Makefile, nvme.c
Hi,
Just a couple of fixes to make it compile on my machine. 
Please pull.
=> Fixes to make it compile

nvme.c
Same fix was applied as in pull request #12.
=> Found another instance of flbas being used as an index into list_item.

linux/nvme.h, nvme.c
derived from:
Intel Solid-State Drive Data Center P3700 Series Product Specification
Mostly copy&paste, but it seems to work:)
=> add additional smart log

Documentation/Makefile, Makefile
* Adds DESTDIR and PREFIX in appropriate places
* Adds share/ to the man path
* Lets the packager override PREFIX
=> Makefile fixes for packagers (DESTDIR / PREFIX)

nvme.c
The compiler rightly warned about an issue in ed3848130, but the fix was
wrong.
There is no guarantee that an int is exactly 32 bits and no guarantee
that a long long is exactly 64 bits. The former one is guaranteed to be
at least 16 bits (but we can safely assume 32 for non-ancient machines).
Imagine an u32 array:
0... 1... 2... 3... 4... 5...
Now cast the pointer to the zeroth element to a 64-bits-int-pointer;
64bit sized int are quite common.
0.......  1.......  2.......
Writing to 0, 1 and 2 would put values in 0, 2 and 4 (on little endian).
And if there is enough data, it would overwrite the stack.
This change moves the casting to the point where the individual values
are copied. That's safe.
=> Don't cast pointers, cast values.

.gitignore, debian/changelog, debian/control, debian/copyright, debian/watch
I am trying to push this package to the Debian archive.
I create the ITP number 810033[1], and I fixed the debian scripts in order to send in this ITP.
[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=810033
=> Fixes in the debian scripts

README.md
Add the openSUSE Tumbleweed package to README.md
Signed-off-by: Johannes Thumshirn <jthumshirn@suse.de>
=> README.md: Add the openSUSE Tumbleweed package

Documentation/nvme-format.1, Documentation/nvme-format.html, Documentation/nvme-format.txt, Documentation/nvme-list-ctrl.1, Documentation/nvme-list-ctrl.html, Documentation/nvme-list-ctrl.txt, debian/copyright
These fixes are required to comply with Debian Policy rules.
=> Fix problems on Debian package

nvme.c
Signed-off-by: Stanislav Kholmanskikh <stanislav.kholmanskikh@oracle.com>
=> nvme: fix the mmap error check

debian/changelog, debian/control, debian/copyright, debian/rules
Dropped all patches as they have all been fixed upstream
Bump changelog version number to 0.5
=> sync with actual debian package

Makefile, nvme.spec.in
This pull request fixes issue #64 Include bash completions in packages.
=> Install bash autocompletion by default

nvme-print.c, src/argconfig.c
Two more fixes, one fixes a null pointer dereference issue on 3 identical string comparisons, the other fix is more of code clean-up to removed an unused parameter.
=> minor fix and code clean up

plugin.c
List reason why command line failed before displaying the usage message
=> Enhanced error reporting for invalid commands and/or extensions. 

nvme.c
When issuing a read to the device, if we pass a data size smaller than the
current sector size, the ioctl() will overflow the data buffer. This will
also happen when reading more than one block from the device, if the buffer
does not have enough bytes to store the result. This patch adds a simple
check using the requested block count to correctly allocate a buffer of
minimum size.
Signed-off-by: Heitor Ricardo Alves de Siqueira <halves@linux.vnet.ibm.com>
=> Fix read/write memory corruption issues

nvme.c
This commit allows nvme-cli to be built with recent gcc/glibc (6.1.1/2.24).
=> purge `readdir_r` -- which is deprecated in recent glibc.

Makefile, nvme-models.c, nvme-models.h, nvme-print.c, nvme-print.h, nvme.c, nvme.h
This branch and patch is based on top of pull request:
https://github.com/linux-nvme/nvme-cli/pull/117
Once that is merged this diff should be cleaned up and can then be reviewed.
=> Jsonify SMART/SMART-ADD and fw-info slots

completions/bash-nvme-completion.sh
The bash completion script has never worked correctly for me.
After reviewing the code, it didn't seem to make too much sense to me
either. Thus, I've rewrote parts of it so that it works. I've also done
a _quick_ audit of all the main commands to make sure they
have the correct arguments available.
=> Fix bash completion script

intel-nvme.c
./nvme intel smart-log-add --json /dev/nvme0n1
=> nvme-cli: nvme-intel implement json output for smart-log

linux/nvme.h, nvme-print.c
=> nvme-cli: Add parsing support for noiob

argconfig.c, argconfig.h, nvme.c
Signed-off-by: Jon Derrick <jonathan.derrick@intel.com>
=> Show help when no or an invalid device is given

intel-nvme.h, nvme-builtin.h
Signed-off-by: Guilherme G. Piccoli <gpiccoli@linux.vnet.ibm.com>
=> nvme-cli: Fix typo in Intel plugin and improve generic help text

nvme.c
Remove unused clear_args()
Signed-off-by: Jon Derrick <jonathan.derrick@intel.com>
=> Show help for nvme reset and subsystem-reset

intel-nvme.c
=> Implement Intel Vendor specific logs 

nvme-print.c
=> fix for issue 219, show-regs reports AQA.ACQS and AQA.ASQS as bytes

nvme.c
Make description in sanitize() const.
=> nvme-cli: make sanitize description const

README.md
Update description of alias for subcommand.
=> nvme-cli: update subcommand alias description in README.md

linux/nvme.h, nvme-builtin.h, nvme-ioctl.c, nvme-ioctl.h, nvme-print.c, nvme.c
=> nvme-cli: Implement get_telemetry_log from 1.3 spec

json.c, json.h
Signed-off-by: Oleksii Timofieiev <tim.oleksii@gmail.com>
=> nvme-cli: Add support of unsigned long long to json routines

intel-nvme.c
Signed-off-by: Oleksii Timofieiev <tim.oleksii@gmail.com>
=> nvme-cli: Fixed incosistency of error handling in intel plugin

wdc-nvme.c
Signed-off-by: Oleksii Timofieiev <tim.oleksii@gmail.com>
=> nvme-cli: fix endianess in WDC plugin.

Documentation/nvme-toshiba-clear-pcie-correctable-errors.1, Documentation/nvme-toshiba-clear-pcie-correctable-errors.html, Documentation/nvme-toshiba-clear-pcie-correctable-errors.txt, Documentation/nvme-toshiba-vs-internal-log.1, Documentation/nvme-toshiba-vs-internal-log.html, Documentation/nvme-toshiba-vs-internal-log.txt, Documentation/nvme-toshiba-vs-smart-add-log.1, Documentation/nvme-toshiba-vs-smart-add-log.html, Documentation/nvme-toshiba-vs-smart-add-log.txt, toshiba-nvme.c, toshiba-nvme.h
Hello nvme-cli team,
I'd like to submit the following changes into the project. It adds a small amount of vendor-specific support for forthcoming Toshiba devices, using the plugin framework.
Thanks and regards,
Andrew Meir
=> Add toshiba plugin code and command documentation.

nvme-lightnvm.c, wdc-nvme.c
Signed-off-by: Alexey Timofeyev <alexey.timofeyev@sk.com>
=> nvme-cli: Fix build breaks for GCC 8.1

Makefile, micron-nvme.c, micron-nvme.h
This plugin adds support for a micron specific firmware download and activation process.
=> Add support for Micron plugin

nvme-print.c
Add Get Feature-Asynchronous Event Configuration can get Telemetry Log Notices Info
=>  nvme-cli: Add Get Feature Command

Documentation/nvme-telemetry-log.txt
Wrote a man page for selecting data area for telemetry.
=> Wrote man page for telemetry

intel-nvme.c
* Remove trailing "\n" so that the output is valid json
=> Remove trailing "\n" so that the output is valid json

nvme-print.c
Before fix string is truncated, not enough information.
CMD: nvme ns-descs /dev/nvme0n1 -o json
> {
>     "nguid" : "d800000000000000"
> }
After Fix, string displayed correctly, JSON is in array format and with more information:
CMD ./nvme ns-descs /dev/nvme0n1 -o json
> {
>    "ns-descs" : [
>       {
>          "nidt" : 2,
>          "nidl" : 16,
>          "type" : "nguid",
>          "nguid" : "d80000000000000004009902ad005076"
>    }
>  ]
> }
=> nvme-print.c : fix ns-descs JSON output

Documentation/nvme-list.1, Documentation/nvme-list.html, Documentation/nvme-list.txt, nvme-models.c
Take from PCI_IDS_PATH or look at some default locations
Updated docs for the envrironment in nvme-list.txt
Regenerated man and html pages.
Fix FILE* close omission in case of error.
=> nvme-models.c - search for pci.ids

Documentation/cmds-main.txt, Documentation/nvme-get-property.1, Documentation/nvme-get-property.html, Documentation/nvme-get-property.txt
Added nvme-get-property documentation for the get-property command added at commit  460a4c0f1dbdf9aaa62932a7ec2f80a755b182f9
=> nvme-get-property : Add documentation

README.md
This makes `README.md` more readable ;)
=> Enable code block syntax highlight in README.md

fabrics.c
Scenario:
1. A nvme controller already exists for FC traddr and host_traddr
2. Running connect all with those parameters again failed
3. nvme-cli result is:
"Failed to write to /dev/nvme-fabrics: Operation already in progress"
4. Exit code for nvme cli is 0
5. After the fix of this commit, exit code is EALREADY (114)
More info:
```
--host-traddr=nn-0x20000090fa94845f:pn-0x10000090fa94845f \
--hostid=d8266f50-5f24-4c55-8959-23d500e4e450 \
--hostnqn=nqn.2014-08.org.nvmexpress:uuid:d8266f50-5f24-4c55-8959-23d500e4e450 \
--traddr=nn-0x500507680c00002b:pn-0x500507680c2a002b \
--transport=fc
Failed to write to /dev/nvme-fabrics: Operation already in progress
0
```
From strace we can see that discovery controller and discovery log page commands
were ok but the creation of the nvme (io) …
=> connect-all: fix exit code on fail to write to /dev/nvme-fabrics

README.md
Working 1.6 build and functional output on current gentoo from mainline portage
=> Added gentoo to README.md

nvme-print.c
=> Print timestamp as a date and time string

nvme.c
"output" has not been freed in some cases.  This patch adds
close_output right after free_mem.
=> nvme: Fix file descriptor leak in telemtry-log

nvme-print.c
=> nvme: fix minor type in id-ctrl human readable output

Documentation/nvme-virtium-save-smart-to-vtview-log.txt, Documentation/nvme-virtium-show-identify.txt, Makefile, plugins/virtium/virtium-nvme.c, plugins/virtium/virtium-nvme.h
Add Virtium plugin extensions, please help me reviewing.
=> Add Virtium plugin extensions

nvme-print.c
=> nvme-print: add pretty print for estimated sanitize time

nvme-print.c
Add newline and missing free for show-regs command.
Add namespace into json output for nvme-list command.
=> Some Json enhancements

linux/nvme.h, nvme-builtin.h, nvme-ioctl.c, nvme-ioctl.h, nvme-print.c, nvme.c
Reviewed-by: Edmund Nadolski <edmund.nadolski@intel.com>
Reviewed-by: Revanth Rajashekar <revanth.rajashekar@intel.com>
=> nvme: add Verify command

README.md
Use 4 spaces before code blocks to ensure proper formatting.
=> Fix code block style in the first section

linux/nvme.h, nvme-builtin.h, nvme-ioctl.c, nvme-ioctl.h, nvme-print.c, nvme-print.h, nvme.c
Please have a look at this, and consider it to be merged.
Thanks,
=> Add support for Get LBA Status command

linux/nvme.h, nvme-print.c
```
Minwoo Im (7):
id-ctrl: update id-ctrl header for 1.4
id-ctrl: show Controller Type(CNTRLTYPE)
id-ctrl: show FRU Globally Unique Identifier(FGUID)
id-ctrl: show Endurance Group Maximum ID(ENDGIDMAX)
id-ctrl: show Persistent Event Log Size(PELS)
id-ctrl: show Persistent Event Log support in LPA
id-ctrl: show Flush command behavior in VWC
linux/nvme.h |  9 ++++++---
nvme-print.c | 37 +++++++++++++++++++++++++++++++++++--
2 files changed, 41 insertions(+), 5 deletions(-)
```
=> Update Identify Controller for 1.4

Documentation/nvme-wdc-vs-fw-activate-history.1, Documentation/nvme-wdc-vs-fw-activate-history.html
This commit made because of make rpm error.
**1 ) Question. Why does (.1, .html) files are included in git?**
(if you want sustain Documentation policy same as now, Please check below suggestion)
**2 ) Suggestion.** 
If there is no other reason to regenerate the Documentations, isn't it better to update when txt files are updated? 
Because generation of .1 .html files makes change only for date or some versions (not related on original txt file), so I think its better to maintain the dates as a txt file updated day.
If this suggestion is accepted, txt file generator/modifier should update .1, .html files as well.
how does it sound?
**make rpm error result below**
**make -C Documentation install-no-build**
make[2]: Entering …
=> Documentation: nvme-wdc-vs-fw-activate-history(1,html) generated

nvme-topology.c
On error, scandir returns -1 and does not allocate memory
for namelist array. In some places in the code return value
of scandir call is not checked. This causes nvme-cli to
attempt to free() an uninitialized pointer, which subsequently
leads to segmentation fault.
To address this issue, check return value of scandir calls
throughout the code.
Fixes #582 
Signed-off-by: Szczerbik, Przemyslaw <przemyslawx.szczerbik@intel.com>
=> Check return value of scandir

linux/nvme.h, nvme-print.c
* Update show_endurance_log
* Update json_endurance_log
=> nvme-cli: Update nvme_endurance_group_log structure

nvme-print.c, nvme.h
* Update show_error_log
* Update json_error_log
=> nvme-cli: Add 'transport type' error to the error log

README.md
Mention the OpenEmbedded/Yocto recipe.
=> README.md: Mention the OpenEmbedded/Yocto recipe

plugins/wdc/wdc-nvme.c
[NVMe-CLI] Updates and fixes to WDC plugin command vs-internal-log for the SN340 drive.
=> [NVMe-CLI] Updates to WDC plugin command vs-internal-log

linux/nvme.h, nvme-print.c
1. Add Controller Memory Buffer Memory Space Control (CMBMSC)
2. Add Controller Memory Buffer Status (CMBSTS)
3. Add Persistent Memory Region Memory Space Control (PMRMSC)
Update show registers
=> nvme-cli: Update NVMe Registers

nvme-print.c, nvme.h
1. Add Controller Memory Buffer Supported (CMBS)
=> nvme-cli: Update Controller Capabilities Register

Documentation/nvme-dera-stat.txt, Makefile, nvme-print.c, plugins/dera/dera-nvme.c, plugins/dera/dera-nvme.h
Add stat sub-command to retrieve Dera device status and additional SMART log.
=> Add Dera plugin extension.

nvme.spec.in, nvmf-autoconnect/udev-rules/71-nvmf-iopolicy-netapp.rules
Specifically ONTAP and E-Series.
=> Add udev rules to set iopolicy for certain NetApp devices

README.md
Signed-off-by: Heiko Thiery <heiko.thiery@gmail.com>
=> README.md: Mention the buildroot package

plugins/shannon/shannon-nvme.c
Shannon Plugin update（for smart-log-add）.
=> Shannon Plugin update.

tests/nvme_get_features_test.py, tests/nvme_test.py
Handling string encoding to utf-8 and also string handling in
tests.
=> Tests: Hande string encoding and handling failures

Documentation/nvme-wdc-log-page-directory.txt, plugins/wdc/wdc-nvme.c, plugins/wdc/wdc-nvme.h
This is a new command with a new man page text file that will need to be regenerated once this pull request has been merged.
=> Add log-page-directory WDC plugin command

plugins/wdc/wdc-nvme.c
=> Fix status displayed by vs-telemetry-controller-option wdc plugin

Documentation/nvme-wdc-log-page-directory.1, Documentation/nvme-wdc-log-page-directory.html, Documentation/nvme-wdc-namespace-resize.1, Documentation/nvme-wdc-namespace-resize.html, Documentation/nvme-wdc-namespace-resize.txt, plugins/wdc/wdc-nvme.c, plugins/wdc/wdc-nvme.h
Add namespace-resize wdc plugin command.
Update vs-internal-log command to support new DUI header version for SN340.
=> Update WDC Plugin commands 

README.md
These patches updated README.md file for the new plugin template.
=> Update README for plugin template

tests/nvme_create_max_ns_test.py, tests/nvme_format_test.py, tests/nvme_fw_log_test.py, tests/nvme_get_features_test.py, tests/nvme_id_ns_test.py, tests/nvme_test.py
Encoding, string handling fixes for subprocess.
Also some related typecast fixes.
=> Encoding for subprocess and typecast fixes

Makefile
This is a fix for: https://github.com/linux-nvme/nvme-cli/issues/663
=> Fixed where libsystem is needed, not just systemd

plugins/virtium/virtium-nvme.c
1. Add function to list power descriptor, and show vendor specific log
2. Fix spelling mistake
Please help me to reviewing this patch.
=> Add function to list power descriptor, and show vendor specific log in Virtium plugin

nvme-ioctl.c, nvme-ioctl.h, nvme.c
=> nvme: refactoring unnecessary functions

Documentation/nvme-transcend-badblock.txt, Documentation/nvme-transcend-healthvalue.txt, Makefile, plugins/transcend/transcend-nvme.c, plugins/transcend/transcend-nvme.h
This plugin will support the Transcend NVMe Devices.
Please feel free to contact me if you have any question.
Thanks.
=> Request to add Transcend Plugin

plugins/memblaze/memblaze-nvme.c, plugins/memblaze/memblaze-utils.h
1. Modify SMART info fellow Intel format;
2. Add Memblaze private SMART info;
3. Compatible with both new and old formats;
Signed-off-by: 丁剑 <jian.ding@memblaze.com>
=> [Memblaze] Modify SMART info

plugins/wdc/wdc-nvme.c
Add parsing version for 0xCA
Changes from review.
Change customer ids
=> Add log page CA parsing

plugins/wdc/wdc-nvme.c
Signed-off-by: Randy Bates <randall.bates@wdc.com>
@jeffreyalien - can you please review also.
=> Bug fixes for CA log page parsing

plugins/wdc/wdc-nvme.c
Signed-off-by: Randy Bates <randall.bates@wdc.com>
=> Add customer id 0x101

Documentation/nvme-create-ns.1, Documentation/nvme-create-ns.html, Documentation/nvme-create-ns.txt, Documentation/nvme-id-iocs.1, Documentation/nvme-id-iocs.html, Documentation/nvme-id-iocs.txt, Documentation/nvme-list-ns.1, Documentation/nvme-list-ns.html, Documentation/nvme-list-ns.txt, completions/_nvme, completions/bash-nvme-completion.sh, linux/nvme.h, nvme-builtin.h, nvme-ioctl.c, nvme-ioctl.h, nvme-print.c, nvme-print.h, nvme.c, plugins/virtium/virtium-nvme.c
Co-authored-by: Klaus Jensen <k.jensen@samsung.com>
=> add io command set support(TP4056)

Documentation/nvme-wdc-vs-smart-add-log.txt, plugins/wdc/wdc-nvme.c
Add support for using uuid index when retrieving the 0xC2 Log Page
Add support for parsing the 0xC0 log page
WDC Plugin update documentation for vs-smart-add-log command
=> [NVME CLI] WDC Plugin Command Updates

nvme-print.c, plugins/zns/zns.c
Capitalize and remove lx from reporting.
=> Two more small fixes for ZNS

README.md
Signed-off-by: Stephen Kitt <steve@sk2.org>
=> Add Debian installation instructions

plugins/wdc/wdc-nvme.c
Signed-off-by: Randy Bates <randall.bates@wdc.com>
=> Update and Parse FB log page

plugins/scaleflux/sfx-nvme.c, plugins/scaleflux/sfx-nvme.h
add sfx set/get-feature sub_cmds to do clean card and change capacity.
=> ScaleFlux: add set/get-feature sub cmd

Documentation/nvme-wdc-vs-temperature-stats.1, Documentation/nvme-wdc-vs-temperature-stats.html, Documentation/nvme-wdc-vs-temperature-stats.txt, plugins/wdc/wdc-nvme.c, plugins/wdc/wdc-nvme.h
Implementing a new command vs-temperature-stats.
=> Drv 852 development

Documentation/nvme-wdc-capabilities.1, Documentation/nvme-wdc-capabilities.html, Documentation/nvme-wdc-capabilities.txt, plugins/wdc/wdc-nvme.c, plugins/wdc/wdc-nvme.h
New command to list the capabilities of the nvme device with respect to the other commands in the WDC plugin.
=> Add WDC Plugin Capabilities Command

.gitignore
=> Add rpm build output on gitignore

plugins/zns/zns.c
=> Handling system error #768

Documentation/nvme-micron-clear-pcie-errors.1, Documentation/nvme-micron-clear-pcie-errors.html, Documentation/nvme-micron-clear-pcie-errors.txt, Documentation/nvme-micron-internal-log.1, Documentation/nvme-micron-internal-log.html, Documentation/nvme-micron-internal-log.txt, Documentation/nvme-micron-nand-stats.1, Documentation/nvme-micron-nand-stats.html, Documentation/nvme-micron-nand-stats.txt, Documentation/nvme-micron-pcie-stats.1, Documentation/nvme-micron-pcie-stats.html, Documentation/nvme-micron-pcie-stats.txt, Documentation/nvme-micron-selective-download.1, Documentation/nvme-micron-selective-download.html, Documentation/nvme-micron-selective-download.txt, Documentation/nvme-micron-temperature-stats.1, Documentation/nvme-micron-temperature-stats.html, Documentation/nvme-micron-temperature-stats.txt, plugins/micron/micron-nvme.c, plugins/micron/micron-nvme.h
Added support for latest Micron NVMe controllers
=> Micron plugin updates with documentation of micron plugin commands

plugins/wdc/wdc-nvme.c
Add support to wdc plugin commands for the following commands on SN345 drives:
vs-fw-activate-history
clear-fw-activate-history
clear-pcie-correctable-error
=> SN345 changes

plugins/wdc/wdc-nvme.c
Add drive info capability to ZN355
=> [nvme-cli] WDC plugin name change ZN345 to ZN355

plugins/wdc/wdc-nvme.c
Interpreting of new capability values that enable the FW activation history and clear FW activation history commands when showing drive capabilities.
=> Update capabilities command for some alternate command versions

Documentation/nvme-wdc-vs-internal-log.1, Documentation/nvme-wdc-vs-internal-log.html, Documentation/nvme-wdc-vs-internal-log.txt, plugins/wdc/wdc-nvme.c
Updates to documentation and capabilities checking for vs-internal-log command.
=> Regression updates

plugins/intel/intel-nvme.c
Add new fields to the Intel's VU smart log
and print these new fields in json and human readable formats
Modify the human readable format function
=> nvme-cli: Intel:  Update Intel VU Smart Log Add

nvme-print.c
Hello Keith,
Here are some minor ZNS print fixes when using human readable format.
Kind regards,
Niklas
=> Zns print fixes

nvme-print.c
=> nvme-print: Show more async event config fields

plugins/wdc/wdc-nvme.c, plugins/wdc/wdc-nvme.h
[nvme cli] Fix vs-smart-add-log min/max user data erase counts
=> [nvme cli] Add WDC plugin command vs-pcie-stats

plugins/wdc/wdc-nvme.c, plugins/wdc/wdc-utils.c, plugins/wdc/wdc-utils.h
vs-nand-stats not printing json format
vs-nand-stats not printing raw format for several fields
vs-temperature-stats not printing json format
vs-drive-info not printing json format
=> [NVME-CLI] WDC Plugin Fixes for SN-730

nvme.c
Before re-reading partition information from a block device, to make
block size of the block device, application should do either:
- Close current file descriptor and re-open it again.
- Request block device to set block size by itself.
Kernel community has discussions about it, and can be found at [1].
The first option might not be good for readability in this program which
is one-shot command-based application.  All the subcommands are
constructed "fd open -> issue command -> fd close".  I don't want to
break the common style for this requirement.
This patch takes the second one and it just ioctl() to the block device
to update it's block size to a given value.
[1] https://lore.kernel.org/linux-nvme/20210105150214.GA16251@lst.de/T/#u
=> nvme: set block size to blkdev before re-read partition

plugins/wdc/wdc-nvme.c
Change to use Power on Hours instead of Timestamp in certain cases
Fix Entry order so entries are displayed oldest to newest
=> [nvme-cli] WDC plugin fixes for vs-fw-activate-history command

nvme-ioctl.c, nvme-ioctl.h, nvme.c
=> nvme: device self test cdw10 specific fields

Documentation/nvme-resv-acquire.1, Documentation/nvme-resv-acquire.html, Documentation/nvme-resv-acquire.txt, Documentation/nvme-resv-release.1, Documentation/nvme-resv-release.html, Documentation/nvme-resv-release.txt
=> Typo s/rtyep/rtype/g

nvme.c
=> nvme: fix get and set features feature-id data type

nvme-print.c
=> nvme: add latest opcodes for command supported and effects log

nvme-print.c
=> nvme: remove zns command set opcodes from the effects log

nvme-print.c
=> nvme: print NSFEAT UIDREUSE bit in human readable format

nvme.c
If device formatted with non-zero metadata size and input
metadata size is less than that it can be fit into mentioned
block count from input then round it of to fit into block count.
=> nvme: Round of the metadata size to fit into block count

.github/workflows/c-cpp.yml, nvme-print.c
=> Trying to get a ppc64le build going

nvme.c, plugins/memblaze/memblaze-nvme.c, plugins/memblaze/memblaze-nvme.h, plugins/memblaze/memblaze-utils.h
1、Added clear-error-log feature
2、Support high latency log
3、Support IO latency histogram
4、Modify smart-log-add to support more projects
5、Modify some prompt words and rename some functions
=> Memblaze has some feature additions and some minor changes

nvme-print.c
=> nvme-print: refactor sanitize log status string

nvme-print.c
=> nvme-print: align switch-case with existing style

linux/nvme.h, nvme-status.c
=> nvme-status: add status to error no support for path related errors

plugins/zns/zns.c
=> zns: fix namespace-id data type in multiple places

nvme-print.c
=> nvme-print: add one space around the operators

nvme-print.c, nvme-print.h
=> nvme-print: fix fetching status code type and status data type

nvme-ioctl.c, nvme-ioctl.h, plugins/zns/zns.c
=> zns: fix zone management receive command zra and zrasf data types

Documentation/nvme-nvm-id-ctrl.1, Documentation/nvme-nvm-id-ctrl.html, Documentation/nvme-nvm-id-ctrl.txt, completions/_nvme, completions/bash-nvme-completion.sh
This is to add the man page for the NVM comand set Identify Controller
struture and zsh, bash completions.
=> nvme: add man page and completions of nvm command set id controller

nvme-print.c
Hello,
Here's couple of small details that I fixed while working with this tool. There was some other mods that I made also, but it seems that those were already handled in the most recent version.
BR, Affe
=> Adding "Ignore Existing Key" parameter to rescap, and some minor re-ordering

nvme-print.c, nvme-print.h
=> nvme-print: remove unused argument passing to json output format print

linux/nvme.h, nvme-print.c, nvme-status.c
=> nvme: add path related error status codes

nvme.c
=> nvme: fix printing set-feature FID and print cdw12, save fields

nvme.c
=> nvme: fix status field masking and data type

fabrics.c, nvme.c, plugins/zns/zns.c
=> nvme-cli: misc. fixes for memory allocation failure case

fabrics.c
The previous fix had an issue with referrals, as it would take
the default values and apply them to all referral entries.
And if the default entries were for 'loop', the default ctrl_loss_tmo
setting would not be used, but rather '-1'.
So this patch reverts the previous patch and correctly blanks
out the ctrl_loss_tmo setting when constructing the connect string.
Fixes: bdf4f3b ("fabrics: ctrl_loss_tmo setting is invalid for 'loop'")
=> fabrics: correctly handle ctrl_loss_tmo settings for loop

nvme-print.c
=> nvme-print: fix register size for raw format print

fabrics.c
Add a helper function that sets the default kato value for the
discovery controllers. Along with ensuring a non-zero kato value
(i.e. NVMF_DEF_DISC_TMO) is passed to a persistent discovery
controller, it also ensures a zero kato value is passed to a
non-persistent discovery controller, as mandated by the NVMe spec.
=> fabrics: ensure zero kato for non-persistent controllers

nvme-print.c
Currently command support and effects log page on json format
printing all the opcodes irrespective of the command supported.
Most part of the log page is "Unkown" opcodes, fixed that. Also
added two json objects "acs" and "iocs" to print them seperately.
=> nvme-print: improve command support and effects log json format

Documentation/nvme-resv-notif-log.1, Documentation/nvme-resv-notif-log.html, Documentation/nvme-resv-notif-log.txt, completions/_nvme, completions/bash-nvme-completion.sh, linux/nvme.h, nvme-builtin.h, nvme-ioctl.c, nvme-ioctl.h, nvme-print.c, nvme-print.h, nvme.c
This is to add the support for the reservation notification
log page with LID = 0x80.
=> nvme: add reservation notifacation log page

nvme.c
For Copy command add namespace id as a user config field
=> nvme: add namespace id config field for copy command

plugins/wdc/wdc-nvme.c
SN730 Updates for FW Maintenance Release
Add support for 2 new customer ids
=> 2 WDC Plugin Updates

nvme.c
=> nvme: fix commenting style

nvme.c
=> nvme: make else if uniform

nvme.c
=> nvme: nvme get and set features buffer length clean up

nvme.c
In virtualization management command CDW10 has been added user
parameters config structure which redundant and CDW11 has only
16 bits (NR) are defined use that only.
Refactor the CDW10 filling and NRM print.
=> nvme: fix and refactor virt mgmt cdw10 and cdw11 arguments

Makefile
code duplicated while squashing the commits
=> Makefile: remove duplicated line for zns.o

nvme.c
=> nvme: add space in persistent event log desc between words

plugins/wdc/wdc-nvme.c
1. [nvme-cli] WDC plugin name change ZN355 to ZN350
2. Added log page directory capability to ZN350.
3. Updates to vs-smart-add-log command (smart Information page-Log Identifier C0h) for ZN350.
=> ZN-350 changes

fabrics.c
Print the device (nvme1, nvme2, etc.) that was used to perform the discover command in the JSON output. 
Example:
```
{
"device" : "nvme1",      <- This is the new line that we print
"genctr" : 6,
"records" : [
{
"trtype" : "tcp",
"adrfam" : "ipv4",
"subtype" : "nvme subsystem",
"treq" : "not specified, sq flow control disable supported",
"portid" : 1,
"trsvcid" : "8009",
"subnqn" : "starfleet",
"traddr" : "127.0.0.1",
"sectype" : "none"
},
```
=> Add device id in JSON output

nvme-print.c
Previously celsisu values were printed by smart-log and get-feature commands.
But kelvin values were printed by id-ctrl command.
For human readable format print both kelvin and celsisu temperature values.
=> nvme-print: print both kelvin and celsius temperature values

nvme-print.c
=> nvme-print: add controller register cap 44th bit

plugins/wdc/wdc-nvme.c
Removed unwanted print statement in WDC plugin's vs-smart-add-log command.
=> ZN-350-bugfix

Documentation/nvme-get-lba-status.1, Documentation/nvme-get-lba-status.html, Documentation/nvme-get-lba-status.txt, nvme.c
=> nvme: adding get lba status command man page

Documentation/nvme-get-feature.1, Documentation/nvme-get-feature.html, Documentation/nvme-get-feature.txt, Documentation/nvme-set-feature.1, Documentation/nvme-set-feature.html, Documentation/nvme-set-feature.txt, completions/_nvme, completions/bash-nvme-completion.sh, nvme-ioctl.c, nvme-ioctl.h, nvme.c, plugins/intel/intel-nvme.c, plugins/memblaze/memblaze-nvme.c, plugins/micron/micron-nvme.c, plugins/seagate/seagate-nvme.c, plugins/shannon/shannon-nvme.c, plugins/toshiba/toshiba-nvme.c, plugins/wdc/wdc-nvme.c
=> nvme: add uuid index in get and set features command

Documentation/nvme-list-ctrl.1, Documentation/nvme-list-ctrl.html, Documentation/nvme-list-ctrl.txt, nvme-print.c, nvme-print.h, nvme.c
=> nvme: add json output format for list_crl

plugins/zns/zns.c
=> zns: style fixes in zns plugin

Documentation/nvme-list-ns.1, Documentation/nvme-list-ns.html, Documentation/nvme-list-ns.txt, nvme-print.c, nvme-print.h, nvme.c
=> nvme: add json output format for list_ns

plugins/zns/zns.c
get_zdes_bytes shall return constant value in failed cases in
order to catch in called function
Check if the get_zdes_bytes returned proper data length or not.
=> zns: fix get_zdes_bytes return value in failed cases

plugins/wdc/wdc-nvme.c
=> wdc-nvme: fix the build failure

nvme.c
=> nvme: add latency parameter for passthru commands

nvme.c
=> nvme: add persistent event log action field invalid check

Documentation/nvme-id-iocs.1, Documentation/nvme-id-iocs.html, Documentation/nvme-id-iocs.txt, linux/nvme.h, nvme-print.c, nvme-print.h, nvme.c
=> nvme: add json, binary and human readable output format for id iocs

Documentation/nvme-admin-passthru.1, Documentation/nvme-admin-passthru.html, Documentation/nvme-admin-passthru.txt, Documentation/nvme-io-passthru.1, Documentation/nvme-io-passthru.html, Documentation/nvme-io-passthru.txt
=> nvme: update passthru commands man page with latency parameter details

nvme-print.c
=> nvme-print: sanitize log style fix

fabrics.c, linux/nvme.h, nvme-print.c
=> nvme: add missing endianness annotations

linux/nvme.h, nvme-print.c
=> nvme: fix the fw-log structure and show fw log changes

linux/nvme.h, nvme-print.c
=> nvme: add identify controller structure 2.0 spec. fields

nvme-print.c
=> nvme: extend existing id ctrl parameters as per 2.0

nvme.c
=> nvme: add status to error number for id_uuid and verify_cmd

nvme-ioctl.c
=> nvme: style fix

Documentation/nvme-verify.1, Documentation/nvme-verify.html, Documentation/nvme-verify.txt
=> nvme: add verify command man page

Documentation/nvme-capacity-mgmt.1, Documentation/nvme-capacity-mgmt.html, Documentation/nvme-capacity-mgmt.txt, completions/_nvme, completions/bash-nvme-completion.sh, linux/nvme.h, nvme-builtin.h, nvme-ioctl.c, nvme-ioctl.h, nvme.c
Host software issues this Capacity Management command to
configure/Create/Delete Endurance Groups and NVM Sets in an
NVM subsystem.
Signed-off-by: Karthik Balan <karthik.b82@samsung.com>
=> nvme: add capacity management command support

Documentation/nvme-id-domain.1, Documentation/nvme-id-domain.html, Documentation/nvme-id-domain.txt, completions/_nvme, completions/bash-nvme-completion.sh, linux/nvme.h, nvme-builtin.h, nvme-ioctl.c, nvme-ioctl.h, nvme-print.c, nvme-print.h, nvme.c
=> Add Identify CNS 0x18 Domain List Support

fabrics.c
As per section 7.4.9.3 "Transport Service Identifier" of the NVMe over
Fabrics 1.1 specification, the default IANA port number for a NVMe/TCP
discovery controller is 8009. But at the same time, it also clearly
states that NVMe/TCP I/O controllers should not use TCP port number
8009, but may instead use 4420 as the default here.
So make sure to fill these values appropriately, and pass it down.
=> fabrics: add default port number for NVMe/TCP I/O controllers

.github/workflows/c-cpp.yml, nvme-print.c, nvme-print.h, nvme.c, nvme.h, plugins/dera/dera-nvme.c, plugins/intel/intel-nvme.c, plugins/memblaze/memblaze-nvme.c, plugins/micron/micron-nvme.c, plugins/scaleflux/sfx-nvme.c, plugins/seagate/seagate-nvme.c, plugins/shannon/shannon-nvme.c, plugins/toshiba/toshiba-nvme.c, plugins/wdc/wdc-nvme.c, plugins/ymtc/ymtc-nvme.c
=> Update workflow to checkout libnvme

plugins/wdc/wdc-nvme.c, plugins/wdc/wdc-nvme.h
Update WDC plugin version to 1.15.1
Signed-off-by: Jeff Lien jeff.lien@wdc.com
=> Split media units written/read into hi/lo 64 bit fields

README.md
it should be `git submodule update --init`
=> Fix git submodule command

Documentation/nvme-supported-log-pages.1, Documentation/nvme-supported-log-pages.html, Documentation/nvme-supported-log-pages.txt, completions/_nvme, completions/bash-nvme-completion.sh, linux/nvme.h, nvme-builtin.h, nvme-ioctl.c, nvme-ioctl.h, nvme-print.c, nvme-print.h, nvme.c
=> nvme: add supported log pages log page (lid = 0x00)

Documentation/nvme-list-endgrp.1, Documentation/nvme-list-endgrp.html, Documentation/nvme-list-endgrp.txt, completions/_nvme, completions/bash-nvme-completion.sh, linux/nvme.h, nvme-builtin.h, nvme-ioctl.c, nvme-ioctl.h, nvme-print.c, nvme-print.h, nvme.c
=> add identify endurance group list (cns 0x19) support

plugins/intel/intel-nvme.c
Now we only perfom a single query and place the result in a byte
array. Then,  we determine the right log page layout in terms of
the media version.
Signed-off-by: Francisco Munoz <francisco.munoz.ruiz@intel.com>
=> Intel latstats: Optane clears latency stats evey time the log page is pulled, so we only query once

linux/nvme.h
Based spec : NVMe-NVM-Command-Set-Specification-1.0a-2021.07.26-Ratified
=> nvme.h: nvme_id_ns rsvd area modified as lbaf fields

nvme-print.c
Generate json output when appropriate option is specified for zns report-zones.
=> add json support for zns report zones

linux/nvme.h, nvme-print.c, plugins/zns/zns.c
NVMe-Zoned-Namespace-Command-Set-Specification-1.1a-2021.07.26-Ratified
Figure 37: Zone Descriptor Data Structure - Zone Attributes Information
=> zns: Add missing Zone Attributes Information on zone descriptor

nvme-print.c, nvme-print.h, plugins/zns/zns.c, plugins/zns/zns.h
Signed-off-by: Andreas Hindborg <andreas.hindborg@wdc.com>
=> zns: Add list command

nvme.c
To avoid formarting a busy namespace accidently a new function called `open_exclusive()` was added. 
This function opens a namespace in exclusive mode `(O_EXCL)`. If this fails with error `EBUSY` an log
messages hints to the `--force` command line option. By calling `nvme format` with the `--force` option it
will continue formating the namespace.
This patch fixes issue: #1095
Signed-off-by: Olaf Schmerse <olaf.schmerse@ionos.com>
=> nvme: fail on busy namespace

Documentation/nvme-connect.1, Documentation/nvme-connect.html, Documentation/nvme-connect.txt
I noticed irritating spelling and think there might be errors in the docs for `nvme-connect`
=> fix minor doc issues

ccan/ccan/check_type/LICENSE, ccan/ccan/check_type/_info, ccan/ccan/check_type/check_type.h, ccan/ccan/container_of/LICENSE, ccan/ccan/container_of/_info, ccan/ccan/container_of/container_of.h, ccan/ccan/list/LICENSE, ccan/ccan/list/_info, ccan/ccan/list/list.c, ccan/ccan/list/list.h, ccan/ccan/str/LICENSE, ccan/ccan/str/_info, ccan/ccan/str/debug.c, ccan/ccan/str/str.c, ccan/ccan/str/str.h, ccan/ccan/str/str_debug.h, ccan/licenses/BSD-MIT, ccan/meson.build, meson.build, nvme-print.c, nvme-print.h, nvme.c
Revert the change from #1188 as we have ccan now back in the nvme-cli, there is no point in not having the dynamic version for the effects log parser feature.
=> Revert use array

.github/workflows/c-cpp.yml, fabrics.c, nvme.h
Recent merge introduced some build problems. Fix them
#1220
=> Build fixes

.github/workflows/meson.yml, meson.build, subprojects/json-c.wrap
Update to latest libnvme version.
=> libnvme: git submodule update

Documentation/nvme-check-dhchap-key.txt, Documentation/nvme-connect.txt, Documentation/nvme-gen-dhchap-key.txt, Makefile, fabrics.c, meson.build, nvme-builtin.h, nvme.c, util/argconfig.h, util/base64.c, util/base64.h, util/meson.build
Hi all,
here's a patchset to implement in-band authentication support. It relies on the corresponding pull request (https://github.com/linux-nvme/libnvme.git#100), and obviously the kernel patches to implement the actual functionality.
So if we agree on the kernel interface we can merge it, otherwise we'll need to hold it off until the kernel side is merged.
=> In-band authentication support

plugins/wdc/wdc-nvme.c, plugins/wdc/wdc-nvme.h
=> [nvme-cli] Improve formatting for WDC plugin command - vs-smart-add-log output

completions/_nvme
=> completions: fix zsh completion (wrong string end)

plugins/wdc/wdc-nvme.c
=> [nvme-cli] Undo revert of ZN350 changes in the master branch

ccan/meson.build, plugins/memblaze/memblaze-nvme.c, plugins/micron/micron-nvme.c
=> Ccan debug build

completions/bash-nvme-completion.sh
=> bash: Fix nvme completion

Documentation/nvme-zns-open-zone.1, Documentation/nvme-zns-open-zone.html, Documentation/nvme-zns-open-zone.txt, Documentation/nvme-zns-set-zone-desc.1, Documentation/nvme-zns-set-zone-desc.html, Documentation/nvme-zns-set-zone-desc.txt, Documentation/nvme-zns-zrwa-flush-zone.1, Documentation/nvme-zns-zrwa-flush-zone.html, Documentation/nvme-zns-zrwa-flush-zone.txt, nvme-print.c, plugins/zns/zns.c, plugins/zns/zns.h
A couple of cleanups for the ZRWA to align it with the existing
style.
=> zns: small cleanups to zrwa

Documentation/nvme-connect.txt, fabrics.c
Commit 0ad49ad ("Print device name on connect")
=> Print device name on connect

Documentation/nvme-connect.1, Documentation/nvme-connect.html, fabrics.c
=> Generate nvme-connect documentation

plugins/memblaze/memblaze-nvme.c
Signed-off-by: jinhua2021 <jinhua.huang@memblaze.com>
=> memblaze-nvme: remove power loss protection from smart-log-add

Makefile, meson.build, nvme.control.in, nvme.spec.in, nvmf-autoconnect/dracut-conf/70-nvmf-autoconnect.conf.in
Fix some errors revealed when trying to build using https://sr.ht/~lattis/muon
=> Meson fixups

Makefile, meson.build, nvme.c
Splitted out the build system changes from #1297
=> build: cleanup and make the defines more consistent

plugins/wdc/wdc-nvme.c
=> [nvme-cli] Fix vs-smart-add-log bug to retrieve customer id

plugins/wdc/wdc-nvme.c
=> [nvme-cli] Fix build warnings in WDC Plugin from Issue #1309

plugins/micron/micron-nvme.c
=> [nvme-cli] Fix build warnings in Micron Plugin - Issue 1317

Documentation/nvme-media-unit-stat-log.1, Documentation/nvme-media-unit-stat-log.html, Documentation/nvme-media-unit-stat-log.txt, completions/_nvme, completions/bash-nvme-completion.sh, nvme-builtin.h, nvme-print.c, nvme-print.h, nvme.c
=> nvme: Add Media Unit Status log page(LID: 0x10)

subprojects/libnvme.wrap
Get fix for incorrect controller display (libnvme PR#195)
=> build: Update libnvme wrap

plugins/wdc/wdc-nvme.c, plugins/wdc/wdc-nvme.h
=> [nvme-cli] Add support for Additional SN450 Device

fabrics.c, nvme.c, nvme.h, plugins/micron/micron-nvme.c, plugins/wdc/wdc-nvme.c, plugins/zns/zns.c
=> Handle libnvme error codes and return proper error code when termiating nvme-cli

Makefile, meson_options.txt
=> meson: fix default dracut directory based on dracut manual

nvme-print.c
=> nvme: Add Enhanced Controller Meta Data(FID: 0x7D)

Documentation/nvme-supported-cap-config-log.txt, completions/_nvme, completions/bash-nvme-completion.sh, nvme-builtin.h, nvme-print.c, nvme-print.h, nvme.c
=> nvme: Add Supported Capacity Configuration List log page(LID: 0x11)

plugins/wdc/wdc-nvme.c
Added telemetry log fetch support for SN810, SN530 and SN740 series NVMe SSDs through wdc vs-internal-log command.
=> Added telemetry log fetch support for WDC vs-internal-log command

plugins/wdc/wdc-nvme.c, plugins/wdc/wdc-nvme.h
Change sn450 name to sn560
Update wdc plugin version to 1.16.3
=> [nvme-cli] Fix sn650 capabilities setting

plugins/wdc/wdc-nvme.c
Created a new function - wdc_get_fw_cust_id that will simplfy the
code and handle the free of the allocated data
Original message from PR-1375:
Fix incorrect access after memory is already freed up. Also couple
of minor fixes to use correct cpu endianness while accessing data
read from drive.
Co-Authored-by: Indraneel-M
=> [nvme-cli] Additional changes for PR 1375

plugins/netapp/netapp-nvme.c
The nvme ns desc uuid handling in the NetApp plugin for
ontapdevices is broken after the recent upgrade to libnvme. The
uuid handling logic here was flawed to begin with, so rework this
code to ensure the respective uuid descriptor itself is stored in
the ontapdevice_info structure and processed appropriately.
=> netapp-nvme: fix nvme ns desc uuid handling for ontapdevices

util/parser.c
Make the documentation consistent with the other header files.
fixed whitespace issues and indentations levels.
=> parser: Streamline documentation

README.md
New meson users are not aware of this rather nifty update
mechanism. Mention it in the README.
=> README: Mention meson subprojects update

Documentation/cmd-plugins.txt, Documentation/nvme.txt
Added intel plugin commands in list
=> cmds-main: Add intel plugin commands

Documentation/cmd-plugins.txt
updated cmd-plugins file with huawei plugin commands
=> cmd-plugins: Add huawei plugin commands

nvme.c, subprojects/libnvme.wrap
recover functionallty of https://github.com/linux-nvme/nvme-cli/commit/7f8d194e2532ba5c8240d731e87c39186ba03764
list ns with CNS(0x07, 0x1A) enabled
Reported-by: Kyungsik Shin <ks1012.shin@samsung.com>
\+ libnvme update
=> nvme: list_ns bug fix (csi option enable)

Documentation/cmd-plugins.txt
updated cmd-plugins.txt file with dera,
micron plugin commands.
=> cmd-plugins: Add dera, micron plugin commands in doc

Documentation/cmd-plugins.txt
netapp, toshiba plugin commands has been
added in cmd-plugins.txt
=> cmd-plugins: plugin commands update in doc

nvme-print.c, nvme-print.h, nvme.c, subprojects/libnvme.wrap
Patches to fixup the ANA path state display.
Fixes issue #1417.
=> Fixup ANA path state display

tests/README, tests/meson.build, tests/nvme_copy_test.py, tests/nvme_dsm_test.py, tests/nvme_verify_test.py
Tests has been added for copy, verify, DSM
commands and respective tests updated in meson.build
file.
=> tests: Add tests for copy, verify, dsm commands

completions/bash-nvme-completion.sh
Signed-off-by: Martin Belanger <martin.belanger@dell.com>
=> Fix typo - hsot to host

Documentation/cmd-plugins.txt
updated cmd-plugins.txt file with transcend, virtium
plugin commands
=> cmd-plugins: Add transcend, virtium plugin commands

Documentation/cmd-plugins.txt
Added WDC plugin commands in cmd-plugins.txt file
=> cmd-plugins: Add plugin commands in doc

Documentation/cmd-plugins.txt, Documentation/nvme-zns-id-ns.txt
updated cmd-plugins.txt file with ZNS commands.
=> cmd-plugins: Add ZNS plugin commands 

nvme-print.c
Restore nvme-cli 1.x behavior to print the full path to the device
file. We assume that the devtmpfs is mounted under /dev which is the
case for any systemd based distro and a de-facto standard.
But SPDK users see their device populated under /dev/spdk have their
device file appear. So instead blindly prefix /dev do a stat to check
if the file exist.
If our educated guesses fail, don't add the full path. This should be
really a corner case and as long no one complains don't overengineer.
Fixes: #1422
=> nvme: Print full device path

tests/meson.build, tests/nvme_lba_status_log_test.py
Added test case for lba status log page and updated
meson.build accordingly.
=> tests: Add tests for lba status log page

nvme-rpmb.c
=> Fixed spelling for Partition

fabrics.c
libnvme doesn't know at controller creation if the new controller is
going to be discovery controller. But nvme-cli knows it, so just set
defaults on the caller level.
Fixes: #1475
=> fabrics: Set default trsvcid ports for TCP and RDMA

meson_options.txt
Signed-off-by: Morten Linderud <morten@linderud.pw>
=> meson: Install udev rules to /usr/lib 

.github/dependabot.yml
Signed-off-by: Boris Glimcher <Boris.Glimcher@emc.com>
=> ci: create first dependabot.yml

fabrics.c
This is just a small change to fix up an error message.
=> fabrics: fix help string for connect traddr option

Documentation/nvme-ana-log.txt, fabrics.c, nvme-models.c, nvme-print.c, nvme-rpmb.c, nvme.c, plugins/dera/dera-nvme.c, plugins/huawei/huawei-nvme.c, plugins/intel/intel-nvme.c, plugins/memblaze/memblaze-nvme.c, plugins/memblaze/memblaze-utils.h, plugins/micron/micron-nvme.c, plugins/netapp/netapp-nvme.c, plugins/ocp/ocp-nvme.c, plugins/scaleflux/sfx-nvme.c, plugins/seagate/seagate-nvme.c, plugins/shannon/shannon-nvme.c, plugins/toshiba/toshiba-nvme.c, plugins/transcend/transcend-nvme.c, plugins/virtium/virtium-nvme.c, plugins/wdc/wdc-nvme.c, plugins/ymtc/ymtc-nvme.c, plugins/zns/zns.c, subprojects/libnvme.wrap, util/argconfig.c
A bunch of fixes found by coverity.
Nothing special, but the wdc plugin has some 'creative' usage when trying to display raw values.
Maybe someone should have a look at that.
=> Coverity fixes

nvme.c
when write option is set(but opcode is not), file should open with read flag
same for read
it occur 'Bad file descriptor' error when access the file
Reported-by: Kyungsik Shin <ks1012.shin@samsung.com>
=> nvme: Fix error when passthru does not match opcode based flags

meson.build, subprojects/uuid.wrap
see util-linux/util-linux#1657
Signed-off-by: Boris Glimcher <Boris.Glimcher@emc.com>
=> build: use uuid wrap for fallback build

Documentation/meson.build, Documentation/nvme-wdc-vs-device-waf.txt, plugins/wdc/wdc-nvme.c, plugins/wdc/wdc-nvme.h
Added wdc plugin command vs-device-waf
Updated the format of the vs-cloud-log command data printout to match the requirements.
=> Changes for WDC SN810-2 Drive

plugins/wdc/wdc-nvme.c, plugins/wdc/wdc-nvme.h
=> wdc:  Add support for new WDC Devices

Documentation/nvme-verify.txt, Documentation/nvme-write-zeroes.txt, nvme-print.c, nvme.c, plugins/zns/zns.c, subprojects/libnvme.wrap
TP-4068 Contains changes to support Enhanced Protection Information as well as support for extended Reference Tags
TP-4084 Contains changes to support Time to Ready enhancements.
=> Changes to support TP-4068  and TP-4084

fabrics.c
With TP8013 each discovery subsystem can have a unique subsystem
NQN. So a check for the subsystem NQN is not sufficient anymore
to figure out if this is a discovery subsystem, one needs to check
the 'subsystype' sysfs attribute, too.
=> fabrics: support unique discovery subsystem NQN

nvme-print.c, subprojects/libnvme.wrap
1. update libnvme wrap
2. Add missing active power workload field
3. Use enums for power scale
4. Fix indentation
=> libnvme wrap update, update power descriptor fields

plugins/scaleflux/sfx-nvme.c
A couple of cleanups on #1556 
- indention level
- commit message tweaking
=> Sfx get lat stats log csd3000

plugins/wdc/wdc-nvme.c
=> wdc: Fix SN560 Device Capabilities

plugins/wdc/wdc-nvme.h
I forgot to include this in PR 1568.
=> wdc: Increment WDC Plugin Version

plugins/dell/dell-nvme.c, plugins/dell/dell-nvme.h, plugins/meson.build
Signed-off-by: Boris Glimcher <Boris.Glimcher@emc.com>
=> plugins: Add Dell plugin with basic id-ctrl

subprojects/json-c.wrap
Update to the latest the json-c wrap version.
=> build: Update json-c.wrap

Documentation/nvme.txt
Required information on how an invoking process might determine success or
failure.
=> docs: Add nvme command RETURNS section for #1560 requirement

.github/workflows/release.yml, release.sh
Automate the release with a script. This ensures we always do the same steps for an release. It also documents how to do it.
See also: https://github.com/linux-nvme/libnvme/issues/287
=> Add release script

nvme.c
collect_effects_log eats up the return code from
nvme_get_log_cmd_effects. Forward it to the shell..
Fixes: 155fbebfe7b7 ("Update effects-log to handle multiple command sets")
Fixes: #1601
=> nvme: Return status/error code for effects-log command

plugins/ymtc/ymtc-nvme.c
fix ymtc additional smart info display
=> ymtc: fix ymtc additional smart info display

nvme.c
Remove the duplicate prinfow assignment
Signed-off-by: Francis Pravin Antony Michael Raj <francis.michael@solidigm.com>
Signed-off-by: Jonathan Derrick <jonathan.derrick@solidigm.com>
=> nvme: Remove duplicate line

fabrics.c
In certain corner cases, the kernel will not populate a nvme subsystem
but only create a nvme controller. nvme_scan_ctrl will fail in such
scenarios to find the controller object. Let's do the lookup based on
the ctrl name only.
Fixes [#431](https://github.com/linux-nvme/libnvme/issues/431)
=> fabrics: Avoid nvme_scan_ctrl when disconnecting

meson.build, wrapper.c
Unfortunately, we have a couple of build fallouts.
Fixes #1628
=> Fix release fallouts

ccan/meson.build, meson.build, nvme.c, plugins/ocp/ocp-nvme.c, plugins/solidigm/solidigm-garbage-collection.c, plugins/solidigm/solidigm-smart.c, plugins/wdc/wdc-nvme.c
Small commit message changes and initialization of the struct arg updated.
See #1608
[I couldn't push it on the original branch, hence this new PR]
=> plugins: minor fixes v2

nvme-print.c
=> print: Add Controller Ready Timeout Exceeded HW error code

nvme-print.c
=> nvme-print: fix wrong json key

plugins/zns/zns.c
=> zns.c: report zones should be started after retrieved zone

nvme-print.c, nvme.c, plugins/micron/micron-nvme.c, plugins/solidigm/solidigm-garbage-collection.c, plugins/solidigm/solidigm-latency-tracking.c, plugins/wdc/wdc-nvme.c
During #1682 development these various small build fixes came to be.
=> Various small build fixes

plugins/wdc/wdc-nvme.c, plugins/wdc/wdc-nvme.h
Update WDC plugin version to 2.1.2
=> plugins/wdc: Add support for SN660 drive

Makefile
=> Makefile: Add 'make debug' for debug build

fabrics.c, nvmf-autoconnect/systemd/nvmf-autoconnect.service.in, subprojects/json-c.wrap
Also use the config.json config file when doing an auto connect.
Fixes: #1667
Fixes: #1668
=> fabrics: Honor JSON config file in connect-all command

README.md, meson.build, subprojects/libnvme.wrap, subprojects/uuid.wrap
A bunch of small build related updates for the upcoming 2.2 release
fixes: #1663
=> Build cleanups

Documentation/nvme-sanitize.txt
=> doc: Fix sanitize command examples as character device for issue #1559

nvme.c
This fixes the issue #1746 but add sanitize action 1: exit failure mode also.
=> nvme: Improve sanitize action help

Documentation/nvme-sanitize.txt, nvme.c, util/argconfig.c, util/argconfig.h
=> nvme: sanitize: Allow sanitize action string values

fabrics.c, meson.build, nvme.c
A bunch of fixes/improvements which are from the #1765  work. Let's review them independently from the new feature.
=> Miscellaneous fabric fixes/improvements

util/argconfig.h
=> MAINT: util: Delete duplicated OPT_LONG definition

nvme-print.c, plugins/fdp/fdp.c, subprojects/libnvme.wrap
A set of various fixups for the TP4146 support.
=> TP4146 fixes

Documentation/nvme-compare.txt, Documentation/nvme-read.txt, Documentation/nvme-write.txt, util/suffix.c
=> util: Parse suffix binary value as unsinged long long correctly

fabrics.c
The recent changes to support Persistent Discovery Controller has introduced a few small bugs. Fix these.
=> Persistent discovery controller fixes

nvme.c
nvme-cli v1.16 supported effects-log for fabric devices only, nvme-cli 2.x supported only memory based transports (aka PCI). Obviously, we should support effects-log independent of the transport type.
Do this by first trying to map the PCI registers and read the CAP property if this fails fall back using the get-properties approach.
Fixes: #1783
=> nvme: Support effects-log for fabrics ctrl

plugins/wdc/wdc-nvme.c, plugins/wdc/wdc-nvme.h
Signed-off-by: Jeffrey Lien <jeff.lien@wdc.com>
=> plugins/wdc: Fix data Formatting for Latency Monitor Log Page

.github/cross/clang.txt, .github/cross/ubuntu-armhf.txt, .github/cross/ubuntu-ppc64le.txt, .github/cross/ubuntu-s390x.txt, .github/workflows/appimage.yml, .github/workflows/build.yml, .github/workflows/release.yml
Enable s390x cross builds and also run all tests when building cross.
=> build: Add s390x cross build and enable cross tests

unit/meson.build, unit/test-argconfig-parse.c
Fixes: #1803
Sorry for the issue #1801 as reviewed #1790 but missed it to find.
=> unit: Add test-argconfig-parse

.github/workflows/build.yml
=> build: Add muon build target

plugins/ocp/ocp-clear-fw-update-history.h, plugins/ocp/ocp-nvme.c, plugins/ocp/ocp-nvme.h
As reported by a code linter results in OCP plugin
[dwagner:
- lot's of manual cleanup
- fixed non white space changes reported by checktool
- verified result with 'git diff --word-diff' ]
=> plugins/ocp: Fix whitespace and style issues

nvme.c
FWUG indicates the granularity and alignment requirement of the firmware image being updated by the Firmware Image Download command
FWUG is reported in 4 KiB units
0h indicates that no information on granularity is provided FFh indicates there is no restriction
so when this is 0 value, use 4 KiB split as a default
Reported-by: Minsik Jeon <hmi.jeon@samsung.com>
=> nvme.c: Check Firmware Update Granularity in fwdl

nvme.c
In case nvme_get_property fails, nvme_get_properties frees the allocated memory.
The memory should not be accessed and freed again in show_registers.
=> nvme: Fix invalid memory access in show_registers

.github/workflows/build.yml
Upload all log files in case of failure: https://github.com/linux-nvme/libnvme/pull/582
=> build: Upload all log files on failure

nvme.c
3 Bits - Max value 7
SEL : Bits [10:08] of Get Features Command Dword 10
4 Bits - Max value 15
OWPASS : Bits [07:04] of Sanitize – Command Dword 10
7 Bits - Max value 127
LSP : Bits [14:08] of Get Log Page Command Dword 10 UUID Index : Bits [06:00] of Get Log Page, Get Features, Set Features Command Dword 14
=> nvme: Fix parameter limit range

nvme.c
The required block count and data size is not automatically set for a namespace device in submit_io(). Also it is the user specified block count and not the actual required block count that is passed to the ioctl data structure, often leading to nvme passthrough io errors. For e.g. an nvme read on a 512b block size namespace device with data size set to 4K ends up with the below error:
nvme read /dev/nvme0n1 -s 0 -z 4096
NVMe status: Data SGL Length Invalid: The length of a Data SGL is too short or too long and the controller does not support SGL transfers longer than the amount of data to be transferred(0x400f)
This read is successful only when the appropriate block count is passed from the command line:
nvme read /dev/nvme0n1 -s 0 -z 4096 -c 7
read: Success
So fix this by deriving the …
=> nvme: fix block count and data size logic

nvme-print.c, nvme.c
=> nvme: Check fw-commit command support MUD

.github/workflows/appimage.yml
Also split deploy strep from build step.
=> build: Use sftp transport for AppImage deploy step

fabrics.c
Unlike other nvme transports, nvme/fc connection requires a valid host_traddr in addition to traddr and transport type. Current fc config JSON handling is broken due to the host_traddr not getting updated even if explicitly listed in the JSON file, as shown below:
nvme connect-all -J /usr/local/etc/nvme/config.json Failed to write to /dev/nvme-fabrics: Invalid argument
And the below error is logged in the messages file for the same:
nvme_fabrics: missing parameter 'host_traddr=%s'
Fix this by ensuring the relevant host_traddr string is appropriately passed to the respective nvme controller structure. And while we are at it, ensure the host_iface string is updated too but noting that it is only applicable to tcp alone, and not rdma or fc.
=> fabrics: fix fc config JSON file handling

nvme-builtin.h, nvme.c
This PR includes a patch to fix passthru command function indentation errors also.
=> nvme: Add support for NVMe-MI receive command

Documentation/meson.build, Documentation/nvme-admin-passthru.txt, Documentation/nvme-get-feature.txt, Documentation/nvme-nvme-mi-recv.txt, Documentation/nvme-nvme-mi-send.txt, Documentation/nvme-ocp-clear-fw-activate-history.txt, Documentation/nvme-ocp-clear-pcie-correctable-error-counters.txt, Documentation/nvme-ocp-eol-plp-failure-mode.txt, Documentation/nvme-set-feature.txt
This includes some other documentations maintenance changes.
=> doc: Add eol-plp-failure-mode command documentation

nvme-print-json.c, nvme-print-json.h, nvme-print.c, nvme-print.h, nvme.c, util/argconfig.c
=> Json output error

fabrics.c
Note: Still remaining some errors warnings.
=> fabrics: Fix linux kernel check patch errors and warnings

completions/_nvme, completions/bash-nvme-completion.sh
It was introduced by the change 6aab9e49e but not added for command completion.
Note: The changes included some completion script files indentation fixes.
=> completions: Add json command option

plugins/wdc/wdc-nvme.c
Extend SN530 SSD support for alternate PCI device IDs.
=> plugins/wdc: Extend SN530 support.

Documentation/nvme-ocp-error-recovery-log.txt, plugins/ocp/ocp-nvme.c, plugins/ocp/ocp-nvme.h
plugin/ocp: Added implementation for 0xC1 log page
Reviewed-by: Karthik Balan <karthik.b82@samsung.com>, Arunpandian J <arun.j@samsung.com>
Signed-off-by: Jayakanthan Rajendran [jaya.ganthan@samsung.com](mailto:jaya.ganthan@samsung.com)
=> plugin/ocp: Added implementation for Error Recovery(0xC1) log page

Documentation/nvme-ocp-device-capability-log.txt, completions/_nvme, completions/bash-nvme-completion.sh, plugins/ocp/ocp-nvme.c, plugins/ocp/ocp-nvme.h
Added device capability log page(LID: 0xC4) in OCP plugin and related documentation, bash completion in respective directory.
=> plugins/ocp: Add Device capability(LID: 0xC4) log page

plugins/ocp/ocp-nvme.c, plugins/scaleflux/sfx-nvme.c, plugins/scaleflux/sfx-nvme.h, plugins/wdc/wdc-nvme.c, util/types.c, util/types.h
Refactoring PR https://github.com/linux-nvme/nvme-cli/pull/1948  
@whou-sfx please check if the result is okay.
=> scaleflux: support expand-cap and dump-evtlog command

nvme-print-binary.c, nvme-print-json.c, nvme-print-stdout.c, nvme-print.c, nvme-print.h
Reviewed the final result of the refactoring with fresh eyes and spotted a few things to cleanup or fix.
=> Fixes for the recent print refactoring

plugins/solidigm/meson.build, plugins/solidigm/solidigm-market-log.c, plugins/solidigm/solidigm-market-log.h, plugins/solidigm/solidigm-nvme.c, plugins/solidigm/solidigm-nvme.h
Added ability to print Marketing name for Solidigm drives in Solidigm plugin
=> plugins/solidigm: Added Marketing Name Log support for Solidigm.

nvme-print-json.c, nvme-print-stdout.c, nvme-print.c, subprojects/libnvme.wrap
- A few small fixes upfront.
- Add the iopolicy scheduler to the topology output 
Fixes: https://github.com/linux-nvme/nvme-cli/issues/1963
=> Add I/O scheduler configuration to the topology command

plugins/solidigm/solidigm-telemetry/nlog.c, scripts/build.sh
Do not continue to build and hide any errors.
=> build: abort CI builds on first error

nvme-print-json.c, nvme-print-stdout.c, subprojects/libnvme.wrap
Depends on the changes in commit `6de7efe` for libnvme
=> nvme: Add support for the OAQD ID controller field

nvme.c
"data" field is being used without memory allocation
this commit add fix for that
=> fix for create-ns command

Documentation/nvme-wdc-set-latency-monitor-feature.txt, plugins/wdc/wdc-nvme.c, plugins/wdc/wdc-nvme.h
This commit enables several commands to work with this device properly and adds a new plugin command set-latency-monitor-feature.
Reviewed-by: Jeffrey Lien <jeff.lien@wdc.com>
=> plugins/wdc: enhanced SN861 device support

plugins/solidigm/solidigm-internal-logs.c, plugins/solidigm/solidigm-nvme.h, plugins/solidigm/solidigm-telemetry.c, plugins/solidigm/solidigm-util.h
Faster telemetry retrieval using large buffers.
=> plugins/solidigm: internal-logs Telemetry auto detect last data area.

plugins/memblaze/memblaze-nvme.c, plugins/memblaze/memblaze-nvme.h
1. add smart-log-add, latency-feature functions
2. convert code style to align with linux kernel code style
3. using __packed instead  of pragma style
=> plugins/memblaze: Add smart-log-add and latency-feature functions

nvme.c
Cherry picked the PR https://github.com/linux-nvme/nvme-cli/pull/2088 patche below to split since not related to the json output changes.
1. e98bc408 nvme: Change phy-rx-eom-log command to use NVME_ARGS instead
=> nvme: Change phy-rx-eom-log command to use NVME_ARGS instead

README.md
=> README: Add make static explanation

.mailmap, nvme-print-json.c, plugins/ocp/ocp-nvme.c
Fixup a few things after the recent update of nvme-print-json.
=> Build fix and a few cleanups for nvme-cli-json

Documentation/nvme-connect.1
(`--application` -> `--context`)
=> doc: Fix nvme-connect manpage --application option string

Documentation/nvme-ocp-telemetry-string-log-page.txt, completions/_nvme, completions/bash-nvme-completion.sh, plugins/ocp/ocp-nvme.c, plugins/ocp/ocp-nvme.h
Added OCP 2.5 Telemetry string log page and Telemetry log page support.
=> plugins/ocp: Add OCP Telemetry String log page, Telemetry log page

.github/workflows/checkpatch.yml, .github/workflows/coverage.yml
- ignore some paths for code coverage test
- add checkpatch to report style issues automatically
=> update workflow jobs

nvme-print-json.c
While the spec may allow for arbitrary use of vendor-specific data, some implementations are simply strings.  JSON will encode the string, allowing for safe use of control characters.
The only requirement is that the there be a null-byte in the vendor-specific field terminating the string.  Data beyond the null-byte will be ignored.
[dwagner: use d_json instead obj_add_str]
Supersedes: #2143
=> nvme-print-json: include vs for identify namespace

Documentation/nvme-config.txt, Documentation/nvme-connect-all.txt, Documentation/nvme-connect.txt, Documentation/nvme-discover.txt
=> doc: Fix config-schema.json's URL

nvme-print-json.c, nvme-print-stdout.c
This is for the issue mentioned by https://github.com/linux-nvme/nvme-cli/pull/1962#discussion_r1213398564 before.
=> nvme-print: Fix PEL SEB print functions

plugins/netapp/netapp-nvme.c
Add nspath tlv handling logic to the NetApp plugin.
=> nvme-netapp: add nspath tlv handling

plugins/memblaze/memblaze-nvme.c
1. Set leading indent to tab
2. Set proper alignment as code len limitation
=> plugins/memblaze: code-format on leading indent and align

plugins/memblaze/memblaze-nvme.c
applying __packed on more structs
=> plugins/memblaze: code refactor on applying __packed on more structs

plugins/memblaze/memblaze-nvme.c, plugins/memblaze/memblaze-nvme.h
=> plugins/memblaze: add performance stats

nvme-print-stdout.c
~~Replase~~ **Replace** hard coded shift and mask values.
=> nvme-print-stdout: use NVME_MAJOR and NVME_MINOR definitions

nvme-print-stdout.c
~~Replase~~ **Replace** hard corded register value, shift and mask values.
=> nvme-print-stdout: use controller configuration definitions

Documentation/nvme-ocp-get-dssd-async-event-config.txt, Documentation/nvme-ocp-set-dssd-async-event-config.txt, completions/_nvme, completions/bash-nvme-completion.sh, plugins/ocp/ocp-nvme.c, plugins/ocp/ocp-nvme.h
Adds two new OCP plugin functions for getting and setting this feature, based on the 2.5 OCP spec.
=> ocp: support OCP DSSD Async Event Config feature

plugins/meson.build, plugins/ssstc/ssstc-nvme.c, plugins/ssstc/ssstc-nvme.h
add a new plugin for SSSTC driver
Signed-off-by: kobyou <kobyou@126.com>
=> add a new plugin for SSSTC driver

Documentation/nvme-connect.txt
Describe the kernel retry a connection behavior.
=> doc: add nvme connet ctrl-loss-tmo description

plugins/solidigm/solidigm-internal-logs.c, plugins/solidigm/solidigm-nvme.h
Added some Identify pages, and some standard log, and some VU logs. Created abstract data type with common fields for internal logs. Better string buffer overflow avoidance.
=> plugins/solidigm: Added log pages to vs-internal-logs

plugins/solidigm/solidigm-id-ctrl.c, plugins/solidigm/solidigm-nvme.h
Added 13 extra VU fields to Solidigm id-ctrl
including a buffer for correct offset
=> plugins/solidigm: Added extra VU fields to id-ctrl

Documentation/nvme-ocp-tcg-configuration-log.txt, completions/_nvme, completions/bash-nvme-completion.sh, plugins/ocp/ocp-nvme.c, plugins/ocp/ocp-nvme.h
Reviewed-by: Karthik Balan <karthik.b82@samsung.com>, Arunpandian J <arun.j@samsung.com>
=> plugins/ocp: Added ocp TCG Configuration Log Page

nvme-print-json.c, nvme-print-stdout.c
Print the newly added fields in TP4141a. Also, fixed the stcrs bit mask value.
=> nvme-print: print the new fields added in TP4141a

nvme.c
As per TP4141a:
"If the Qualified Protection Information Format Support(QPIFS) bit is set to 1 and the Protection Information Format(PIF) field is set to 11b (i.e., Qualified Type), then the pif is as defined in the Qualified Protection Information Format (QPIF) field."
So, choose PIF from QPIF if QPIFS supports and PIF is QTYPE.
=> nvme: choose PIF from QPIF if QPIFS supports and PIF is QTYPE

nvme.c
Add a helper function to get pif and sts value from elbaf filed.
=> nvme: add helper function to get pif and sts value

Documentation/nvme-smart-log.txt, completions/_nvme, completions/bash-nvme-completion.sh, nvme-print-binary.c, nvme-print-stdout.c, nvme-print.c, nvme-print.h, nvme.c, nvme.h, util/types.h
Show temperatures in degrees fahrenheit by the option.
=> nvme: Add smart-log command fahrenheit option

nvme-print-stdout.c
DRY the subsys config output. Refactor into a helper.
=> nvme-print-stdout: refactor subsys config

plugins/ocp/ocp-nvme.h
Update ocp plugin version to 2.9.0
=> ocp: Update Plugin Version

Documentation/nvme-micron-ocp-telemetry-log-parse.txt
The title needs a man page section info.
=> doc: fix micron ocp telemetry log parse title

.github/workflows/docs.yaml, scripts/build.sh
Build the documentation in the CI build to catch formatting issues in the submissions.
Fixes: #https://github.com/linux-nvme/nvme-cli/issues/2408
=> build: add documentation CI build

ccan/ccan/strset/strset.c
Add to set freed entry pointer to NULL then check it if NULL.
=> ccan: Add freed pointer checking to delete strset member

plugins/wdc/wdc-nvme.c, plugins/wdc/wdc-nvme.h
Add panic count and prev panic id to Error Recovery log page (0xC1)
Add debug telemetry log size to Latency Monitor log page (0xc3)
=> wdc: OCP 2.5 Log Page Updates

nvme-print-json.c, nvme-print-stdout.c, nvme.c
Print the new fields added in TP4165.
=> nvme-print: print the new fields added in TP4165

completions/_nvme
add the zsh completion of the dapustor plugin
=> completions: add the zsh completion of the dapustor plugin

nvme-print-json.c, nvme-print-stdout.c
Print the new fields added in Identify Controller Data Structure.
Also, print the field added in Temperature Threshold feature.
=> nvme-print: print the new fields added in TP4142

nvme-print-stdout.c, nvme-print.c
Add arbitration, power management, LBA range type and temperature threshold features definitions at first so still remained features.
=> nvme-print: add feature fields struct definition to print feild values

nvme-print-json.c, nvme-print-stdout.c, subprojects/libnvme.wrap
Added new fields from I/O Command Set Specific Identify Namespace Data Structure CNS5 as per NVM Command Set Specification(Rev 1.1).
=> nvme-print: added new fields for nvm_id_ns

util/types.c, util/types.h
Use the function to calculate with the uint128_t value.
=> util: extern uint128_t_to_double() function

util/logging.h
=> logging: add print_info function

plugins/ocp/ocp-nvme.c, plugins/ocp/ocp-nvme.h
The commands returns set of enable IEEE1667 silo.
=> ocp: add get-enable-ieee1667-silo command

plugins/ocp/ocp-nvme.c
Add panic count and previous panic IDs.
=> ocp: add error recovery log page version 3

plugins/ocp/ocp-smart-extended-log.c
Add NVMe command set errata version and lowest permitted firmware revision.
=> ocp: add SMART / health information extended log page version 4

nvme-print-json.c, nvme-print-stdout.c, nvme-print.h
Print the newly added NSSES field of CAP register.
=> nvme-print: print NSSES field of CAP register

plugins/ocp/ocp-nvme.h
Add missing version update after adding changes for ocp spec 2.5
=> ocp-nvme: ocp plugin version update #2527 #2529

Documentation/nvme-sanitize.txt, completions/_nvme, completions/bash-nvme-completion.sh
Add Enter Media Verification State (EVMS) option of Sanitize command.
=> doc: Add sanitize command emvs option

plugins/netapp/netapp-nvme.c
=> plugins/netapp: add include of libgen.h for basename(3) prototype

plugins/ocp/ocp-smart-extended-log.c
The index is required by the OCP specification.
=> ocp: set UUID index to get extended smart log

nvme.c
Added the Namespace Zeroes (NSZ) support to Write Zeroes command. Also, fixed the dtype limitation (DTYPE - 22:20 bits).
TP4160 - WZSL Limit Modification
=> nvme: add Namespace Zeroes support to Write Zeroes command

nvme-print-stdout.c
Additional HMLMS bit in OACS field (stdout)
=> print: OACS Host Managed Live Migration Support (HMLMS)

plugins/meson.build
Some plugins do not use json so no need to check the build dependency.
=> plugins: build plugins not depended on json without json

subprojects/json-c.wrap
=> build: bump wrap

nvme-print.c
Also added some missed admin commands strings.
=> nvme-print: add NVMe 2.1 admin commands strings

nvme-builtin.h, nvme-print-binary.c, nvme-print-json.c, nvme-print-stdout.c, nvme-print.c, nvme-print.h, nvme-wrap.c, nvme-wrap.h, nvme.c, subprojects/libnvme.wrap
Since added the NVMe 2.1 log page.
=> nvme: add mgmt-addr-list-log command

nvme-builtin.h, nvme-print-binary.c, nvme-print-json.c, nvme-print-stdout.c, nvme-print.c, nvme-print.h, nvme-wrap.c, nvme-wrap.h, nvme.c
Since added the NVMe 2.1 log page.
=> nvme: add rotational-media-info-log command

tests/nvme_compare_test.py, tests/nvme_create_max_ns_test.py, tests/nvme_smart_log_test.py, tests/nvme_test.py, tests/nvme_test_io.py, tests/nvme_verify_test.py
The discussion and testing in relation to https://github.com/linux-nvme/nvme-cli/issues/2668 discovered some bugs in the test cases that are addressed with this PR.
=> Improve tests

plugins/sed/sedopal_cmd.c, plugins/virtium/virtium-nvme.c, subprojects/libnvme.wrap, util/logging.c, util/types.c
After the container updates, the cross build fails. Fix it.
=> Fix build after cross build container update

plugins/netapp/netapp-nvme.c
Yet another correction to the basestr headers.
=> netapp-ontapdev: correct the basestr header

nvme-print-json.c, nvme-print-stdout.c, nvme.c, subprojects/libnvme.wrap
Add human readable output for Identify I/O Command Set Data Structure (CNS 1Ch).
=> nvme-print: add human readable output for IOCS Data Structure

Documentation/cmd-plugins.txt
Added most unique solidigm plugin commands to main manual page.
=> Documentation: Added solidigm plugin commands to main manual page.

plugins/meson.build, plugins/solidigm/meson.build
Add as same with other solidigm sources added by solidigm/meson.build.
=> plugins: move meson.build solidigm-nvme.c into solidigm/meson.build

nvme-print-json.c
This reverts commit 929f4619a9aa9c900247384480fe60ff96931b07.
The output format chagned and breaks existing automation.
Fixes: #2749
=> Revert "nvme-print-json: display only verbose output"

plugins/micron/micron-nvme.c, plugins/micron/micron-nvme.h
Updated the Micron plugin to support the latest products and features. Changes follow the Kernel coding style guidelines for consistency.
=> Update: micron plugin with latest product support

Documentation/cmd-plugins.txt, Documentation/meson.build, Documentation/nvme-mangoboost-id-ctrl.txt
man pages for MangoBoost plugin commands.
=> Documentation: Add man page for mangoboost command

plugins/micron/micron-nvme.c
Added missing micron product ID's into plugin
=> plugins/micron: adding missing product support

Documentation/nvme-list.txt, nvme-print-stdout.c
The sizes are printed with SI prefixes.
=> doc: add nvme list namespace usage sizes description

nvme-print-stdout.c, subprojects/libnvme.wrap
=> nvme-print-stdout: add get-log command verbose outputs

.github/workflows/build.yml, scripts/build.sh
Fixes: #https://github.com/linux-nvme/libnvme/issues/571
=> Enable valgrind for default builds
