wrapper.c

The wrapper needs to call the library version of the function.
While at it, introduce preprocessor helpers to reduce the amount
boilerplate code.
Fixes: 7ccb7d29afa0 ("wrapper: Add weak nvme_init_copy_range_f1 symbol")
Fixes: #1628

wrapper: Call library version of nvme_init_copy_range_f1

---

nvme.c
util/argconfig.c
util/argconfig.h

In copy command, nlbs is declared as __u16. While parsing command line argument,
it is typecast to integer pointer. So nlbs[1], nlbs[3], nlbs[5], ... are stored
as zero after getting parsed. Therefore it is passing wrong value to controller.
Hence, adding a helper function to parse the 16-bit comma separated list
Signed-off-by: Francis Pravin Antony Michael Raj <francis.michael@solidigm.com>
Signed-off-by: Jonathan Derrick <jonathan.derrick@solidigm.com>

nvme: Add helper function to parse 16-bit comma separated list

---

util/json.c
util/json.h

Notable json-c 0.13 is lacking support for serializing uint64_t
types. At this point of writing the 0.13 version is widely
deployed. Let's add our own version of the serialization function as
fallback.
Fixes #1632

json: Support uint64 types serialization for older json-c versions

---

nvme-wrap.c
nvme-wrap.h
nvme.c
subprojects/libnvme.wrap

Now that we have the MI transport & wrapper infrastructure merged, and the admin commands implemented in libnvme-mi, we can add more functionality to the wrapper code, and start using the `nvme_cli_` functions in nvme-cli.
As always, comments, queries, suggestions etc are most welcome.

MI: Add (and use) `nvme_cli_*` wrappers for more admin functions

---

plugins/wdc/wdc-nvme.c
plugins/wdc/wdc-nvme.h

Add support for Version 1 Error Recovery log page
Fix fw-activate-history timestamp json data
Update OCP log page capabiliites for SN550, SN650,
and SN655

wdc:  OCP Log page updates and fixes

---

nvme-rpmb.c
nvme.c
plugins/dera/dera-nvme.c
plugins/innogrit/innogrit-nvme.c
plugins/intel/intel-nvme.c
plugins/memblaze/memblaze-nvme.c
plugins/micron/micron-nvme.c
plugins/ocp/ocp-nvme.c
plugins/scaleflux/sfx-nvme.c
plugins/seagate/seagate-nvme.c
plugins/shannon/shannon-nvme.c
plugins/solidigm/solidigm-garbage-collection.c
plugins/solidigm/solidigm-latency-tracking.c
plugins/solidigm/solidigm-smart.c
plugins/toshiba/toshiba-nvme.c
plugins/transcend/transcend-nvme.c
plugins/virtium/virtium-nvme.c
plugins/wdc/wdc-nvme.c
plugins/ymtc/ymtc-nvme.c
plugins/zns/zns.c

Currently, we see a warning with specific compilers:
```
../nvme/nvme.c: In function 'ns_rescan':
../nvme/nvme.c:4389:19: warning: 'dev' may be used uninitialized in this function [-Wmaybe-uninitialized]
```
This is due to a theoretical failure path in `parse_and_open()`, where
`argconfig_parse()` returns a positive value - this would require the
global `errno` to be negative.
Even though the unintialised use of dev is only possible with negative
error (which shouldn't happen), we should still consider any non-zero
return value of `parse_and_open` a failure. This change fixes the
instances of:
err = parse_and_open(...);
if (err < 0)
changing to:
err = parse_and_open(...);
if (err)
... and also applies this to the single use of `open_exclusive()`.
The positive return values from …

tree: fail on non-negative return values from parse_and_open

---

nvme-print.c

The sanitize->sstat needs to be mask. We do this for the JSON output
but not for the normal shell output.
Fixes: https://github.com/linux-nvme/nvme-cli/issues/752

nvme: Masks SSTAT in sanize-log output

---

Documentation/nvme-sanitize.txt

asciidoc creates list with either a '*' or '-'. Without it this is
rendered as one paragraph which is hard to read.
While at it, also use hex values to match with example.

docs: Update formatting for sanact list

---

README.md

Document how to contribute to the project. Highlight the fact, that
it expected that the PRs are also following the Linux community
contributions guidelines (clean series).

doc: Add 'how to contribute' section

---

nvme-print.c
nvme-print.h
plugins/ocp/ocp-nvme.c
plugins/virtium/virtium-nvme.c
plugins/wdc/wdc-nvme.c
util/json.c
util/json.h
util/meson.build
util/types.c
util/types.h

This is a complete reworked version of #1655 
- reorganized/splitted the PR
- moved common type bits to new location util/types.h
- dropped the print_uint128 function. Just use uint128_t_to_string() directly
TODOs(?):
- The le128_to_cpu() function should probably be a macro like the other le*_to_cpu() helpers from ccan
- Naming scheme seems a bit off and a bit too verbose, e.g. `_to_string`.

Add uint128 type

---

Documentation/nvme-list-subsys.txt

The examples show the output from nvme-cli 1.x. The address field shows the attributes separated by spaces. The corresponding code in libnvme doesn't do this. Instead the exact output from sysfs, e.g.
traddr=192.168.201.101,trsvcid=4420
Update the example in the nvme list-subsys documentation.
Signed-off-by: Daniel Wagner <dwagnwer@suse.de>

doc: Update examples in nvme-list-subsys.txt

---

nvme-print.c

For pcie devices there might be no hostid available, in case the /etc/nvme/hostid file doesn't exist.

nvme-print: Handle NULL hostid in JSON output

---

plugins/wdc/wdc-nvme.c

clang reports
../plugins/wdc/wdc-nvme.c:9000:36: warning: implicit conversion from enumeration type 'NVME_FEATURE_IDENTIFIERS' (aka 'enum _NVME_FEATURE_IDENTIFIERS') to different enumeration type 'enum nvme_features_id' [-Wenum-conversion]
deFeatureIdList[listIdx].featureId,
~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
Add type case to avoid the warning. Ideally, the plugin would not introduce their own enum value.
Fixes: https://github.com/linux-nvme/nvme-cli/issues/1665

plugins/wdc: Add type case for feature id

---

nvmf-autoconnect/udev-rules/70-nvmf-autoconnect.rules.in

The HOST_IFACE only applies to TCP connections. When provided, it forces TCP connections on a specific interface instead of letting the routing table decide. Some users may prefer to force connections on specific interfaces instead of configuring the routing table. This change makes sure that the HOST_IFACE used to set up the persistent connection to the discovery controller also gets applied to the I/O controller connections.
Signed-off-by: Martin Belanger <martin.belanger@dell.com>

udev: Add HOST_IFACE to udev rule

---

nvme-print.c
tests/meson.build
tests/test-uint128.c
util/json.c
util/json.h
util/types.c
util/types.h

Currently, nvme-cli will not compile on 32-bit platforms, as uint128_t is not available.
This change, based on suggestions from Daniel Wagner <dwagner@suse.de>, adds our own nvme_uint128_t type, which needs a custom to_string() function.
In order to make the latter straightforward, we use four 32-bit words for the internal representation of the 128-bit type. We then use 64-bit arithmetic to avoid having to handle the carry-bit explicitly.
Also, add a small test case for the printing.
Signed-off-by: Jeremy Kerr <jk@codeconstruct.com.au>

utils: Fix uint128_t usage

---

.github/cross/ubuntu-armhf.txt
.github/cross/ubuntu-ppc64le.txt
.github/workflows/meson.yml
nvme.c
plugins/scaleflux/sfx-nvme.c
plugins/seagate/seagate-nvme.c

This change adds a couple of cross-compilation targets for nvme-cli: armhf and powerpc64.
In order to do this though, we have to fix a couple of warnings for printf-specifiers and casts on those arches.

Add warning fixes and enable cross compilation targets in github workflows

---

tests/meson.build
util/types.c

We currently have a bug when converting from le128, as we'll overwrite words that we later need to read.
Also, use an if rather than #ifdef, so the BE case can be compiled. Turns out we need the ccan headers for this.
Signed-off-by: Jeremy Kerr <jk@codeconstruct.com.au>

util: Fix le128_to_cpu on big-endian

---

nvme-wrap.c
nvme-wrap.h
nvme.c
subprojects/libnvme.wrap

This change adds nvme_dev wrappers for the firmware download and firmware commit commands, allowing access over a MI channel.
We need a bump to libnvme for the underlying MI firmware calls.
Signed-off-by: Jeremy Kerr <jk@codeconstruct.com.au>

nvme: Add wrappers for firmware commands

---

nvme.c

if cfg.metadata is NULL, passing it to strlen() will trigger a SIGSEGV.

nvme: check if cfg.metadata is NULL before passing it to strlen()

---

util/types.c

We need to swap the words order in little-endian machine too. For example:
```
uint128:  0x4000000030000000200000001
0  1  2  3 |  4  5  6  7 | 8  9  a  b  | c  d  e  f
01 00 00 00 | 02 00 00 00 | 03 00 00 00 | 04 00 00 00
w0(MSB)   |     w1      |    w2       |  w3(LSB)
04 00 00 00 | 03 00 00 00 | 02 00 00 00 | 01 00 00 00
```
Fix: https://github.com/linux-nvme/nvme-cli/issues/1702
Signed-off-by: Jinliang Wang <jinliangw@google.com>

util: Fix le128_to_cpu on little-endian

---

tests/meson.build

Meson reports future deprecation of meson.build_root().  The recommended replacement is to use meson.current_build_dir().
Fixes: #1701

build: Use meson.current_build_dir() for tests

---

Makefile

This PR adds ``make uninstall``.
Example output is provided below, showing how ``make uninstall`` behaves after ``make install``.
Equivalent PR provided for **libnvme**: https://github.com/linux-nvme/libnvme/pull/501
**Install**
```
safl@debtop:~/git/nvme-cli$ make && sudo make install
meson .build
The Meson build system
Version: 0.60.0
Source dir: /home/safl/git/nvme-cli
Build dir: /home/safl/git/nvme-cli/.build
Build type: native build
Project name: nvme-cli
Project version: 2.1.2
C compiler for the host machine: cc (gcc 10.2.1 "cc (Debian 10.2.1-6) 10.2.1 20210110")
C linker for the host machine: cc ld.bfd 2.35.2
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Run-time dependency libnvme found: YES 1.1
Run-time dependency …
```

Makefile: add 'make uninstall'

---

nvme-print.c
nvme-print.h
nvme.c
plugins/wdc/wdc-nvme.c

WIP: needs upstream libnvme changes first
This series adds support for the status type encoding proposed in https://github.com/linux-nvme/libnvme/pull/502
We first add decoding using the nvme_status_get_type() helper, and then add support for MI-specific status values through nvme_mi_status_to_string().

Add support for libvnme status types

---

plugins/solidigm/solidigm-telemetry/data-area.c
util/json.c
util/json.h

We need the definition of json_object_get_uint64 in case json-c doesn't provide it.

util/json.h: Add json_object_get_uint64 fallback implementation

---

plugins/solidigm/solidigm-telemetry.c

Seeing the below warning while compiling nvme-cli:
ninja: Entering directory `.build'
[27/51] Compiling C object nvme.p/plugins_solidigm_solidigm-telemetry.c.o ../plugins/solidigm/solidigm-telemetry.c: In function ‘solidigm_get_telemetry_log’: ../plugins/solidigm/solidigm-telemetry.c:126:22: warning: ‘length’ may be used uninitialized in this function [-Wmaybe-uninitialized]
tl.configuration = json_tokener_parse_ex(jstok, conf_str, length);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[51/51] Linking target nvme
Fix this by initializing the 'length' variable to zero.

solidgm: fix initialization warning

---

fabrics.c
libnvme-wrap.c

Enable 'persistent' flag during nvme connect-all if set in the config JSON file.

fabrics: fix 'persistent' handling during connect-all with JSON file

---

meson.build

With the drop of libuuid we need also the corresponding libnvme library which provides its own uuid types.
Fixes: #1717

build: Update libnvme version dependency to 1.2

---

completions/_nvme

The zsh completion system requires compdef to be set in the first line of the completion definition. The SPDX identifier introduced breaks this requirement, so let's just move it a line down.

zsh: move SPDX identifier

---

nvme-wrap.c
nvme-wrap.h
nvme.c

Suppport ns-descs, primary-ctrl-caps and list-secondary subcommands though nvme-mi.
Signed-off-by: Jinliang Wang <jinliangw@google.com>

nvme-mi: support ns-descs, primary-ctrl-caps, list-secondary

---

nvme-wrap.c
nvme-wrap.h
nvme.c
subprojects/libnvme.wrap

Bump libnvme version and support admin_passthru over nvme-mi.
Test Identify Controller command on:
- In-band
```
./nvme admin-passthru --opcode 0x06 --cdw10=0x01 --data-len=4096 --read /dev/nvme0
Admin Command Identify is Success and result: 0x00000000
0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
0000: 4d 14 4d 14 53 33 35 42 4e 58 30 4b 38 31 33 38 "M.M.S35BNX0K8138"
0010: 38 30 20 20 20 20 20 20 53 41 4d 53 55 4e 47 20 "80......SAMSUNG."
0020: 4d 5a 56 4b 57 35 31 32 48 4d 4a 50 2d 30 30 30 "MZVKW512HMJP-000"
0030: 4c 37 20 20 20 20 20 20 20 20 20 20 20 20 20 20 "L7.............."
0040: 36 4c 36 51 43 58 41 37 02 38 25 00 00 00 02 00 "6L6QCXA7.8%....."
0050: 00 02 01 00 a0 86 01 00 40 4b 4c 00 00 00 00 00 "........@KL....."
...
```
- nvme-mi:
```
./nvme admin-passthru --opcode 0x06 …
```

Support admin_passthru over nvme-mi

---

fabrics.c
linux/nvme.h

These two patches only introduce a bare minimum to support TP8013 and 80134. There many fixes and features needed to get this really working. As there is little interest in adding this to the 1.x branch, let's drop those changes again.

Drop incomplete support for TP8013 and 8014 

---

meson.build

The Meson buildspec uses features introduced in Meson 0.50.0, but only specifies 0.48.0. Eliminates a Meson warning.
Signed-off-by: nick black <dankamongmen@gmail.com>

build: require meson 0.50.0+

---

nvme.c

Changing this to `true` resulted in my Western Digital 970 EVO Pro NVMe SSDs returning all zeros for smartlog information. Reverts change made in cc73f65.
Resolves #1729.
Signed-off-by: nick black <dankamongmen@gmail.com>

nvme: call nvme_get_smart_log() with false

---

plugins/memblaze/memblaze-nvme.c
plugins/memblaze/memblaze-nvme.h
plugins/memblaze/memblaze-utils.h

1. use "u16 *" instead of "u8 *" to fix the wear-leveling values as defined.
2. remove some useless code.
3. replace the string code style.

plugins/memblaze: fix "smart-log-add" display "wear-leveling" issue.

---

nvme.c

As part of implementing firmware-download over MI transports, this series adds some reliability improvements to the fw-download subcommand:
* reporting progress on individual data transfers, with a new `--progress` argument
* retrying individual transfers where the controller does not indicate a Do Not Resend error
* allowing the user to ignore Overlapping Range errors, if recovering from a previous transfer (`--ignore-ovr`)
As always, I'm happy to answer any queries or handle any comments / feedback.

fw-download retry, progress and error-handling improvements

---

nvme.c

1. 4fd2e555 (HEAD -> master, origin/help-message) nvme: Combine duplicated help message string variables
2. 7dc44232 nvme: Correct show-topology command help spelling error

Help message changes

---

nvme-print.c

This fix is for the issue #1742 opened.

nvme-print: Fix to add uint and uint64 json object values to output

---

nvme-wrap.c
nvme-wrap.h
nvme.c

We cannot use nvme_cli_security_receive wrapper method as other commands because the API between inband and nvme-mi are not compatible.
Signed-off-by: Jinliang Wang <jinliangw@google.com>
Tested:
```
NVME Security Receive Command Success
0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
0000: 00 00 00 b4 00 00 00 01 00 00 00 00 00 00 00 00 "................"
0010: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 "................"
0020: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 "................"
0030: 00 01 10 0c 51 00 00 00 00 00 00 00 00 00 00 00 "....Q..........."
0040: 00 02 10 0c 09 00 00 00 00 00 00 00 00 00 00 00 "................"
0050: 00 03 10 1c 01 00 00 00 00 00 00 00 00 00 02 00 "................"
0060: 7f ff ff ff ff ff ff ff 00 00 00 00 00 00 00 00 "................" …
```

nvme: support security-recv and security-send over nvme-mi

---

completions/bash-nvme-completion.sh

* To fix completion issue by moving global vairables into function _nvme_subcmds. It is not only suite for bash completion system but also support manually source bash script.
* Fix pluginx_sfx_opts spell error to plugin_sfx_opts.
* Correct variable NO_OPTS used in bash assginment.
Signed-off-by: Qiang Wei <qiang.wei@suse.com>

Bash completion: move global declare into function

---

Documentation/nvme-create-ns.txt
nvme.c
tests/meson.build
tests/test-suffix-si-parse.c
util/suffix.c
util/suffix.h

This is proposed by the issue #1747.

nvme: Allow standard SI units for ns-create nsze and ncap input

---

nvme-print.c

The resv-report command is missing to print the zeros in hostid for the terminal output. Update the printf format specifier accordingly.
The JSON output does this correctly.
Fixes: #1757

nvme: Output zero padded hostid in resv-report command

---

nvme-print.c
unit/meson.build
unit/test-uint128-si.c
util/suffix.c
util/suffix.h
util/types.c
util/types.h

This resolves for the issue #1745.

nvme-print: Display smart log data units read and written SI value

---

Documentation/nvme-device-self-test.txt
nvme.c

Add a wait command line option to device-self-test which makes nvme-cli staying in forground and reports progress. This make it possible to wait for the end of the test.
Signed-off-by: Keith Busch <kbusch@kernel.org>
[dwagner: make termination condition handling the end of self test]
Fixes: #https://github.com/linux-nvme/nvme-cli/issues/1759

nvme: Add wait for device self test

---

.github/workflows/appimage.yml

We have to upload the AppImage as release to be able set a link.

build: Upload latest AppImage

---

plugin.c
util/argconfig.c
util/argconfig.h

This is to allow to select stdout or stderr streams for print.

util: Add file stream parameter to print word wrapped

---

fabrics.c
subprojects/libnvme.wrap

This implemention changes the default behavior considerable:
- Try to use unique discovery controllers per default.
- Avoid connecting to already connected or 'duplicates' controllers during discovery
- Make unique discovery controllers persistent per default
The first two are backwards compatible, that means if the user isn't really using '--persistent' as command line option, the outcome should be the same. The last change is a bit daunting IMO. Is this really what the TP8013 mandates?
Fixes #1670

Make unique discovery controllers persistent as default

---

fabrics.c
meson.build
meson_options.txt
subprojects/libnvme.wrap

The persistent discovery controller is a behavior change which might break existing installation. Instead enabling it per default, introduce a compile time and a global configuration option to define the default settings.

fabrics: Make PDC behavior configurable

---

fabrics.c
nvme.h

`nvme_strip_spaces()` has an off-by-one error and starts stripping spaces at the byte AFTER the end of the buffer. Use `space_strip_len()` instead, which doesn't have this bug and is already used in `print_discovery_log()`.

json_discovery_log: avoid buffer overrun

---

release.sh

The release script should also update the dependency on libnvme. Use the libnvme.wrap information as base.
Fixes: #1720

build: Update libnvme version dependency on release

---

Documentation/nvme-device-self-test.txt
nvme.c
subprojects/libnvme.wrap

Still thinking and trying to add changes below also etc.
1. Add device self-test SIGINT signal handling for wait option to abort
2. Use abort self-test code definition value instead hard-code value
3. Update device-self-test command documentation

Device self-test changes

---

.github/azure-pipelines.yml

Let's give it another try to use the addition tests. The Azure Pipeline Agent extension seems to work now.

build: Enable Azure Pipeline again

---

meson.build

The sysconfdir is an explicit path '/etc' and the muon implementation of join_paths is dropping the prefixdir, thus we need to string concanate the syscondfir path instead of using the join_paths function.

build: Use prefixdir directly on sysconfdir

---

nvme.c
unit/meson.build
unit/test-suffix-binary-parse.c
unit/test-suffix-si-parse.c
util/argconfig.c
util/suffix.c
util/suffix.h

suffix_si_parse() has an very awkward interface with using errno and suffixed as return value. Let's just use the return code as status value and use an argument for returning the value and avoid setting the errno.
Furthermoe, this function should not know anything about LBAs, it just supposed to parse a string with a suffix. In order to support the previous use case we also return the endprt which allows to implement the nsze-si parse use case and the caller side (see documentation on create-ns).
Next problem is that suffix_is_parse uses double for calculation which tend to get inaccurate, e.g. 6.14T results in 61399999997. Instead let's do do all in pure integer arithmetic.
Also handle the decimal point according the locale settings.
Fixes: …

util: Reimplement suffix_si_parse

---

unit/test-suffix-binary-parse.c
util/argconfig.c
util/suffix.c

suffix_binary_parse() is used to parse most of the numeric command lines. As it turns out the main use case to provide just numbers without any suffix. Fix the regression recently introduced when we made the parser also to check two characters suffixes.
Fixes: 1e5abd545622 ("util: Update suffix_binary_parse API")
Reported-by: Steven Seungcheol Lee <sc108.lee@samsung.com>
Fixes: #1801

util: Numbers without any suffix are also valid

---

.github/AppImageBuilder.yml
.github/workflows/appimage.yml

Ubuntu uses a multilib setup hence the libraries are not found in /lib64.
Fixes: #1804

build: Update library paths for AppImage

---

Documentation/nvme-connect-all.txt
Documentation/nvme-discover.txt

For `nvme-discover` the options `--hdr-digest` and `--data-digest` were documented with an underscore instead of a hyphen (i.e. `--hdr_digest` and `--data_digest`).
For `nvme-connect-all` the option `--device` was missing.
I also made a few other changes for consistency between `nvme-discover` and `nvme-connect-all`.
Signed-off-by: Martin Belanger <martin.belanger@dell.com>

docs: Fixed typos and add missing option

---

fabrics.c
meson.build
meson_options.txt
nvme-print-json.c
nvme-print-json.h
nvme-print.c
nvme-print.h
plugins/meson.build
plugins/solidigm/solidigm-telemetry.c
plugins/solidigm/solidigm-telemetry/cod.c
plugins/solidigm/solidigm-telemetry/config.c
plugins/solidigm/solidigm-telemetry/config.h
plugins/solidigm/solidigm-telemetry/data-area.c
plugins/solidigm/solidigm-telemetry/header.c
plugins/solidigm/solidigm-telemetry/telemetry-log.h
util/json.h
util/meson.build

This is an attempt to make json-c optional by dropping functionality. I think even if we don't go with this approach, the cleanup and reorg should go in. We should try to avoid pulling the json-c API into core functionality. Maybe we could introduce a generic serializing API (`struct print_ops json_ops { .fdp_events = json_nvme_fdp_events, ... }`). This would make also possible to use different implementation, e.g. a Python based JSON implementation.

Make json-c optional

---

fabrics.c

Fix for: https://github.com/linux-nvme/nvme-cli/issues/1806
When using `nvme connect-all --device` without specifying the options `--host-traddr` and `--host-iface`, the children connections may not have the same `host-traddr` / `host-iface` as the connection to the discovery controller (DC).
This is specific to the `--device` option where one reuses a persistent connection to a discovery controller to update the discovery log pages (DLP) and connect to new controllers listed in the new DLP. If `--device` is used w/o also specifying `--host-traddr` and `--host-iface`, then the new connections may not use the same attributes that were used for the DC connection.
This patch checks if `--host-traddr` and `--host-iface` have been provided, and if not, it will use the DC's `--host-traddr` and …

fabrics: Ensure host-traddr/iface consistency for "connect-all"

---

Documentation/nvme-compare.txt
Documentation/nvme-read.txt
Documentation/nvme-verify.txt
Documentation/nvme-write.txt

Update the documentation on --storage-tag-check. This command line option is a boolean flag and doesn't take any arguments.
Fixes: #1807

doc: --storage-tag-check doesn't take any arguments

---

nvme-print.c

SPDK NVMe character devices are located at /dev/spdk/ according to the documentation (https://spdk.io/doc/nvme.html#nvme_cuse). Fix the typo.
Fixes: 6c9f792f99aa8782b32635c44e3a573bbb36c830 ("nvme: Print full device path")
Cc: Daniel Wagner <dwagner@suse.de>

nvme: fix /dev/spkd/ typo

---

Documentation/nvme-get-log.txt
nvme-wrap.c
nvme-wrap.h
nvme.c
subprojects/libnvme.wrap

nvme: Use chunked read in get_log()
Large transfer might not work because we exhaust resource limits, so
chunk the read into 4k (default).
Fixes: #1818 
Depends: #https://github.com/linux-nvme/libnvme/pull/579

get-log: use chunked read

---

.github/cross/clang.txt
.github/workflows/build.yml

Update the CI build targets so we cover a bit more configuration space.
- Build release and debug builds
- Build with clang
- Cleanup the depdency list, e.g. Drop the libdbus dependency

build: Update CI build targets

---

nvme-print.c
util/json.c
util/types.c
util/types.h

Add uint128_t_to_string_with_sep() to unset the thousands separator. Fixes: 2a8bc94 ("nvme-print: Display smart log data units read and written SI value") Fixes: #1827

util: Revert JSON output to plain numbers

---

nvme-print.c
plugins/memblaze/memblaze-nvme.c
plugins/wdc/wdc-nvme.c

The BIPM recommends that SI units (even those named after scientists) start with a lowercase letter when spelled out.
**References**
* https://www.bipm.org/en/si-base-units/kelvin
* https://www.nist.gov/pml/owm/writing-si-metric-system-units
* https://english.stackexchange.com/questions/173906

Changed 'Kelvin' to 'kelvin', as recommended by the BIPM.

---

plugins/memblaze/memblaze-nvme.c

1. The old nvme-cli set-feature uses 32bit to represent timestamp, but the spec definition is 48bit.
2. memblaze made a slight correction to allow for overflow.
3. Now this correction is no longer needed.

log: high latency timestamp issue

---

nvmf-autoconnect/systemd/nvmefc-boot-connections.service.in
nvmf-autoconnect/systemd/nvmf-connect@.service.in

In order to be able to mount file systems via /etc/fstab we have to make sure that the corresponding auto connect services have been executed. Because the mounting of the local filesystem happens very early in the boot we have to carefully sort these service file into the boot process.
First, we have to disable the DefaultDependency as this will automatically add dependency on sysinit.target which is too late (after local mounts). Though without the default dependency we have to provide a Before and After conditions.
The Before is simple as we have a local-fs-pre target. The After is a bit tricky as there are no targets available.
Because the whole autoconnect machinery depends on udev events being delivered we place the service after systemd-udevd has been started.
Link: …

fabrics: Fix ordering for auto connect services

---

nvme-print-json.c

nvme supported-log-pages -o json currently segfaults due to the wrong json object type as shown below:
nvme: json_object.c: json_object_array_add: Assertion `json_object_get_type(jso) == json_type_array' failed. Aborted (core dumped)
Fix this by passing the appropriate json type.

nvme-print: fix segfault in supported-log-pages json output

---

nvme.c
nvme.h
plugins/intel/intel-nvme.c
plugins/memblaze/memblaze-nvme.c
plugins/micron/micron-nvme.c
util/argconfig.c
util/argconfig.h

Since some features requires the NSID as 0 but not able set previously.

nvme: Change feature default NSID to 0 from all namespaces ID FFFFFFFFh

---

nvme-print.c
util/json.h

Fields `HMPRE`, `HMMIN`, and `NN` in the Identify Controller data structure are 32-bit unsigned values but are being printed as signed integers. Print them using `%u` so large values are not displayed as negative ones. Also make JSON `uint` objects use `uint64` instead of `int64` internally so `u32` values are stored accurately.
Before (on a device which reports `NN` = 0xFFFFEFFF):
```
$ ./.build/nvme id-ctrl /dev/nvme0 | grep nn
nn        : -4097
$ ./.build/nvme id-ctrl /dev/nvme0 -o json | grep nn
"nn":-4097,
```
After:
```
$ ./.build/nvme id-ctrl /dev/nvme0 | grep nn
nn        : 4294963199
$ ./.build/nvme id-ctrl /dev/nvme0 -o json | grep nn
"nn":4294963199,
```

Fix printing of u32 values

---

meson.build

The default sysconfdir needs to be initialize so that Meson and muon expand to the same final result using join_paths().
Fixes: 432a49732bf7 ("build: Use prefixdir directly on sysconfdir")
See https://github.com/linux-nvme/libnvme/issues/588

build: Initialize sysconfdir

---

meson.build

At the end of the meson setup command, display the options so that we can quickly determine that we're configured the project properly
[dwagner: ported this from libnvme to nvme-cli]

build: Print option summary

---

plugins/ocp/ocp-nvme.c

- Add power state change field. This is an OCP 2.0 field.
- Parse full two bytes for point version and minor version fields. Although this should have no functional effect (since versions fields should be zero for 2.0) this should be correct (and if version ever increments past 255 we won't have a bug!)
Screenshots from OCP 2.0:
https://www.opencompute.org/documents/datacenter-nvme-ssd-specification-v2-0r21-pdf

plugins/ocp: OCP 2.0 field updates for SMART cloud log

---

nvme-print.c

The current nvme supported-log-pages output is a little cryptic as seen below:
Support Log Pages Details for nvme1n1:
LID 0x0 (Supported Log Pages), supports 0x3
LID 0x1 (Error Information), supports 0x3
...
So sanitize this output to make it more meaningful with better formatting. This should apply to the verbose output as well. With these changes, the sanitized normal output should show up as follows:
Support Log Pages Details for nvme1n1:
LID 0x0 - Supported Log Pages
LID 0x1 - Error Information
...
And the sanitized verbose output would show up as:
Support Log Pages Details for nvme1n1:
LID 0x0 - Supported Log Pages
LSUPP is supported
IOS is supported
LID 0x1 - Error Information
LSUPP is supported
IOS is supported
...

nvme-print: sanitize supported-log-pages output

---

.github/workflows/build.yml
nvme.c
plugins/inspur/inspur-nvme.c
plugins/solidigm/solidigm-latency-tracking.c

The test target is only the building the minimal dependencies, thus not the complete code base build. Add the build step back.
I noticed that most builds didn't fail though they should have fail  any PR which depends on a libnvme change which is not available.
We hit some clang build failures which we need to fix alongside.

build: Add action build back

---

nvme-print.c
subprojects/libnvme.wrap

Print newly added fields in the error information log page to show which command is errored by opcode. This commit is based on TP4113.
---
This needs (https://github.com/linux-nvme/libnvme/pull/598) to be accepted :)

print: print csi and opcode in error log (TP4113)

---

nvme-print-json.c
nvme-print-json.h
nvme-print.c
util/argconfig.c
util/argconfig.h

1. Split to parse config type function
2. Change if else statement to switch case statement
3. Use calloc instead of malloc
4. Delete unused while 0 statement
5. Add argconfig error common function

util: Cleanup argconfig parse function

---

Documentation/nvme-check-tls-key.txt
Documentation/nvme-connect-all.txt
Documentation/nvme-connect.txt
Documentation/nvme-discover.txt
Documentation/nvme-gen-tls-key.txt
fabrics.c
nvme.c

These are the companion patches to https://github.com/linux-nvme/libnvme/pull/602
We just enable the fabrics options '--tls', '--keyring', and '--tls_key', the actual handling is done by libnvme.

Patches for TLS support

---

nvme-print.c

`nvme list` is one of the most frequently used subcommand to list up nvme devices in the system.  `nvme list -v` prints much more detail in it.  But, those two commands have different number base format which are decimal and hexadecimal without any prefix (e.g., 0x) or something.
nvme list -v shows hexadecimal nsid without `0x` which means it might be confused between decimal and hexadecimal.  To unify this, this patch expands NSID field width from 8 to 10 to cover `0x` two chracters as a prefix.  Chainging it to decimal format might cause issues for the existing systems looking at this value, so just put the prefix on it.

nvme-print: Unify number base format for nsid

---

plugins/solidigm/solidigm-nvme.c
plugins/solidigm/solidigm-nvme.h

Utilized existing SMART cloud implementation in OCP plugin to expose feature in the solidigm plugin (as per OCP 2.0 nvme-cli vendor plugin requirements)

plugins/ocp: Add SMART cloud log to solidigm plugin

---

subprojects/libnvme.wrap

In preparation for the nvme-cli v2.4 release.

build: Bump libnvme to v1.4

---

.github/workflows/appimage.yml

After building the AppImage upload it to an external server.

build: Add external AppImage upload workflow

---

plugins/solidigm/solidigm-nvme.h
plugins/solidigm/solidigm-telemetry.c
plugins/solidigm/solidigm-telemetry/cod.c
plugins/solidigm/solidigm-telemetry/data-area.c
plugins/solidigm/solidigm-telemetry/data-area.h
plugins/solidigm/solidigm-telemetry/header.c

Fixed parsing of 64 bit values.
Fixed COD field name.
Fixed compilation warnings when compiling for 32 bit. Added missing free().
Consolidated single entry function to telemetry parser. Consolidated use of integer types.

plugins/solidigm: Fixes and clean-up of Telemetry parse code.

---

nvme.c

Since if NSID all specified NS data is not identified so the reread failed.

nvme: Fix format command to skip to reread NSID all block device

---

.github/workflows/appimage.yml
.github/workflows/build.yml
meson.build
subprojects/libnvme.wrap

meson's default setting for wrap mode is to attempt to download missing
dependencies. Disable this feature as the community is unhappy with
this default behavior.

Change default fallback behavior

---

Documentation/nvme-connect-all.txt
Documentation/nvme-discover.txt
fabrics.c
fabrics.h
meson.build
nbft.c
nbft.h
plugins/meson.build
plugins/nbft/nbft-plugin.c
plugins/nbft/nbft-plugin.h

Added support for parsing and printing the contents of the NBFT table (per NVMe-oF boot specification v1.0).
```
$ .build/nvme nbft --help
nvme-2.4
usage: nvme nbft  command [device] [args]
The  <device> may be either an NVMe character device (ex: /dev/nvme0), an 
nvme block device (ex: /dev/nvme0n1), or a mctp address in the form
mctp net,eid ctrl-id 
ACPI NBFT table extensions
The following are all implemented sub-commands:
show            Show contents of ACPI NBFT tables
version         Shows the program version
help            Display this help
See nvme nbft help <command> for more information on a specific command
$ .build/nvme nbft show --help
Usage: nvme nbft show <device> [OPTIONS]
Display contents of the ACPI NBFT files.
Options:
[  --output-format=<FMT>, -o <FMT> ]  --- Output …
```

Added NBFT table support

---

plugins/fdp/fdp.c

TP4146 Flexible Data Placement 2022.11.30 Ratified 5.27.1.TBD1 Flexible Data Placement Events (Feature Identifier 1Eh) mentioned as below
This Feature shall be saveable (refer to section 4.2).
Reported-by: Youngjin Jung <yj4369.jung@samsung.com>

fdp: set-events feature is saveable

---

nvme.c
subprojects/libnvme.wrap

Since mos defined __u16, it should be parsed with OPT_SHRT if mos given right after mo, it cause parse error
mo always set as 0
Reported-by: Youngjin Jung <yj4369.jung@samsung.com>

nvme: fix io_mgmt args parse error

---

nvme-print.c

"Reservation Notification Log Page Type" values do not start from 0x1 but from 0x0.
See Page 238:
https://nvmexpress.org/wp-content/uploads/NVM-Express-Base-Specification-2.0c-2022.10.04-Ratified.pdf

nvme: fix rnlpt to_string() values.

---

tests/meson.build
tests/nvme_ctrl_reset_test.py

test added for controller reset and updated test list in meson.build with newly added
test nvme_ctrl_reset_test.
Signed-off-by: Arunpandian J <arun.j@samsung.com>

tests: Add tests for controller reset

---

nvme-wrap.c

if set with NVME_DEFAULT_IOCTL_TIMEOUT, timeout parameter always ignored
Reported-by: Daseul Lee <daseul.lee@samsung.com>

nvme-wrap: do_admin_args_op should not clear args timeout

---

nvme.c

The parameter was changed to use value 8 also by the change 30b89e5ef.
Note: The value is used only for the command functionality to limit feature
output changed from default but not passed to the driver.
Fixes: 63dcb68c6 ("nvme: Fix parameter limit range")

nvme: Fix get-feature command sel parameter check to allow value 8

---

plugins/solidigm/meson.build
plugins/solidigm/solidigm-log-page-dir.c
plugins/solidigm/solidigm-log-page-dir.h
plugins/solidigm/solidigm-nvme.c
plugins/solidigm/solidigm-nvme.h

Added the log-page-directory command to the solidigm plugin as per OCP NVMe Cloud 2.0 nvme-cli requirements (UTIL-NM-7):
https://www.opencompute.org/documents/datacenter-nvme-ssd-specification-v2-0r21-pdf
The feature works by doing the following:
1. Retrieve the supported log pages log (LID=0x00) with UUID index (if specified)
2. If successful, then parse the contents (and add a description)
Parsing works by mapping the specified UUID index to a known solidigm GUID, then assigning a uuid enum. If the uuid enum is valid, then adding a description works the following way:
1. If standard log id (i.e. <0xC0), use the default log id -> description mapping
2. Otherwise, use the uuid enum to find the appropriate log id -> description mapping
**Example Output (nvme solidigm log-page-directory …

solidigm: Add supported log pages log feature to Solidigm plugin

---

nvmf-autoconnect/udev-rules/70-nvmf-autoconnect.rules.in

If another discovery log page change AEN is received while the autoconnect service is already running for a previous AEN, the autoconnect service is not being relaunched. For example, if some of the entries in the log page are not reachable, attempting to connect to them may take a long time before timing out, so AENs received while waiting for the connections have no effect. The AEN is effectively dropped: we ignore the new discovery log entries and worse, the controller won't send more AENs because it's waiting for the log page to be fetched in response to the previous AEN.
Use `systemctl restart` instead of `systemctl start` to ensure `nvme connect-all` is run in response to each AEN. If a previous instance of the service is already running, it will be interrupted and the new log page …

nvmf-autoconnect: restart service to avoid dropping AEN

---

.github/workflows/build.yml

libjson-c-dev:s390x depends on the libgcc-s1 library.

build: Install missing s390 library

---

nvmf-autoconnect/systemd/nvmf-autoconnect.service.in

The unit should be started if either config.json or discovery.conf exists. The current syntax would start it if either one does not exist. Fix it.
Fixes: eec7634 ("fabrics: Trigger auto connect if config.json exists")

fabrics: fix conditions in nvmf-autoconnect.service

---

nvmf-autoconnect/udev-rules/70-nvmf-autoconnect.rules.in

Fix the following warning reported by udevadm verify:
```
nvmf-autoconnect/udev-rules/70-nvmf-autoconnect.rules.in:18 Whitespace after comma is expected.
nvmf-autoconnect/udev-rules/70-nvmf-autoconnect.rules.in: udev rules check failed
```

udev: fix warning reported by udevadm verify

---

nvme-print.c

The NVME_SANITIZE_SSTAT_STATUS_MASK macro is used to mask the 3 least significant bits (representing the status of the most recent sanitize operation) of the SSTAT field.
The SSTAT field is 16 bits wide and contains other information too, such as the Global Data Erased bit and the number of completed passes.
Revert this commit so nvme-cli will print the entire SSTAT field
See NVME Base Specification, page 236
https://nvmexpress.org/wp-content/uploads/NVM-Express-Base-Specification-2_0-2021.06.02-Ratified-5.pdf
This reverts commit 7092ff55c5d9017231a68fa4dbb9a37b42d61d61.

Revert "nvme: Masks SSTAT in sanize-log output"

---

nvme.c

nlbaf returned by id-ns is a 0 based value, so the previous handling of the loop skipped checking the last lbaf.

nvme: Fix nvme format block-size option handling

---

.github/workflows/build.yml
nbft.c
nvme-print-json.h

Configure the muon minimal build without using the json-c fallback. This ensures that the case where json-c is not available is also compile tested.
Fixes #1947

build: Do not use json-c fallback for muon minimal build

---

fabrics.c

Using 'nvme connect' to connect to the well-known discovery NQN could result in a few problems with the current implementation:
1) It does not explicitly disconnect from the discovery subsystem after usage, thereby leading to a spurious discovery controller on the host.
2) Multiple 'nvme connect' invocations to the well-known discovery NQN would result in duplicate discovery controllers on the host.
All this is already handled in 'nvme discover'. So it would be better to avoid using 'nvme connect' to connect to the well-known discovery NQN in the first place, and use 'nvme discover' instead for the same.

fabrics: prevent 'nvme connect' to well-known discovery NQN

---

nvme.c

The submit_io command is using the metadata buffer size provided by the user. But this size argument might be updated and the correct length for the mbuffer is mbuffer_size. Thus use this value and not the initial length.
Fixes: 18de3a6d61a7 ("Convert to libnvme")
Fixes: #1967

nvme: Use correct metadata buffer size

---

nvme.c

The submit_io command is using the buffer size provided by the user. But this size argument might be updated and the correct length for the buffer is buffer_size. Thus use this value and not the initial length.
Fixes: #1967

nvme: Use correct data buffer size

---

nvme-print-json.c
nvme-print-stdout.c
subprojects/libnvme.wrap

https://github.com/linux-nvme/libnvme/pull/657 adds PCI physical slot information to the controller.
This PR prints the Slot number in detailed/verbose output on stdout. JSON object is also updated to include the Slot number in detailed list.

nvme-print: Print PCI physical slot number with -v switch

---

nvme.c

`nvme_show_ana_log()` and `nvme_show_boot_part_log()` are being called with their "length" and "flags" arguments swapped. Fix this so their output is displayed correctly.
```
$ nvme ana-log /dev/nvme1
Asymmetric Namespace Access Log for NVMe device: nvme1
ANA LOG HEADER :-
chgcnt	:	0
ngrps	:	0
ANA Log Desc :-
$ nvme ana-log /dev/nvme1 -o json
{
"Asymmetric Namespace Access Log for NVMe device":"nvme1",
"chgcnt":"0",
"ngrps":"0",
"ANA DESC LIST ":[
]
}
```
Fixes #1994
Fixes: 62a0ce1 ("nvme-print: Unify flag passing into functions")
Fixes: 079afcd ("nvme: add boot partition log support")

nvme-print: fix argument order for show functions

---

util/argconfig.c
util/argconfig.h

util: Set LC_ALL=C as default if -H option is not used

---

fabrics.c
fabrics.h
nbft.c

With the `lookup_ctrl()` check to prevent duplicate connections, identical connections from different hosts are no longer possible. Fix `lookup_ctrl()` to only look for matching controllers on the same host that is being connected.
This restores the ability for multiple hosts on the same machine to connect to the same transport addresses on the same subsystem.
Fixes: 07d6b91 ("fabrics: Do not attempt to reconnect to already connected ctrls")
Previous behavior: `nvme connect` and `nvme connect-all` won't make another connection to the same address from a different host NQN because the address is considered already connected
```
$ nvme connect --transport tcp --traddr 192.168.2.182 --nqn nqn.2010-06.com.purestorage:flasharray.49d21803c4201f6d --hostnqn hostnqn1
$ nvme list-subsys …
```

fabrics: only look for matching ctrl on same host

---

nvme-print-json.c
nvme-print-stdout.c

While iterating through the uuid_list in json_nvme_id_uuid_list() as part of the 'id-uuid' json output, it always misses out displaying the first uuid entry here due to wrongly initialized counter value. Fix it.
And while we are at it, remove the respective comment in stdout_id_uuid_list() as well where this counter is already properly initiatlized.

nvme-print: fix counter while looping through uuid_list

---

nvme-print-stdout.c

The NVM Command Set Extended LBA Format Data Structure has Protection Information Format (pif) and Storage Tag Size (sts) fields. The sts field is incorrectly labeled in the non-verbose normal output.  Fix the label.

nvme-print-stdout: fix storage tag size label

---

Documentation/nvme-ocp-error-recovery-log.txt

Fixed typo in nvme-ocp-error-recovery-log.txt file.

doc: Fix typo in documentation

---

util/json.h

The function `json_object_new_string()` seg. faults when passed a `NULL` pointer. This can happen, for example, when parameters returned by a controller (e.g. Firmware, Model Number, Serial Number, etc.) are undefined and therefore `NULL`. 
This causes the following command to crash:
`nvme list -v -o json`
Note that I had to convert the macros (`#define`) to `static inline` functions. This is to prevent the compiler from generating a lot of `condition always true` warnings for the case where `v` (the pointer that we're checking for `NULL`) is a static string (and hence never `NULL`).

json: fix seg. fault converting NULL to JSON string

---

plugins/zns/zns.c

plugins/zns: Fix offset in report zones

---

nvme.c

nvme: Revert passthru and submit_io to print status to stderr from stdout

---

util/argconfig.c

In order to be able to distinguish between success/failure case when calling strtol/stroul we set errno explicitly to 0.
Fixes: #2030

util: Set errno to 0 before strtol/stroul call

---

nvme-wrap.c
nvme-wrap.h
nvme.c
subprojects/libnvme.wrap

The nsid argument of the  nvme_{mi_admin}_identify_secondary_ctrl_list
command has been removed. Update the call side accordingly.
Fixes: https://github.com/linux-nvme/libnvme/issues/700

nvme: Update list secondary command

---

.github/workflows/appimage.yml
.github/workflows/build.yml
.github/workflows/coverage.yml
meson.build
scripts/build.sh

The builds keep failing because the install step fails. Use prebuild containers which contain all the dependencies.
While at it, also add a coverage build.

build: use prebuild containers for builds

---

.github/workflows/appimage.yml
.github/workflows/build.yml
.github/workflows/coverage.yml

We control the build containers so there is little risk that these randomly break. So let's go with the latest version and avoid updating the build files all the time.

build: use latest container instead fixed version

---

Documentation/nvme-ocp-set-dssd-power-state-feature.txt
completions/_nvme
completions/bash-nvme-completion.sh
plugins/ocp/ocp-nvme.c
plugins/ocp/ocp-nvme.h

Added DSSD Power state feature(FID: C7h) in OCP plugin and related documentation, bash completion in respective directory.

plugins/ocp: Add DSSD Power state feature(FID: C7h) 

---

nvme.c

this modification orignally applied in below commit 9643090317e8eef5b1f9b2c9abda18e06b3e5902

nvme: Do not map status to errno codes

---

nvme.c
plugins/intel/intel-nvme.c
plugins/wdc/wdc-nvme.c
plugins/zns/zns.c

Use same label name for same purpose
it was missing modification of 11542bbdb1c1ad7b1f425925ce474c7ce06162d0

tree: Modify label name close_fd to close_dev

---

nvme-print-stdout.c

Protection information size is not always 8 bytes. For 16b Guard PI format, the PI size is 8 bytes but for 32b and 64b Guard PI formats the PI size is 16 bytes.
See Section 5.2.1 (pp. 76-79) of the NVM Command Set Specification Revision 1.0c: https://nvmexpress.org/wp-content/uploads/NVM-Express-NVM-Command-Set-Specification-1.0c-2022.10.03-Ratified.pdf
To avoid confusion, omit the PI size.

nvme-print: omit size of protection information

---

fabrics.c
subprojects/libnvme.wrap

Removing duplicate code and moving to libnvme. This nvme-cli patch depends on libnvme commit 18b3316c502f229a5339d2c283510ec8008ec3b9.
Depends-on: https://github.com/linux-nvme/libnvme/pull/716
Some of the checks will fail until the above PR has been merged on libnvme.

fabrics: Move duplicate code to libnvme

---

nvme-print.h
nvme.c
nvme.h
plugins/micron/micron-nvme.c
plugins/scaleflux/sfx-nvme.c
plugins/wdc/wdc-nvme.c
plugins/zns/zns.c
util/cleanup.h

The kernel supports since v5.2 direct mapped DMA buffers to userspace.
Up to this point a bounce buffer was involved. Because the buffers are
now directly accessed by the device, the rules of alignment also apply
for the payloads.
Furthermore, ensure that the buffer is a multiple of 4k, because there
are devices on the market which will always transfer a multiple of 4k,
even if we ask for less, e.g 512 bytes. This avoid stack smashes.
Fixes: #https://github.com/linux-nvme/libnvme/issues/684

 nvme: allocate aligned payloads for all nvme commands

---

completions/_nvme
completions/bash-nvme-completion.sh
plugins/ocp/ocp-nvme.h

Get rid of the "vs-" prefix in the fw-activate-history command to bring it in line with the other command names

nit: ocp: rename FW activation history command

---

nvmf-autoconnect/udev-rules/71-nvmf-iopolicy-netapp.rules.in

The current 71-nvmf-iopolicy-netapp.rules.in sets the round-robin iopolicy not just on nvme i/o subsystems, but on discovery subsystems too. Update this rule to have this applied to i/o subsystems alone.
Cc: Clayton Skaggs <claytons@netapp.com>

udev-rule: apply round-robin iopolicy on i/o subsystems alone

---

completions/bash-nvme-completion.sh

The variable containing the commands is call _cmds and not cmds, thus the tab completion didn't work for 'version' and 'help'.
Fixes: #1950

completion: add 'version' and 'help' to list

---

Documentation/nvme-phy-rx-eom-log.txt
nvme-builtin.h
nvme-print-binary.c
nvme-print-json.c
nvme-print-stdout.c
nvme-print.c
nvme-print.h
nvme-wrap.c
nvme-wrap.h
nvme.c

This primarily introduces a new command `phy-rx-eom-log` for getting that log page and allowing the user to specify the lsi/lsp values for it. These changes depend on libnvme commit `e923016`.
One question I have is how to handle failing allocations in `nvme-print-json.c`. Currently these changes just silently fail to include the printable eye data in the json root, but if there's some way this error should be reported I can make that change.
The second commit addresses a very minor bug obscuring non-zero reserved fields for fdpa. I could split this out into its own PR if that would be preferred, otherwise it seemed simple enough to include here as a separate commit.

Add Support for Phy rx eom log

---

unit/test-uint128.c
util/types.c

The separator char can be an utf-8 encoded symbol thus the length of the string is necessarly one.
Fix: #2061

Fix utf-8 encoded number strings

---

.github/workflows/appimage.yml
.github/workflows/coverage.yml
.github/workflows/release.yml

There is no point trying to upload any artifacts to linux-nvme organization if it's a fork.

build: upload artifacts only for upstream repo

---

nvme.c

No meta data is transfered for PRACT=1 and MD=8:
5.2.2.1 Protection Information and Write Commands
5.2.2.2 Protection Informatio and Read Commands
Fixes: #2016

nvme: do not include meta data for PRACT=1 and MD=8

---

.github/workflows/codeql.yml

Add codeql.yml configuration file to allow routine static and vulnerability checks. By the way, codeql has detected one issue on the current head of master. I can provide additional details if required.

Add support for codeql sweeps

---

nvme-print-stdout.c
subprojects/libnvme.wrap

In nvme-cli 1.16, printing the Host Behavior Support feature logged the values of the 3 fields ACRE, ETDAS, and LBAFEE. This appears to have regressed in nvme-cli 2.0, and now only the value of ACRE is printed, without any description. Log all 3 fields with proper descriptions. Drop "Host Behavior Support" from their names, as it's redundant with the feature name.
This depends on https://github.com/linux-nvme/libnvme/pull/736
nvme-cli 1.16 output:
```
$ nvme get-feature /dev/nvme1 --feature-id 0x16 --human-readable
get-feature:0x16 (Host Behavior), Current value:00000000
Host Behavior Support Advanced Command Retry Enable (ACRE): False
Host Behavior Support Extended Telemetry Data Area 4 Supported (ETDAS): False
Host Behavior Support LBA Format Extension Enable (LBAFEE): False
``` …

print-stdout: print Host Behavior Support correctly

---

nvme.c

Fixes: fed9e5ee04cd ("nvme: auto free nvme_dev resource")

nvme: allow set-features to take input from stdin

---

Documentation/nvme-copy.txt
libnvme-wrap.c
nvme-print-stdout.c
nvme.c
tests/nvme_copy_test.py
tests/nvme_test.py

Add support for NVMe TP4130 ("Cross-Namespace Copy")
- Add Copy Descriptor Formats 2h and 3h
- Add "--snsids" option to specify source namespaces to copy from
- Add "--sopts" option to specify source options (Fast Copy Only)
- Print new Host Behavior Support bits, new ONCS bits, and new Optional Copy Formats Supported bits
- Extend unit test case to test cross-namespace copy formats

nvme-copy: support cross-namespace copy

---

Documentation/nvme-ocp-get-plp-health-check-interval.txt
Documentation/nvme-ocp-set-plp-health-check-interval.txt
plugins/ocp/ocp-nvme.c
plugins/ocp/ocp-nvme.h

Added the ocp C6h feature api.
Reviewed-by: Karthik Balan karthik.b82@samsung.com, Arunpandian J arun.j@samsung.com
Signed-off-by: Vigneshwaran Saravanan/SSD TS Dev /SSIR/Engineer/Samsung Electronics <s.vignesh@samsung.com>

plugin/ocp_fid_c6h:Added the ocp C6h feature api

---

libnvme-wrap.c

libnvme-wrap provides fallbacks for missing libnvme functions. For functions that return a value, the FN() macro can be used to define a default return value if the function isn't found. This isn't possible for functions returning void,
so VOID_FN() currently is a no-op if the function can't be found. For nvme_init_copy_range_f1(), the only current VOID_FN() user, this will result in silently sending a Copy command with a zeroed range, which is not what the user requested. Instead, exit the process immediately if the function can't be found.
Here's an example with the `nvme_init_copy_range_f1` symbol removed from `libnvme.map`:
```
$ nvme copy /dev/nvme1n1 --format 1 --slbs 123 --blocks 456 --sdlba 789
libnvme function nvme_init_copy_range_f1 not found
$ echo $?
1
```
Previously this …

libnvme-wrap: exit on VOID_FN lookup failure

---

meson.build
nvmf-autoconnect/systemd/nvmf-autoconnect.service.in
nvmf-autoconnect/systemd/nvmf-connect-nbft.service.in
nvmf-autoconnect/udev-rules/65-persistent-net-nbft.rules.in

Add support to auto connect via NBFT.
@mwilck during updating our downstream packages I noticed these patches never made it upstream. I think they should also be upstream. Any objections?

autoconnect nbft systemd service

---

Documentation/nvme-connect.txt

There is no code which reads in the secret from the mentioned file. This was done in the early stages of the implementation. But it is not considered good practice to store secrets as plain text in /etc, thus this feature was removed later. Instead the connect command is able to use the kernel keystore for this.
Fixes: #2120

doc: remove invalid hostkey info for --dhchap-secret

---

scripts/build.sh

A few improvements for the build.sh script for muon
- do not rebuild samurai/muon every time.
- drop dependency on `libcurl`, `libarchive` and `libpkgconfig`. The `wrap` feature of muon is using `git` directly to fetch `libnvme`.

update build.sh script for muon builds

---

README.md

Add more information how to build the project in different scenarios (older distros, static builds etc.).
Also mention where to download the test AppImage.
Fixes: #2108

doc: add additional build instructions

---

nvme.c

The raw secret is passed in hex, so the length of the input is twice the size of the key.

nvme: fixup length calculation for 'nvme gen-tls-key --secret'

---

Documentation/nvme-check-tls-key.txt
Documentation/nvme-gen-tls-key.txt
nvme.c
subprojects/libnvme.wrap

TP8018 specifies a new TLS identifier, where the original TLS identifer is suffixed with a PSK hash. This allows to differentiate between keys with different key material and with that enables key rotation.

Implement support for version 1 TLS identifiers as specified in TP8018 (version 2)

---

nvme.c

During nvme gen-tls-key generation, the permitted hmac options is 1 for SHA-256 & 2 for SHA-384 respectively for the retained key. But nvme-cli mistakenly permits an additional option 3 too which defaults to SHA-256 itself. Rectify this.

nvme: restric hmac options for gen-tls-key

---

fabrics.c

Nvme connect currently fails with an "Invalid output format" error if no output-format is specified to the nvme connect command. Fix this by initializing the format string.

fabrics: fix invalid output format error during nvme connect

---

fabrics.c

Currently one sees a connect error during a nvme discover/connect if the hostnqn file exists, but not the hostid file. Fix this by ensuring the hostid is taken from the corresponding hostnqn for such scenarios.

fabrics: fix connect error if hostid file does not exist

---

nvme-print-stdout.c

Print a more meaningful connect message.

nvme-print-stdout: enhance connect message

---

.github/workflows/checkpatch.yml
nvme-print-json.c

The JSON refactoring and cleanup change renamed a bunch of existing field names which breaks existing users. Revert to the old names.
Fixes: 1d7c092 ("nvme-print-json: Combine duplicated json key and val string variables")
Fixes: #2166

nvme-print-json: Revert field name changes

---

fabrics.c

Currently nvme connect prints an annoying "use hostid which does not match uuid in hostnqn" warning even for normal scenarios when both the hostid and hostnqn files are present. So move these warnings to verbose level instead.

fabrics: move hostid/hostnqn warnings to verbose level

---

plugins/wdc/wdc-nvme.c
plugins/wdc/wdc-nvme.h
plugins/wdc/wdc-utils.c

Fix a potential buffer overrun error when
retrieving the VU internal debug data log.
Fix vs-smart-add-log for SN-861 drives
Simplify the wdc_UuidEqual function

wdc: Plugin fixes and updates

---

nvme.c

nvme check-tls-key currently misses out successfully printing the inserted tls key, so print the same. And while we are it, fix a small typo while printing the error message related to the failure of generating the identity key.

nvme: print inserted tls key for check-tls-key

---

nvme-print-stdout.c

Trivial typo fix in the nvme list verbose output.

nvme-print: fix typo in list verbose output

---

nvme.c

when create telemetry log host, parse telemetry da
Reported-by: Ki ryoung <kiryong1.kim@samsung.com>
Signed-off-by: Minsik jeon <hmi.jeon@samsung.com>

nvme: Parse telemetry da in create telemetry log host

---

nbft.c

libnvme introduced a specific error code (NVME_CONNECT_ADDRNOTAVAIL) when the address is not available. Previously, the generic error code (NVME_CONNENCT_WRITE) was return in this case.

nbft: fix tcp/dhcp address fallback retry

---

Documentation/nvme-connect-all.txt
Documentation/nvme-connect.txt
Documentation/nvme-discover.txt
fabrics.c
subprojects/libnvme.wrap

Add support for option '--concat' to enable secure concatenation after DH-HMAC-CHAP.

Implement support for secure concatenation

---

Documentation/nvme-connect-all.txt
Documentation/nvme-connect.txt
Documentation/nvme-discover.txt

It was renamed to "-J" but some docs were left out.

doc: Fix short option name for cfg-file

---

nbft.c

Do not print error message if ACPI tables are no present

---

Documentation/nvme-create-ns.txt
nvme.c

Some controllers refuse to create namespaces with a size not aligned to a 1 megabyte boundary, this happens when using the -S and -C options.
$ nvme create-ns /dev/nvme0 -S 80M -C 80M -f 0
NVMe status: Invalid Field in Command: A reserved coded value or an unsupported value in a defined field(0x2)
Fix this problem by modifying parse_lba_num_si() to align the values to 1 Megabyte boundaries.

create-ns: align the namespaces to 1Mib boundaries when using SI suffixes

---

nvme.c

The descriptions are already line wrapped as appropriate. Don't insert random newline characters in inappropriate places. It just makes the output look rediculous.

don't include newlines in already wrapped text

---

nvme-print-json.c

The valid object is of type array not obj, thus use obj_add_array to add it to the root.
Fixes: #2213

nvme-print-json: append array object in json_support_log

---

plugins/sed/sedopal_cmd.c

Ask for password twice in case there is a typo in entering it.

sed: Confirm entered password before initialization.

---

nvme-print-json.c

This reverts commit b854cbda04a19b7dcfcbeb569146cf9ab79fd5f3.

Revert "nvme-print-json: remove obj_print helper"

---

nvme-print-stdout.c
nvme.c

Print additional details such as loc, nidt, nidl & type in the ns-descs verbose output for parity with the corresponding json output.

nvme-print: print more details in ns-descs verbose output

---

nvme-print-json.c
nvme-print-stdout.c
nvme.c

Note: Partially duplicated with the PR #2188 changes so merged later.

nvme: Add show-regs and get-property commands NSSD print outputs

---

nvme-print-stdout.c
nvme-print.c
nvme-print.h
subprojects/libnvme.wrap

Change the hardcoded the register bit shift to use the definitions.

nvme-print-stdout: Use persistent event log RCI definitions

---

plugins/wdc/wdc-nvme.c
plugins/wdc/wdc-nvme.h
plugins/wdc/wdc-utils.c

This change will use UUID lists to access the WD C2 log page and retrieve the correct info needed to display the drive status.

wdc: Add support for the get-drive-status command to SN861

---

plugins/ocp/ocp-fw-activation-history.c

The current code is displaying all 8 bytes of the timestamp field for the timestamp.  The timestamp value is only in the first 6 bytes. The 7th byte contains the origin and synch fields and the 8th byte is reserved.

ocp: Fix timestamp displayed by fw-activate-history command

---

fabrics.c
nvme-wrap.c
nvme-wrap.h
nvme.c
nvme.h
subprojects/libnvme.wrap
util/logging.c
util/logging.h
util/meson.build

Introduce a global log level which then can be forwarded to libnvme. Also provide our own low level passthru commands so that we extend it with extensive logging outputs. While it also support the 64 bit version of it.

Refactor and extend logging

---

plugins/micron/micron-nvme.c

Fix the time-of-check time-of-use filesystem race condition.

plugins/micron: Fix code scanning alert

---

nvme-print-stdout.c

Change it instead of hardcoded register mask and shift values.

nvme-print-stdout: Use NVME_PMRCAP register definition to print

---

nvme-print-stdout.c

Also unify to use %#x or %#"PRIx64" instead of 0x%x and 0x%"PRIx64".

nvme-print-stdout: Add hexadecimal value 0x prefix

---

plugins/wdc/wdc-nvme.c
plugins/wdc/wdc-nvme.h

The actual timestamp value is in bytes 0:5 of the 8 byte field. The code was using all 8 bytes so a change was made to mask off the top 2 bytes.  The timestamp calculations were also simplified to be more maintainable.

wdc:  Fix timestamp displayed by vs-firmware-activate-history command

---

fabrics.c
nvme.c

nvme 1.x did not issue an warning when the nvme_core module was not loaded. Make 2.x behave in the same way.
Fixes: #2241

nvme: do not issue warning when nvme_core module is not loaded

---

plugins/ocp/ocp-nvme.c

Noticed this as part of supporting set-telemetry-profile, it seems that the power-state option is not being detected properly. With this fix the function is able to enter set_dssd_power_state when given the option or its alias.

ocp: fix for power-state argument checking

---

nvme-print-stdout.c

Change it instead of hardcoded register mask and shift values.

nvme-print-stdout: Use NVME_SET_FEAT_EVENT register definitions

---

nvme-print-stdout.c

Use it with NVME_FID_SUPPORTED_EFFECTS register definitions existed.

nvme-print-stdout: Use NVME_GET for FID supported and effects FSP

---

nvme-print-stdout.c

Change it instead of hardcoded field mask and shift values.

nvme-print-stdout: Use NVME_BOOT_PARTITION_INFO field definitions

---

meson.build
nbft.c
nvme-print-json.c
nvme-print-stdout.c
plugins/nbft/nbft-plugin.c
plugins/sed/sedopal_cmd.c

The meson 'debug' buildtype defaults to '-O0 -g' which misses some important compiler warnings (as of gcc-13). While there's     no universal solution, the 'debugoptimized' buildtype supplies '-O2 -g' that appears to be a reasonable compromise for having    important compiler warnings by default.
Either way, the specified warning_level=1 always supplies '-Wall' that is unfortunately not enough with '-O0'.

meson buildtarget + some warning fixes

---

nbft.c
nbft.h
plugins/nbft/nbft-plugin.c

This adds support for the newly introduced `unavailable` SSNS flag. Certain firmware (UEFI) implementations may include SSNS records in the ACPI NBFT table that failed to connect and optionally provide a detailed reason (TP-8029, not subject to this pull request).
In userspace I thought it might be beneficial to do another connection attempt, with expectation of failure. Such failure should not be reported nor should fail the whole connection process (`nvme connect-all --nbft`). Failure messages would still be reported in verbose mode.
As currently designed, three connection attempts are made: the pre-OS/UEFI phase, dracut and another try via the `nvmf-connect-nbft.service` systemd unit. Between these attempts networking may change, new routes added, tunnels established, etc.
Needs …

NBFT parser SSNS flags

---

Documentation/nvme-ocp-set-telemetry-profile.txt
completions/_nvme
completions/bash-nvme-completion.sh
plugins/ocp/ocp-nvme.c
plugins/ocp/ocp-nvme.h

Adds a new OCP plugin function to set the device telemetry profile, configuring what debug data shall be collected by the device.

ocp: support OCP 2.5 Set Telemetry Profile feature

---

nvme.c

The mmap registers has been changed to not use the nvme root.

nvme: Delete unused nvme root scanned

---

plugins/wdc/wdc-nvme.c

Fix the comparison of narrow type with wide type in loop condition.
Note: Include some coding style errors fixes.

plugins/wdc: Fix code scanning alert

---

nvme.c

The memory is allocated by the gen-tls-key and check-tls-key commands.

nvme: Fix to cleanup free raw_secret memory allocated

---

plugins/memblaze/memblaze-nvme.c

Change the definition from "flash_error_media_count" to "inflight_write_io_cmd".

plugins/memblaze: fix code mis-type error

---

plugins/sed/sedopal_cmd.c

The SED key and kernel keyring were not being updated by the initialization operation. Add password update after the other initialization tasks are completed.

sed: update SED password when initializing

---

nvme-print-json.c

There is a history of combining duplicated json keys before.
Fixes: 1d7c092f9dac ("nvme-print-json: Combine duplicated json key and val string variables")
Fixes: 59a0f125cb08 ("nvme-print-json: Delete static const char string global variables")
But there is a local variable with the same name, so the key and value are the same.
Reviewed-by: Sangkuk Lee <sangkuk0.lee@samsung.com>
Reported-by: Kiryong Kim <kiryong1.kim@samsung.com>
Signed-off-by: Minsik Jeon <hmi.jeon@samsung.com>
Co-authored-by: Steven Seungcheol Lee <sc108.lee@samsung.com>

nvme-print-json: Bugfix status json key of sanitize-log

---

nvme.c

When the scan operation fails, let's also report the error code in order to help understand why the operation failed.

nvme: extend error message for ns scan failures

---

Documentation/nvme-tls-key.txt
nvme-builtin.h
nvme.c
subprojects/libnvme.wrap

Add a new utility 'tls-key' to import or export keys to or from the kernel keystore.

Implement persistent keys

---

nvme-print-stdout.c

Replace hard coded register value, shift and mask values.

nvme-print-stdout: use CSTS definitions

---

nvme-print-stdout.c

Replace hard coded register shift and mask values instead.

nvme-print-stdout: use admin queue attributes definitions

---

nvme.c

Printing the encoded key is useful with gen-tls-key's -i option as well.

nvme: print encoded key for gen-tls-key's -i option too

---

nvme.c

Nvme check-tls-key requires both hostnqn and subsysnqn to be specified along with the keydata. Ideally, it should be able to fetch the hostnqn string from the hostnqn file if no hostnqn option is passed, irrespective of whether the insert option is specified or not. Also passing the subsysnqn option is required not just for identity v1, but for v0 as well, irrespective of the insert option. Fix accordingly.

nvme: check-tls-key fails despite having hostnqn file

---

nbft.c

With planned NBFT discovery work, a common connection function would be handy. Besides, the DHCP fallback mostly duplicated the connection code anyway, let's refactor that.

nbft: Refactor connection attempt out

---

Documentation/nvme-get-reg.txt
Documentation/nvme-set-reg.txt
common.h
completions/_nvme
completions/bash-nvme-completion.sh
nvme-builtin.h
nvme-print-json.c
nvme-print-stdout.c
nvme-print.c
nvme-print.h
nvme.c
nvme.h

Note: Currently only stdout print supported.

nvme: Add support for get-reg command to output single register

---

fabrics.c

The payload should be properly aligned.
Fixes: #https://github.com/linux-nvme/libnvme/issues/807

fabrics: align identify command payload

---

util/logging.c

This reverts commit a2b1aecb9075c7a8f9bad627fc45171bb533c8bd.
The result field is undefined for many commands and thus can have random values. Thus we can't blindly evaluate these for all commands.

Revert "logging: fix error handling for ioctl passthru wrappers"

---

nvme-print-stdout.c

Use libnvme register definitions instead.

nvme-print-stdout: Use NVME_CMBLOC definitions

---

fabrics.c

Valgrind revealed a mem leak in nvmf_check_hostid_and_hostnqn() during nvme discover & connect. Leak traced to both hostid pointers not getting freed for cases where the hostid value matches the strings from both these respective hostid pointers. Fix the same.

fabrics: fix mem leak in nvmf_check_hostid_and_hostnqn()

---

nvme.c

Valgrind revealed mem leaks in multiple key related functions including gen_tls_key() and check_tls_key() during insert, and gen_dhchap_key(). This was traced to the respective cfg pointer not getting freed after fetching the hostnqn string from the hostnqn file. Fix the same.

nvme: fix mem leak in multiple key related functions

---

.github/workflows/appimage.yml

This reverts commit 158eb8d82c497c104cf9c2d4665983084cc8ae0e.
This breaks the build with
'appimagecrafters/appimage-builder:0.8.2' should be either '[path]/Dockerfile' or 'docker://image[:tag]'.
v2 was released a couple of years ago, so I don't expect this gets fixed at all. Instead go back to last good version.

Revert "build(deps): bump AppImageCrafters/build-appimage from 1.3 to 2"

---

plugins/ocp/ocp-utils.c
plugins/ocp/ocp-utils.h

Enable reuse of OCP UUID discovery logic from other plugins. Enable single call to nvme_identify_uuid() when dealing with multiple UUIDs

plugins/ocp: Split ocp_get_uuid_index() into find and get functions.

---

nvme.c

Check the firmware file size if not aligned with FWUG value.

nvme: Add fw-download warning message for FWUG alignment error

---

nvme.c

`sizeof(*sec_buf)` should return 1, which would mean `sec_buf` is not properly allocated to receive data from the target device. This fixes that.

nvme: fix security buffer allocation size

---

plugins/ocp/ocp-clear-features.c
plugins/ocp/ocp-fw-activation-history.c
plugins/ocp/ocp-nvme.c
plugins/ocp/ocp-utils.c
plugins/ocp/ocp-utils.h
plugins/solidigm/solidigm-util.c

Changed uuidx type to __u8 in the related function calls, because that's the type that will feed struct nvme_get_log_args.

plugins/ocp: Adjusted variable type size carrying UUID index to 8 bit.

---

nvme-print-stdout.c

Use libnvme definitions to print CMIC data.

nvme-print-stdout: Use NVME_CMIC definitions

---

nvme-print-stdout.c

Added by NVMe revision 2.0 multiple controller shutdown enhancement.

nvme-print-stdout: Add CSTS.ST register stdout print

---

nvme.c

Print an error message and return the error code to the caller.

nvme: fix error path if write() fails in get_telemetry_log()

---

meson.build
plugins/meson.build

There's already code to not build the sed opal plugin when the necessary headers aren't present. However, it doesn't work, since HAVE_SED_OPAL is always defined to be either 0 or 1, so the meson has() return true, even when the value is 0, causing the sed-opal plugin to build, even when the header files it needs are missing.
Note: This came up in the context of my updating the FreeBSD port to the latest. Meson makes it a lot easier than before to do a minimal change port, but this is one of the few actual bugs that I found and so should change upstream. This issue is independent of my port, even though it came up in that context.
Also updated to add a second commit that fixes a spelling error in meson.build while I'm in the neighborhood.

sed_opal: Only build when we really have sed_opal headers

---

nvme-wrap.c
nvme-wrap.h

`nvme_cli_get_log_ana_groups()` is not called anywhere. In preparation for a `libnvme` change that changes the signature of `nvme_get_log_ana_groups()`, just remove the function.

nvme-wrap: remove unused nvme_cli_get_log_ana_groups()

---

nvme-wrap.c
nvme-wrap.h

The identify primary ctrl command do not accept the namespace argument. Thus remove it.
While at it, also update identify secondary ctrl function to use same argument name.

nvme: identify primary ctrl do not accept nsid

---

nvme-print-stdout.c

The fields needed be output only as the 52 most significant bits.

nvme-print-stdout: fix ASQB, ACQB and BMBBA prints

---

nvme.c
subprojects/libnvme.wrap
util/cleanup.h

We currently only initialize the libnvme logging for those commands which use the `nvme_root_t` object. In order to get the logging going for all commands we have to initialize the logging for every command.
This is a first attempt to solve this. Maybe it would be better to initialize the libvnme logging just once for all commands.
For this draft I'v just made it work for the `read` and `write` command (submit_io).

Initialize logging for commands

---

nvme.c

The pevent_collected structure uses the buffer address which is allocated using nvme_alloc_huge(). So, pevent_collected and mh.p has same address. Hence, removing _cleanup_free_ from pevent_collected to prevent double free.

nvme: remove double free in persistent-event-log

---

plugins/solidigm/solidigm-internal-logs.c
plugins/solidigm/solidigm-market-log.c

ARG_MAX is defined in <limits.h>, per POSIX, but it's defined to be a variable in glibc. Instead, get rid of it entirely by using asprintf to construct the commands. This prevents us from trying a partially constructed command that might do something unintentional. For solidigm-market-log.c, there's no constants needed from <linux/limits.h>. With this we can delete it both places.

solidigm: Eliminate <linux/limits.h>

---

nvme.c
plugins/innogrit/typedef.h
util/base64.c

<stdint.h> provides `uint32_t`, while `u_int_32` is an unofficial/internal typedef that glibc happens to provide. This fixes the build on musl.
Bug: https://bugs.gentoo.org/931194

Use C99 types for uint32_t

---

nvme-print.c

nvme-print: Added "Command and Feature Lockdown" string to LID 0x14

---

Makefile

The `Makefile` is mainly used as a tool for people not familiar with `meson`. However, the `Makefile` is a good way to see how to invoke `meson` properly. This patch contains a few small fixes to match the preferred way of invoking `meson`.

build: Update meson commands in Makefile

---

nvme-print-json.c
nvme-print-stdout.c

Note: The long line string and strncpy() warnings are not fixed.

nvme-print-json: Fix linux kernel check patch errors

---

plugins/sed/sedopal_cmd.c

The partition table was being re-read after both lock and unlock operations. The re-read would fail with an error message after a lock since the partiton was no longer readable.

sed: only re-read partition table after unlock.

---

nvme.c

As per spec, 0th bit is set when the controller detects an overlapping firmware/boot partition image update command sequence due to processing a command from an Admin Submission Queue on a controller and the 1st bit is set due to processing the command from Management Endpoint. So, fixed the MUD result message.

nvme: fix fw-commit MUD result message

---

plugins/ocp/ocp-nvme.h

Title - I probably should have done this a lot earlier.
I (sort of arbitrarily) chose 77f6c8fc3ad808422127c052cdbd40b62cb348d7 to be the starting point for version ```1.0.0```. From there, I worked forward in the history and more or less added 1 to the minor version for every command added to the OCP plugin. Happy to take suggestions if anyone has a better idea.

ocp: Switch OCP plugin to use semantic versioning

---

plugins/nbft/nbft-plugin.c

Remove the workaround with creating empty root object and use the new libnvme API instead.
(reverts one part of #2215)

plugins/nbft: Use default library logging

---

plugins/sed/sedopal_cmd.c

The non-destructive revert was not sufficiently reverting the lsp. A TPER revert is required or the drive is only partially reverted.

sed: perform a tper revert after lsp revert

---

plugins/ssstc/ssstc-nvme.c

uint16_t is ISO defined and comes from stdint.h, makes it portable across glibc and musl on linux.

plugins/ssstc: Replace __uint16_t with uint16_t

---

nvme-print-stdout.c

Fix to print the log within one line per each FID (LID - 12h) and NVMe-MI Command (LID - 13h) while printing in human readable form.

nvme-print-stdout: fix to print the log line by line

---

nvme-print-stdout.c

Print MDTS and Size Limits Exclude Metadata(MEM) bit of CTRATT field which added in TP-4099.

nvme-print-stdout: print MEM bit of CTRATT field

---

.github/workflows/build.yml
scripts/build.sh

Build and install libnvme separately from libnvme. This should catch any attempts to include private headers from the library.
Also this is what distro usually do, so we should test this as well.

build: separate builds of libnvme and nvme-cli

---

nvme-print-stdout.c

This fix for nvme spec 2.0 where FLBAS bits 6:5 indicates the most significant 2 bits of the Format Index
that was used to format the namespace. So, use nvme_id_ns_flbas_to_lbaf_inuse function to get the proper
format index of the namespace.

nvme-print-stdout: fix format index in stdout_nvm_id_ns

---

fabrics.c
fabrics.h
nbft.c
nbft.h
util/cleanup.h

This brings support for performing discovery and connect-all from Discovery Descriptor List records.
Needs https://github.com/linux-nvme/libnvme/pull/820 to parse URIs from NBFT.
Tested with static IPv4 and IPv6 against linux soft target. ~~For now, persistent discovery controllers have not been tested.~~

nbft: Discovery support

---

nvme-print.c

Print the correct opcode name instead of "Unknown".

nvme-print: add the cancel opcode the nvme_cmd_to_string() list

---

nvme.c

It's wrong to assume that if the ioctl() returns a non-zero number then the errno variable is set.
The ioctl() might return an NVMe Status error to inform the caller that the requested log page is not supported, in that case errno is left untouched.
The original code didn't handle this case and returned "-errno" even when the latter was zero. The caller interpreted this as a successful operation and this might lead to improperly dereferencing the log page pointer.
$ nvme telemetry-log /dev/nvme0 --output-file=telemetry_log.bin
ERROR: get_telemetry_log: : write failed with error : Bad address
Fix this bug by returning the NVMe status if errno is zero:
$ nvme telemetry-log /dev/nvme0 --output-file=telemetry_log.bin
NVMe status: Invalid Log Page: The log page indicated is invalid(0x109) …

nvme: telemetry: report the correct error if the ioctl() fails.

---

Documentation/nvme-format.txt
nvme.c

Protection Information is not only 8 bytes of the metadata, it can also be 16 bytes such as in 32b and 64b guard protection formats.

documentation fix for format cmd

---

nvme-print-stdout.c
nvme.c

Use PIF enum and add a helper function to print the Protection Information Format(PIF) in string form.

nvme-print-stdout: Add helper function to print PIF in string form

---

plugins/ocp/ocp-nvme.c

Printing the GUID was crashing due to the unsigned int never becoming less than 0, and fixing that triggered a warning about an incorrect max index when printing Event FIFO data.

plugins/ocp: undeflow + index fixes for telemetry

---

fabrics.c

The fabric commands don't depend on the namespace information. Since we are hitting scalling issues with large number of namespaces, skip the scan for those.
Fixes: #2231

skip namespace scan for fabric commads

---

nvme-print-json.c

Every va_start() should be matched by a corresponding va_end() to keep the static analyzers happy.

nvme-print-json: add missing va_end()

---

nvme-wrap.c
nvme-wrap.h
nvme.c
subprojects/libnvme.wrap

Depends on linux-nvme/libnvme/pull/848
---
`nvme ana-log` only includes space for MNAN namespace IDs
in the allocated ANA log page buffer if bit 6 of ANACAP
in the Identify Controller structure isn't set.
But the specification says:
Bit 6 if set to '1', then the ANAGRPID field in the Identify Namespace
data structure (refer to the NVM Command Set Specification)
does not change while the namespace is attached to any controller
There is no suggestion that NSIDs won't be returned in the ANA log page.
However, we can exclude space for NSIDs from the allocated buffer
if the Get Log Page command is going to be sent with the RGO bit set,
i.e. the `--groups` argument is passed.
Therefore, use the `libnvme` helper `nvme_get_ana_log_len_from_id_ctrl()`
to calculate the maximum ANA log page length. …

Use ANA log page fixes from libnvme

---

nvme-print-json.c
nvme-print.c
nvme-print.h

Previously PEL reserved event output as NULL string. This resolves to print as reserved event with the event type value.

nvme-print: Print PEL reserved event string

---

nvme.c

Treat non-zero return values from parse_args() as errors, and not just negative return values. Also makes this consistent with other functions in nvme.c where parse_args() is invoked.

nvme: update parse_args() return value handling

---

nvme-print.c
nvme-print.h

Fix for the checkpatch review error below.
Error: WARNING: Prefer 'unsigned int' to bare use of 'unsigned'

nvme-print: Use 'unsigned int' instead of 'unsigned'

---

plugins/wdc/wdc-nvme.c

Make the file_path array size match the input

wdc: Fix compiler warning.

---

plugins/ocp/meson.build
plugins/ocp/ocp-nvme.c
plugins/ocp/ocp-telemetry-decode.c
plugins/ocp/ocp-telemetry-decode.h

This commit will provide the first phase of changes needed for parsing of OCP 2.5 Telemetry Log Pages 7h and 8h, Data Areas 1 and 2.  It will decode the predefined classes for Data Area 1 and 2 Statistics, and Event FIFO's.

ocp: OCP 2.5 Telemetry DA 1 and 2 Parsing Updates

---

common.h

Using nvme show-regs within a VM on arm64 can sometimes lead to VM termination.
To answer why this happens: one of the deficiencies of the Arm architecture is that there exists a range of load/store instructions that have insufficient decode information for traps taken to the hypervisor. KVM, for example, may raise an external abort or outright terminate the VM depending on the configuration.
This is a known problem on the kernel side, and is fixed by using assembly MMIO accessors w/ 'safe' load/store instructions. So do exactly that, providing arm64-specific accessors and falling back to plain old volatile pointer accesses for other architectures.
Reported-by: William Butler <wab@google.com>

common.h: Avoid using unsupported load/store instructions in arm64 VMs

---

nvme.c
plugins/solidigm/solidigm-internal-logs.c
util/cleanup.h

Delete duplicated functions and change _cleanup_file_ to _cleanup_fd_.

nvme: change to use libnvme cleanup functions

---

Documentation/nvme-smart-log.txt
completions/_nvme
completions/bash-nvme-completion.sh
nvme-print-json.c
nvme-print-stdout.c
nvme-print.c
nvme-print.h
nvme.c
nvme.h

Delete the fahrenheit option separately.

nvme-print: check locale to use temperatures in degrees fahrenheit

---

plugins/ocp/ocp-nvme.c

This PR will take care the below failures for "telemetry-string-log"
Resolved the json printing issue
Changed the Statistic Identifier, Event String, Vendor Unique, ASCII table offset and size calculation 
Signed-off-by: Vigneshwaran Saravanan/Vigneshwaran Saravanan <s.vignesh@samsung.com>
Reviewed-by: Karthik Balan <karthik.b82@samsung.com>, 
Reviewed-by:  Arunpandian J <arun.j@samsung.com>, 
Reviewed-by:  Jayakanthan Rajendran <jaya.ganthan@samsung.com>

plugins/ocp : Fixed the OCP Telemetry String Log Page (LID:C9h) fix

---

nvme.c

nvme: use _cleanup_free_ type buffer for get-feature command

---

Documentation/cmd-plugins.txt
Documentation/meson.build
Documentation/nvme-micron-ocp-telemetry-log-parse.txt
completions/_nvme
completions/bash-nvme-completion.sh
plugins/meson.build
plugins/micron/micron-nvme.c
plugins/micron/micron-nvme.h
plugins/micron/micron-ocp-telemetry.c
plugins/micron/micron-ocp-telemetry.h
plugins/micron/micron-utils.c
plugins/micron/micron-utils.h

**Description:**
- Added support for OCP telemetry (internal) log parsing as per OCP 2.5 specification - [Datacenter NVMe SSD Specification v2.5r9.pdf](https://github.com/user-attachments/files/16051920/Datacenter.NVMe.SSD.Specification.v2.5r9.pdf) section 4.9.
- The CLI command will take the input binary files (telemetry/internal logs LOG ID 0x07 or 0x08) and string log (0xC9) as inputs and provides a parsed JSON or text file as attached below:
**CLI Examples:**
$ sudo ./nvme micron ocp-telemetry-log-parse --format=normal --string-log="nvmelog_ocp_c9.bin" --telemetry-log="nvme_host_telemetry_log.bin" --output-file="nvme_cli_telemetry_host_normal.txt" /dev/nvme0
$ sudo ./nvme micron ocp-telemetry-log-parse --format=json --string-log="nvmelog_ocp_c9.bin" …

plugins/micron: Added support for OCP telemetry (internal) log parsing. Datacenter NVMe SSD Specification v2.5r9 section 4.9

---

nvme-rpmb.c

This follows the NVMe revision 2.0a authentication key data flow.

nvme-rpmb: send RPMB_REQ_READ_RESULT for authentication key programming

---

nvme.c
util/logging.c

Verbose logging for certain nvme commands like id-ctrl, id-ns, smart-log, sanitize-log, etc. does not print anything additional or verbose compared to the regular output. These commands already implement a human-readable option which works fine, but it is the verbose option that is broken. So fix the verbose option here to ensure it is on par with the human-readable option. Later if required, we can eliminate any one of these options for these commands to avoid redundancy.

nvme: fix verbose logging for certain commands

---

Documentation/nvme-ocp-eol-plp-failure-mode.txt
plugins/ocp/ocp-nvme.c

The value required from OCP version 2.0 for get feature command also.

ocp-nvme: set UUID index for eol-plp-failure-mode command to get

---

Documentation/nvme-ocp-get-error-injection.txt
completions/_nvme
completions/bash-nvme-completion.sh
plugins/ocp/ocp-nvme.c
plugins/ocp/ocp-nvme.h

The set-error-injection command will be added separately.

ocp-nvme: add get-error-injection command

---

nvme-print-json.c
nvme-print-stdout.c
subprojects/libnvme.wrap

As per TP4090, a new field support is added as NPDGL (Namespace Preferred Deallocate Granularity Large) and so the bit-field of NSFEAT, OPTPERF get extended by 1 bit.
Reviewed-by: Mohit Kapoor <mohit.kap@samsung.com>

nvme-print: add new field added in TP4090

---

nvme.c

As per NVM Command Set Specification, Rev 1.0d, Sec-5.2.2 PRACT Bit: "If PRACT bit is set to 1 and Metadata size equals to the Protection Information size, the protection information is stripped or inserted by the controller."
Currently NVMe supports 8 and 16 byte size of Protection Information. So, use pi_size instead of 8 byte.

nvme: check MD size with PI size when PRACT set to 1

---

fabrics.c
subprojects/libnvme.wrap

There are several  places to lookup the default hostnqn/hostid. Add a helper which implements a canonical way to do this.
Fixes: #https://github.com/linux-nvme/nvme-cli/issues/1956
Depends: https://github.com/linux-nvme/libnvme/pull/857

Use libnvme helper to retrieve hostnqn/hostid

---

.github/workflows/appimage.yml
meson.build
scripts/build.sh

The github checkout action is trying to be smart and breaks `git describe` in the process. Checkout the complete history so that we can do a `git describe`. Maybe there is a better strategy to get an usable git version string into the build. But for the time being, let's do the simplest thing and clone the complete repo.
Fixes: #2410

Add correct git version to AppImage

---

.github/workflows/appimage.yml

There is no point in using 3rd party actions for downloading the artifacts. Let's use the official one.

build: use official download action

---

plugins/wdc/wdc-nvme.c
plugins/wdc/wdc-nvme.h

Add OCP 2.5 fields
Create common functions to get and parse the
different variations of the C0 log page.

wdc: Update and refactor the C0h log page parsing

---

util/cleanup.h

`cleanup_nvme_root()` is checking whether the passed pointer is non-NULL, but since the pointer is to a local variable, this will always be true. Therefore, remove the check and always call `nvme_free_tree()`.

util: remove unnecessary NULL check in cleanup_nvme_root()

---

fabrics.c

`_discover_from_json_config_file()` takes a `nvme_subsystem_t` argument but doesn't use it.
Drop the unnecessary argument.
Fixes: b3b9963396c5 (`fabrics: refactore discover from json config`)

fabrics: remove unused _discover_from_json_config_file() argument

---

nvme-print-json.c
nvme-print-stdout.c

As per TP4104, added print for two new fields for HMB feature HMNARE (Host Memory Non-operational Access Restriction Enable) and HMNAR (Host Memory Non-operational Access Restricted) with 1 bit each. Bit 1 is not used for Get Feature command and will be 0. And added print for HMBR field in stdout_id_ctrl_ctratt.
Reviewed-by: Mohit Kapoor <mohit.kap@samsung.com>

nvme-print: Added print for two new fields for HMB feature

---

nvme.c

The NVME_NS_FLBAS_HIGHER/LOWER_MASK is used to get the format index value from Formatted LBA Size (FLBAS) field of Identify Namespace Data Structure. But, We are not getting the proper lbafu value while using the same macro on user passed format index value. So, use the proper mask to get the correct lbafu value.

nvme: use proper mask to get correct lbafu value

---

nvme.c

The value of NVME_FEAT_FID_TIMESTAMP cannot be set to 0 through 'set-feature -f 0xe -v 0'
Using argconfig_parse_seen() can fix this issue

nvme: use argconfig_parse_seen to check the parameter

---

Documentation/nvme-ocp-set-error-injection.txt
completions/_nvme
completions/bash-nvme-completion.sh
plugins/ocp/ocp-nvme.c
plugins/ocp/ocp-nvme.h

The command injects error conditions.

ocp: add set-error-injection command

---

plugins/virtium/virtium-nvme.c

On recent Ubuntu Oracular (24.10) builders, -Wincompatible-pointer-types will cause build errors (see [nvme-cli 2.9.1-1ubuntu1 build failure on armhf](https://launchpadlibrarian.net/740677619/buildlog_ubuntu-oracular-armhf.nvme-cli_2.9.1-1ubuntu1_BUILDING.txt.gz).
In the vtview_log structs, `time_t` should be used for any `time_stamp` values instead of `long.` This ensures correct builds on 32-bit architectures even with 64-bit `time_t` (e.g. armhf on Ubuntu).

plugins/virtium: use time_t for time_stamp values

---

fabrics.c
nvme.c

Many nvme commands such as discover, connect, connect-all, etc. simply return to the prompt without printing any useful error message when the respective nvme driver modules are not loaded in the kernel. This is because nothing gets printed when nvme_scan_topology() returns an ENOENT due to missing nvme system files stemming from not loading the appropriate nvme modules. Fix the same.

fabrics: update printing an error for ENOENT too

---

nvme-print-stdout.c

Refer to FDP Events Set Feature Data Structure:
the number of FDP Event Types is only Dword11 bits [23:16].
the buffer only contains FDP Event Type.
The value of mem_buf is incorrect:
the pointer 'set_feat_event' should be converted to 'unsigned char *' first

nvme-print-stdout: fix persistent-event-log set feature event output

---

nvme.c

The APIs may not set errno set errno to 0 before the device open.

nvme: return ret error value to open device if errno not set

---

nvme.c

Newer kernels enable the lockdown feature when secure boot is enabled. This feature also prevents the register mapping into userspace. Thus it is not enough to have CONFIG_IO_STRICT_DEVMEM disabled. Extend the message with the hint also to disable secure boot.
Fixes: #2420

nvme: extend help message when mmap regs fails

---

fabrics.c
util/cleanup.h

valgrinds reports that the nvme_ctrl_t is leaked in the connect command. Let's introduced a new cleanup helper for this.

fabrics: do not leak nvme_ctrl_t object on connect

---

plugins/sed/sedopal_cmd.c

TCG SED features have variable sizes, so the code needs to use stored length to move the offset for the next feature. Otherwise, it checks the code at the wrong offset.

sed: Fix parsing of Discovery0 features

---

plugins/dapustor/dapustor-nvme.c
plugins/dapustor/dapustor-nvme.h
plugins/meson.build

Add the DapuStor plugin to support the retrieval and display of the Vendor Specific SMART logs:
Additional SMART log page (0xCA)
Extended Additional SMART log page (0xCB)
After the command `nvme dapustor smart-log-add` is executed,
the information in the following format will be returned:
```
key                               normalized raw
program_fail_count              : 100%       0
erase_fail_count                : 100%       0
wear_leveling                   : 100%       min: 3, max: 4, avg: 3
end_to_end_error_detection_count: 100%       0
crc_error_count                 : 100%       0
timed_workload_media_wear       : 100%       0.000%
timed_workload_host_reads       : 100%       100%
timed_workload_timer            : 100%       0 min
thermal_throttle_status         : 100% …
```

plugins: Add a new DapuStor plugin and the smart-log-add command

---

nvme-print-stdout.c
subprojects/libnvme.wrap

As per TP4167, added print for a new field CSER (Command Submission
and Execution Relaxations) [15:14] added in Commands Supported and
Effects Data Structure.
Signed-off-by: Nitin Sao <nitin.sao@samsung.com>
Reviewed-by: Mohit Kapoor <mohit.kap@samsung.com>

nvme-print-stdout: Added print for new field CSER (TP4167)

---

Documentation/cmd-plugins.txt
Documentation/meson.build
Documentation/nvme-dapustor-smart-log-add.txt
completions/bash-nvme-completion.sh
plugins/dapustor/dapustor-nvme.c

Extended Additional SMART log is optional.
If the collection fails, the command dose not stop.
Add the manual of dapustor plugin.
*.1 and *.html can be generated automatically,
so I only added the nvme-dapustor-smart-log-add.txt file.
Update tab completion.

plugins/dapustor: dapustor smart-log-add update

---

nvme-print-json.c
nvme-print-stdout.c
subprojects/libnvme.wrap

Use the Completion Condition enum for LBA Status Descriptor.
Also, modified the print statement of Completion Condition.

nvme-print: use Completion Condition enum

---

nvme-print.c

Previously used LC_ALL so not checked correctly if LC_MEASUREMENT set.

nvme-print: use LC_MEASUREMENT to check fahrenheit temperature

---

plugins/wdc/wdc-nvme.c
plugins/wdc/wdc-nvme.h

Support for a new form factor (EDSFF E3.S) of the SN-861
drive was added to the wdc plugin code.

wdc: Add Support for new SN-861 PCI device id

---

plugins/wdc/wdc-nvme.c
plugins/wdc/wdc-nvme.h

Running nvme wdc vs-nand-stats will change the values of the user data fields
depending on output format used. In regular stdout, the ordering is TLC min,
TLC Max, SLC Min, SLC Max. However in json, the values get reassigned, what
was SLC Min in stdout will become TLC >
Regular format (TLC Min, TLC Max, SLC Min, SLC Max)
[root@ /tmp/]# nvme wdc vs-nand-stats /dev/nvme0n1 | grep User\ Data
User Data Erase Counts - TLC Min 169
User Data Erase Counts - TLC Max 310
User Data Erase Counts - SLC Min 10719
User Data Erase Counts - SLC Max 11676
Json format (SLC Min, SLC Max, TLC Min, TLC Max)
[root@ /tmp/]# nvme wdc vs-nand-stats /dev/nvme0n1 -o json | grep User\ Data
"User Data Erase Counts - SLC Min" : 169,
"User Data Erase Counts - SLC Max" : 310,
"User Data Erase Counts - TLC Min" : 10719, …

 plugins/wdc: fix json output for vs-nand-stats

---

plugins/solidigm/solidigm-internal-logs.c

Fixing generation of CNS 11h identify namespace data structure generation for each allocated namespace instead of attached namespace.

fixing CNS 11h to generate identify per allocated namespace.

---

nvme-print-stdout.c
nvme-print.c

Minor textual and formatting changes to the error-log output.

nvme-print: sanitize error-log output

---

nvme-print-stdout.c
nvme-print.h

To reduce the repeated print code for arrays.

nvme-print-stdout: add print_array function

---

nvme.c

Treat nvme_insert_tls_key_versioned() return value of zero as errors too.

nvme: update nvme_insert_tls_key_versioned() return handling

---

plugins/ocp/ocp-nvme.c

The value not set but checked the ret variable after the call.

ocp: fix to set return value to get c9 log page data

---

nvme-print-json.c

This is to delete the free function call.

nvme-print-json: use _cleanup_free_

---

nvme.c

This is to delete the hardcoded values.

nvme: use NVME_GET_FEATURES_SEL_SUPPORTED definition

---

fabrics.c

Config JSON file handling is currently broken due to an incorrect access filename check. Fix it.

fabrics: fix incorrect access filename check

---

nvme-print-json.c
nvme-print.h

Some additinal functions introduced and fix obj_add_uint_0nx error.

nvme-print-json: extern json object add functions

---

nvme.c
subprojects/libnvme.wrap

Use the macro instead of comparing the long filed value definition.

nvme: use NVME_CHECK() to check get features select field value

---

plugins/ocp/ocp-hardware-component-log.c

Previously the NULL pointer is set incorrectly.

ocp: fix to set log data pointer allocated

---

nvme-print-stdout.c

This is to reduce the hard coded value usage.

nvme-print-stdout: use NVME_CTRL_OAES definitions

---

Documentation/nvme-get-feature.txt
completions/_nvme
completions/bash-nvme-completion.sh
nvme-print.c
nvme.c
nvme.h

These changes are to replace the hardcoded SEL values.

nvme: use NVME_GET_FEATURES_SEL definitions

---

nvme-print-json.c
nvme-print-stdout.c

Convert the status and phase tag fields to native byte order at first.

nvme-print: fix error information log page endianness error

---

nvme.c

The changes for create-ns, compare, read and write commands.

nvme: fix to convert metadata size to native byte order

---

nvme.c

Valgrind complained about an "uninitialized value created by a stack allocation" error while running the error-log command. Fix the same.

nvme: fix uninitialized value in error-log

---

nvme-print-stdout.c

The changed-ns-list-log command currently prints nothing for scenarios where there are no changed ns in the log data. Print a meaningful message for the same.

nvme-print-stdout: update changed-ns-list-log output

---

nvme-print-json.c

1. Print the CMBEBS and CMBSWTP register in json format
2. Print the Controller Register values in order based on the offset.

nvme-print-json: print CMBEBS and CMBSWTP in json format

---

plugins/ocp/ocp-nvme.c

Some OCP commands are missing a high-order zero in each byte of the output GUID.
This commit fixes the format specifier for the printf function.

ocp: fix GUID output

---

plugins/ocp/ocp-nvme.c

When the noraml format is specified without -t option to ocp internal-log command, the command ends abnormally with segmentation fault.
This commit fixes the option handling.

ocp: fix option handling in internal-log

---

nvme-print.c
nvme-print.h
nvme.c

Get properties only at offsets that support nvme fabric registers.
Since crto was not found in the nvmeof spec, it is removed.
Also, NSSR is only optional register. If the device is not supported by the optional register, the error is ignored.
Reviewed-by: Steven Seungcheol <sc108.lee@samsung.com>
Signed-off-by: Minsik Jeon <hmi.jeon@samsung.com>

nvme: Support show-regs for nvmeof

---

plugins/wdc/wdc-nvme.c
plugins/wdc/wdc-nvme.h

This commit will add support for the SN51000S drive which includes the following pci device ids:
0x5061, 0x5062, 0x5063.

wdc: Add Support for SN5100S

---

nvme-print-json.c

Update the nvme-id-ctrl JSON verbose output for parity with this command's normal verbose output.

nvme-print-json: update JSON verbose output for nvm-id-ctrl

---

plugins/ocp/ocp-nvme.c

For supporting ocp 2.5 and legacy version
if we want to check the log version,
we need to get DSSD(OCP) Spec version from ocp smart.
example) Latency Monitor (Log Identifier C3h)
OCP 2.0 Log Page version : 0x1
OCP 2.5 Log Page version : 0x4

ocp-nvme: remove ocp log page version checking

---

plugins/ocp/ocp-nvme.c

Datacenter NVMe SSD Specification v2.5
Log Identifier C3h
[447:436] Latency Monitor Debug Telemetry Log Size
This is the number of Dwords in the Latency Monitor Debug Log. This value is in Dwords.
little endian order print
Signed-off-by: Hyuntae Kim <h1219.kim@samsung.com>
This PR based on PR #2527

ocp-nvme: Add LMDATA-37 for Latency Monitor Log

---

plugins/solidigm/solidigm-internal-logs.c
plugins/solidigm/solidigm-nvme.h
plugins/solidigm/solidigm-telemetry.c
plugins/solidigm/solidigm-util.c
plugins/solidigm/solidigm-util.h

Retry to retrieve telemetry with smaller chunk size, because some systems are failing to retrieve telemetry in 256KB chunks.

plugins/solidigm: Automatic retry smaller telemetry chunk size.

---

plugins/sed/sedopal_cmd.c

The existing ioctl to change password only updated the admin1 password. Add using a new ioctl IOC_OPAL_SET_SID_PW to also update the sid password so that sid and admin1 passwords are kept in sync.

plugins/sed: add sid password change

---

plugins/dapustor/dapustor-nvme.c

Output Extended Additional SMART raw binary data if it exists. 
Add the missing 'temp_since_bootup' field for json output.

plugins/dapustor: smart-log-add fix

---

plugins/memblaze/memblaze-nvme.c

plugins/memblaze: fix a wrong id on smart-log-add

---

Documentation/nvme-device-self-test.txt

As a first-time user I was wondering on where to find the `device-self-test` results.
I think adding this information to the `device-self-test` documentation would be quite useful.

doc: show where self-test results can be found

---

nvme-print-stdout.c

NVME_CSI_KV implemented

---

nvme.c
subprojects/libnvme.wrap

Add Enter Media Verification State (EMVS) support to sanitize command.
TP4152 - Post-Sanitize Media Verification 2024.04.01 Ratified.

nvme: add EMVS support to sanitize command

---

nvme-print-stdout.c

Print the newly added VERS bit of SANICAP field in Identify Controller Data Structure. Also, changed the variable names as per spec.

nvme-print-stdout: print VERS bit of SANICAP field

---

plugins/ocp/ocp-fw-activation-history.c
plugins/ocp/ocp-hardware-component-log.h
plugins/ocp/ocp-nvme.c
plugins/ocp/ocp-nvme.h
plugins/ocp/ocp-print-json.c
plugins/ocp/ocp-print-stdout.c
plugins/ocp/ocp-smart-extended-log.c
plugins/ocp/ocp-telemetry-decode.c
plugins/ocp/ocp-telemetry-decode.h

This reduces the duplicated GUID length 16 bytes definitions.

ocp: combine to use GUID length definitions

---

nvme-print-stdout.c
nvme-print.c

Add Sanitize Media Verification Event in Persistent Event Log.
TP4152 - Post-Sanitize Media Verification 2024.04.01 Ratified.

nvme-print: Add Sanitize Media Verification Event in PEL log

---

Documentation/nvme-connect.txt
Documentation/nvme-gen-tls-key.txt
fabrics.c
meson.build
nvme.c
nvmf-autoconnect/udev-rules/70-nvmf-keys.rules.in
subprojects/libnvme.wrap

Extend the ` --tls_key` and `--keyring` argument to accept also configured keys.
Depends on https://github.com/linux-nvme/libnvme/pull/894

Allow connect to use configured TLS keys

---

.github/workflows/run-nightly-tests.yml
tests/nvme_attach_detach_ns_test.py
tests/nvme_compare_test.py
tests/nvme_copy_test.py
tests/nvme_create_max_ns_test.py
tests/nvme_ctrl_reset_test.py
tests/nvme_format_test.py
tests/nvme_get_features_test.py
tests/nvme_get_lba_status_test.py
tests/nvme_lba_status_log_test.py
tests/nvme_smart_log_test.py
tests/nvme_test.py

This PR introduces a GitHub workflow that runs all test cases under the
`tests` directory on real hardware.
In preparation, the existing test cases are fixed, such that the new
`run-tests` workflow completes successfully (see actions on my fork's master
branch).
The infrastructure that provides the self-hosted GitHub runner with real nvme
devices attached to it are provided by Western Digital Corporation.
On a high-level overview, this infrastructure contains multiple storage nodes
that form a Kubernetes cluster. Within this Kubernetes cluster, KubeVirt
virtual machines can be spawned on demand with different hardware
configurations. Those VMs are owned by different users. One user group that
is separated in its own namespace is self-hosted GitHub runners.
The overall goal of this …

Add workflow to run tests on real hardware

---

plugins/ocp/ocp-fw-activation-history.h
plugins/ocp/ocp-print-json.c
plugins/ocp/ocp-print-stdout.c

Fix the entry data fields to little endian format. Basically print functions convert the fields data to cpu format. But still some errors then fixed the print functions also.

ocp: fix firmware activation history entry endian

---

plugins/ocp/ocp-nvme.h
plugins/ocp/ocp-print-json.c

Fix the entry data fields to little endian format. Basically print functions convert the fields data to cpu format. But still some errors then fixed the print json functions also.

ocp: fix TCG configuration log endian

---

plugins/ocp/ocp-nvme.c

Fix the entry data to little endian format.
Also delete to fill the data to 0 since already initialized by 0.

ocp: fix latency monitoring data structure entry endian

---

Documentation/nvme-check-tls-key.txt
nvme.c

`gen-tls-key` has this option, let's also add it to the `check-tls-key` command.

Add  support to append key to keyfile in check-tls-key

---

.github/workflows/coverage.yml

The code coverage action is silently failing partly because the required Codecov token is missing.
Reading the token from the GitHub secrets.
The missing gpg package must be fixed in
https://github.com/linux-nvme/ci-containers.
Furthermore, fail the coverage workflow if the codecov-action errors out.
Please add the `CODECOV_TOKEN` to the GitHub secrets :)

build: Add token for coverage test

---

nvme-print-json.c
nvme-print-stdout.c

Used NVME_GET macro in sanitize log. Also, updated the print statement as per NVM Express Base Specification Revision 2.1.

nvme-print: use NVME_GET in sanitize log

---

plugins/amzn/amzn-nvme.c
plugins/amzn/amzn-nvme.h

this patch adds support to pull stats from amzn ebs nvme devices.

plugins/amzn: add stats support

---

TLS.md

There are couple of step necessary to get TLS working nicely. Document it how this is done.

docs: add howto to setup TLS connections

---

nvme-print.c

LC_MEASUREMENT is a GNU (libc) extension - fall back to LC_ALL if it's not defined.
Fixes build with musl libc

nvme-print: add fallback for non-standard locale category

---

plugins/ocp/ocp-nvme.h
plugins/ocp/ocp-print-json.c
plugins/ocp/ocp-print-stdout.c

ocp-nvme: Add LMDATA-37 for Latency Monitor Log
3cc286067954ebed1e4588989498e6377246f3f0 commit removed

ocp-nvme: Recommit removed patch #2529

---

plugins/ocp/ocp-hardware-component-log.c
plugins/ocp/ocp-print-json.c
plugins/ocp/ocp-print-stdout.c

The display of Hardware Component (Log Identifier C6h) failures to comply with protocol OCP2.5
Issue: https://github.com/linux-nvme/nvme-cli/issues/2566

ocp-nvme: fix the error display of Hardware Component Log

---

nvme.c

Print a helpful success message (under verbose option) for few functions like subsystem_reset(), reset() and ns_rescan().

nvme: update messages for few misc functions

---

plugins/ocp/ocp-nvme.c

4.15.3.1 Error Injection Entry Data Structure
ERRIE-3 Error Injection Type

ocp-nvme: Add Error Injection type from ocp2.6

---

fabrics.c

The nvme dim command returns a zero even for failure scenarios as shown below:
nvme0 DIM register command error. Status:0xffffffff - Operation not supported
echo $?
0
Fix this by ensuring appropriate values are returned for success and failure scenarios. And while at it, remove a couple of superfluous braces too here.

fabrics: update return values for dim

---

nvme-print-stdout.c
subprojects/libnvme.wrap

nvme-print: Add id-ctrl CTRATT.RHII, using enum
use enum nvme_id_ctrl_ctratt to parse values
reorder variable define
rename variables with abbreviation from nvme spec 2.1
build: bump libnvme wrap
To use enum for idctrl CTRATT.RHII

nvme-print: Add id-ctrl CTRATT.RHII

---

nvme-print-stdout.c

Using enums of ANSAN and RGCNS bit for OAES field based on NVM Express Base Specification 2.1.

type: Using enums of ANSAN and RGCNS bit for OAES

---

plugins/ocp/ocp-hardware-component-log.c

The index is required by the OCP specification.

ocp: set UUID index to get hwcomp log

---

nvme-print-stdout.c
subprojects/libnvme.wrap

The fields added by NVM command set specification 1.1.

nvme-print-stdout: add nvm-id-ctrl command VER and LBAMQF fields

---

nvme.c

if rae default is true, it's always true
so it was not possible to issue with RAE=0
If the host is reading the Telemetry Controller-Initiated log page, then the host reads any portion of that log page with the Retain Asynchronous Event bit cleared to ‘0’ to indicate to the controller that the host has completed reading the Telemetry Controller-Initiated log page

nvme: telemetry ctrl-init need to clear RAE

---

nvme-print-stdout.c

Fix the error of the `Arbitration Mechanism Supported`
in the Controller Capabilities field of Controller Properties.
Refer to Section 3.1.4.1 of [NVM Express® Base Specification](https://nvmexpress.org/wp-content/uploads/NVM-Express-Base-Specification-Revision-2.1-2024.08.05-Ratified.pdf), WRRUPC is indicated by bit 0 of AMS

nvme-print: fix Arbitration Mechanism Supported

---

nvme-print-stdout.c
subprojects/libnvme.wrap

Print the newly added MAXWZD and NSZS bits of ONCS field in Identify Controller Data Structure.
TP4160 - WZSL Limit Modification

nvme-print-stdout: print MAXWZD and NSZS bits of ONCS field

---

plugins/ocp/ocp-nvme.c
plugins/ocp/ocp-print-json.c

This PR will take care of fixing the output format for "telemetry-string-log" command in ocp plug in
Fixed the code to handle json output crash and proper display of ASCII Table content
Disabling debug logs output while parsing telemetry-string-log data
Signed-off-by: Karthik Balan [karthik.b82@samsung.com](mailto:karthik.b82@samsung.com),
Reviewed-by: Arunpandian J [arun.j@samsung.com](mailto:arun.j@samsung.com),

plugins/ocp: fix telemetry string log output format

---

nvme.c

nsdescs should point to an allocated memory of size NVME_IDENTIFY_DATA_SIZE bytes, not "sizeof(*void)" bytes.

ns_descs: prevent buffer overrun and memory corruption

---

plugins/ocp/ocp-nvme.h
plugins/ocp/ocp-print-json.c
plugins/ocp/ocp-print-stdout.c

Add Number of Namespace Provisioned Locking Objects Extended(TCGL-23)
remove reserved area prints (Shall be cleared to zero)
reserved area field name modified by byte address

ocp: TCG Configuration Log field added ocp v2.6

---

nvme-print-json.c
nvme-print-stdout.c
nvme-print.c
subprojects/libnvme.wrap

new fields, missing fields print added

print: id-ctrl print updated based on NVMe v2.1

---

.github/workflows/run-nightly-tests.yml
tests/nvme_attach_detach_ns_test.py
tests/nvme_compare_test.py
tests/nvme_copy_test.py
tests/nvme_create_max_ns_test.py
tests/nvme_ctrl_reset_test.py
tests/nvme_dsm_test.py
tests/nvme_flush_test.py
tests/nvme_format_test.py
tests/nvme_fw_log_test.py
tests/nvme_get_features_test.py
tests/nvme_get_lba_status_test.py
tests/nvme_id_ns_test.py
tests/nvme_lba_status_log_test.py
tests/nvme_smart_log_test.py
tests/nvme_test.py
tests/nvme_test_io.py
tests/nvme_verify_test.py
tests/nvme_writeuncor_test.py
tests/nvme_writezeros_test.py

This PR introduces various improvements to the python test cases.
Before merging this commit, we would need a new self-hosted GitHub runner
instance assigned to this repository, as the device clean up routine is now
handled by the runner instance on the `ACTIONS_RUNNER_HOOK_JOB_COMPLETED`. 
The new self-hosted runner should be created and assigned to this repository via
a different channel, as this requires a token exchange.

tests: various improvements

---

fabrics.c
nbft.c

In case of a connection failure of any SSNS records that are not marked as 'unavailable', report proper error code so that nvme-cli callers may retry the operation.
The semantics of most functions is to return 0 zero for success and negative errno numbers in case of an error.

nbft: Report proper error codes from discover_from_nbft()

---

Documentation/nvme-ocp-internal-log.txt
completions/_nvme
plugins/ocp/ocp-nvme.c
plugins/ocp/ocp-telemetry-decode.h

Since the type none value never set by the command handling.

ocp: delete internal-log command telemetry type none value definition

---

plugins/sed/sed.c
plugins/sed/sedopal_cmd.c
plugins/sed/sedopal_cmd.h

By default 'sed initialize' will set the entire disk to read/write locked, ie no access is possible. That is all fine if the BIOS supports TCG Opal, as then the BIOS can unlock the drive before access. But for BIOS _not_ supporting TCG Opal this results in an inaccessible drive, and requires the user to use a different drive to boot and unlock the SED device.
This patch adds a flag '--read-only' to 'nvme sed initlialize' such that the 'read-lock enable' flag is not set for the locking range, and the device continues to be readable by the BIOS for booting.

sed: add '--read-only' to 'sed initialize'

---

Documentation/nvme-write-zeroes.txt
completions/_nvme
completions/bash-nvme-completion.sh

Add Namespace Zeroes (NSZ) option of Write Zeroes command.

doc: Add write zeroes command namespace-zeroes option

---

nvme.c

Since only json print codes work with the json-c library.

nvme: disable output-format option json value without json-c

---

plugins/amzn/amzn-nvme.c
plugins/meson.build

amzn: enable amzn-nvme.c build without json-c dependencies checking

---

plugins/meson.build

dell plugin does not use json so no need to check the build dependency.

dell: build plugin not depended on json without json

---

plugins/meson.build

fdp plugin does not use json so no need to check the build dependency.

fdp: build plugin not depended on json without json

---

plugins/huawei/huawei-nvme.c
plugins/meson.build

huawei: enable huawei-nvme.c build without json-c dependencies checking

---

plugins/intel/intel-nvme.c
plugins/meson.build

intel: enable intel-nvme.c build without json-c dependencies checking

---

plugins/meson.build
plugins/micron/micron-nvme.c

micron: enable micron-nvme.c build without json-c dependencies checking

---

plugins/scaleflux/sfx-nvme.c
plugins/scaleflux/sfx-nvme.h
plugins/scaleflux/sfx-types.h

Refactoring to have an sfx-types.h and sfx-nvme.h
Adding an equivalent to sfx-status into sfx nvme-cli plugin JSON and normal prints working
Added drive lifetime WAF in sfx status output
Co-authored-by: Ben Reese <5884008+benreese0@users.noreply.github.com>
Co-authored-by: Jayden Stenfort <127808534+A-Fellow-Comrade@users.noreply.github.com>

Plugin: Updating ScaleFlux Plugin

---

Documentation/nvme-ocp-smart-add-log.txt
plugins/ocp/ocp-print-json.c
plugins/ocp/ocp-print-stdout.c
plugins/ocp/ocp-print.c
plugins/ocp/ocp-print.h
plugins/ocp/ocp-smart-extended-log.c

The current OCP JSON format for the SMART extended log page is not condusive to metric collection via tools like Prometheus. So we add a new output mode that uses all lower case and underscores (instead of spaces). This should help with metric collection. At the same time we clean up some of the field names. We add a new argument (--output-format-version) to allow us to select which output version we want. Documentation updated to reflect this change and mark this as experimental.
Fixes #2577.

ocp-nvme: Add a different formatting for JSON output

---

plugins/lm/lm-nvme.c
plugins/lm/lm-nvme.h
plugins/lm/lm-print-binary.c
plugins/lm/lm-print-json.c
plugins/lm/lm-print-stdout.c
plugins/lm/lm-print.c
plugins/lm/lm-print.h
plugins/lm/meson.build
plugins/meson.build

Implementation of TP 4159 PCIe Infrastructure for Live Migration plugin. Includes command support for Track Send, Migration Receive, Migration Send, and Controller Data Queue; Identify Controller LM related fields; Bash and ZSH completions.
Changes are isolated to the User Data Migration subset, with Track Memory functionality deferred to a future commit.
[TP4159 PCIe Infrastructure for Live Migration 2024.07.30 Ratified.pdf](https://github.com/user-attachments/files/17682852/TP4159.PCIe.Infrastructure.for.Live.Migration.2024.07.30.Ratified.pdf)

nvme: Live Migration

---

plugins/ocp/ocp-nvme.c
plugins/ocp/ocp-utils.c
plugins/ocp/ocp-utils.h

The index is required by the OCP specification.

ocp: add ocp_get_log_simple() to set UUID index

---

plugins/amzn/amzn-nvme.c

Use flags instead of cfg.output_format.

amzn: avoid sprinkling ifdefs and use flags

---

plugins/dapustor/dapustor-nvme.c
plugins/intel/intel-nvme.c
plugins/scaleflux/sfx-nvme.c
plugins/ssstc/ssstc-nvme.c
util/argconfig.h

This is to not need ugly ifdefs everywhere.

plugins: introduce OPT_FLAG_JSON for command option json

---

plugins/meson.build
plugins/nbft/nbft-plugin.c
plugins/netapp/netapp-nvme.c

nbft: enable nbft-plugin.c build without json-c dependencies checking

---

plugins/dapustor/dapustor-nvme.c
plugins/intel/intel-nvme.c
plugins/meson.build
plugins/micron/micron-nvme.c
plugins/netapp/netapp-nvme.c
plugins/scaleflux/sfx-nvme.c
plugins/seagate/seagate-nvme.c
plugins/ssstc/ssstc-nvme.c
util/json.h

scaleflux: enable sfx-nvme.c build without json-c dependencies checking

---

nvme-print-json.c

Use libnvme register definitions instead of the shift operator.

nvme-print-json: update register print code to use libnvme definition

---

nvme.c

Previously used incorrectly NVME_GET() but not shifted the masked values.

nvme: fix to use NVME_VAL() for CQ entry status field filter

---

nvme-print-json.c
nvme-print.h
nvme.h
plugins/ocp/ocp-fw-activation-history.h
plugins/ocp/ocp-print-json.c
plugins/ocp/ocp-print-stdout.c
util/json.c
util/json.h
util/types.c
util/types.h

Since currently mixed to use them in ocp-print-json.c then unify.

ocp: replace to use json_object_* macros to obj_* macros

---

plugins/ocp/ocp-nvme.h
plugins/ocp/ocp-telemetry-decode.c
plugins/ocp/ocp-telemetry-decode.h

The OCP 2.5 Telemetry log statistics parsing code was not checking for the end of the stats data and therefore getting stuck in an infinite while loop.
Also added code to parse out the statistic specific data for the Max Die, Max NAND Channel, and Min NAND Channel Bad Block.

ocp: Fixes for OCP 2.5 Telemetry Stats Parsing

---

plugins/ocp/ocp-print-json.c
plugins/ocp/ocp-print-stdout.c
plugins/ocp/ocp-print.c
plugins/ocp/ocp-print.h
plugins/ocp/ocp-smart-extended-log.c
plugins/ocp/ocp-smart-extended-log.h

printed log tested (same), except below
Remove wrong duplicated prints from stdout
NVMe base errata version
NVMe command set errata version

plugins/ocp: Use structure for ocp smart log

---

nvme-print-stdout.c
nvme.c

Add the new Self-test Code (SCT) Host-Initiated Refresh operation support to Device Self-test command.
Also, add it in the Device Self-test Log Page.
TP4058 - Environmental Extremes Management.

nvme: add the new Self-test Code of Device Self-test command

---

nvme-print-stdout.c

Add human readable output for DSTO field of Identify Controller Data Structure.

nvme-print-stdout: add human readable output for DSTO field

---

nvme-print-stdout.c

Still needed to add some remaining definitions in libnvme.

nvme-print-stdout: use NVME_CTRL_OACS definitions

---

nvme.c
util/argconfig.c
util/argconfig.h

Since IO commands rejected by the chardev if more than one namespace.

nvme: use blkdev for direct if namespace-id specified

---

nvme.c

A controller that uses a 128-bit Host Identifier may result in the "nvme resv-report" command failing with a "Host Identifier Inconsistent Format" error that suggests the "simultaneous use of 64-bit and 128-bit Host Identifier values on different controllers".
This error can be avoided if the "--eds" option is used, to request the extended data structure.  However, the controller's ctratt value indicates whether the Host Identifier is 64 bits or 128 bits. Therefore, check the ctratt flag, and set eds to true if the controller indicates a 128-bit Host Identifier.

nvme: set eds to true if controller supports 128 bit hostid

---

nvmf-autoconnect/udev-rules/70-nvmf-keys.rules.in

Append nvme to @SYSCONFDIR@ in udev rule.
I'd think the TLS keyfile should be located at /etc/nvme/tls-keys and not just /etc/tls-keys.

nvmf-keys: udev rule should be using /etc/nvme

---

plugins/ocp/ocp-telemetry-decode.c
plugins/ocp/ocp-telemetry-decode.h

Lookup ascii string in VU Event Identifier String Table for vendor unique event classes. Fix not looking up spec-defined statistic id name. Fix typo ('static' => 'statistic').

ocp-telemetry-decode: fix ascii string lookup

---

fabrics.c

There is limited usability in specifying both -n and -d, so make both exclusive.

fabrics: make 'disconnect' accepting only -n or -d

---

plugins/solidigm/solidigm-internal-logs.c
plugins/solidigm/solidigm-nvme.h
plugins/solidigm/solidigm-telemetry/config.c

Replace snprintf with asprintf
Telemetry null check

Solidigm change snprintf to asprintf

---

tests/nvme_test.py

The attach operation takes a bit of time and is asynchronous, thus we should monitor if the block device appears for a period, before returning an error.
#2668

tests: monitor /dev for new nvme block device

---

nvmf-autoconnect/udev-rules/71-nvmf-netapp.rules.in

The queue_depth based iopolicy suits ONTAP NVMe controllers better. So switch to the same.

udev-rules-ontap: switch to queue-depth iopolicy

---

util/utils.c

The fixed 256-byte description_str will overflow for any reasonably sized data_size >= 128.
Max data_size is for OCP VU Event Data is 0xFF Dwords, so the buffer should be at least 1020 bytes + 1 for null. 1024 seems like a nice number for OCP.
Reported-by: Nate Thornton <n.thornton@samsung.com>
Fixes: https://github.com/linux-nvme/nvme-cli/issues/2686

plugins/ocp: fix telemetry parser buffer overflow

---

Documentation/nvme-attach-ns.txt
nvme.c

Also updating the documentation.

nvme: change attach-ns to error out if wrong device given

---

nvme-wrap.c
subprojects/libnvme.wrap

Since the libnvme-mi missed to add but will be added then use it.

nvme-wrap: use rotational media information log libnvme-mi API

---

Documentation/nvme-dispersed-ns-participating-nss-log.txt
completions/_nvme
completions/bash-nvme-completion.sh
nvme-builtin.h
nvme-print-binary.c
nvme-print-json.c
nvme-print-stdout.c
nvme-print.c
nvme-print.h
nvme-wrap.c
nvme-wrap.h
nvme.c

Since added the NVMe 2.1 log page.

nvme: add dispersed-ns-participating-nss-log command

---

nvme.c
util/logging.h

Do not clutter the info message level with debug information.

nvme: do not output debug infos on info level

---

.github/workflows/run-nightly-tests.yml
nvme.c
util/argconfig.c
util/argconfig.h

These changes broke the nightly CI runs. We were unable to figure out in time what it causes the fail, thus revert these changes.
Introduced here with #2665 to address #2662
Fixes: #2668

Revert attach/detach command line interface changes

---

nvme.c

The nvme JSON outputs now print everything verbose. But this was missed out for the get-feature command, so fix the same here.

nvme: make get-feature JSON output print everything

---

nvme.c

Several commands such as nvme get-feature, get-property, id_iocs, etc. don't check for a valid output format unlike other nvme commands. Fix the same.

nvme: check for valid output format

---

nvme-print-json.c
nvme-print-stdout.c

Print the new fields of I/O Command Set Specific Identify Controller Data Structure based on
NVM Command Set Specification 1.1.

nvme-print: print new fields of nvm_id_ctrl

---

plugins/ocp/ocp-telemetry-decode.c
plugins/ocp/ocp-telemetry-decode.h

Updated the Telemetry Structure and Enum to support the OCP 2.6 spec
Reviewed-by: Karthik Balan <karthik.b82@samsung.com>
Reviewed-by: Arunpandian J <arun.j@samsung.com>

plugins/ocp: Added OCP 2.6 telemetry support

---

nvme-wrap.c

Since the len parameter should be moved before the log parameter.

nvme-wrap: fix get_log_reachability_associations parameters order

---

completions/_nvme
completions/bash-nvme-completion.sh

Fixed syntax error on zsh auto-completion

completions: Added fdp feature auto-completion.

---

nvme-print-json.c
nvme-print-stdout.c

Print the fields of Host Behavior Support feature (FID - 16h).
NVM Express Base Specification 2.1

nvme-print: print Host Behavior Support feature fields

---

Documentation/nvme-host-discovery-log.txt
completions/_nvme
completions/bash-nvme-completion.sh
nvme-builtin.h
nvme-print-binary.c
nvme-print-json.c
nvme-print-stdout.c
nvme-print.c
nvme-print.h
nvme-wrap.c
nvme-wrap.h
nvme.c
subprojects/libnvme.wrap

Since added the NVMe 2.1 log page.

nvme: add host-discovery-log command

---

Documentation/nvme-create-ns.txt
nvme.c

When the device supports the namespace granularity feature, update the alignment requirements accordingly. Because this is likely to change the capacity of the namespace also issue a info what is going to happen.
Fixes: #2721

nvme: enforce ns granularity on ns create

---

plugins/sed/sed.c
plugins/sed/sedopal_cmd.c
plugins/sed/sedopal_cmd.h
plugins/sed/sedopal_spec.h

Added ability to discover and print details of all specified level 0 features.

sed: extended discovery feature code printing

---

plugins/micron/micron-nvme.c

Add missing newline to error for cards that don't support the vs-drive-info command.

micron: Add missing newline

---

Makefile

This pull request simply updates the meson syntax for some of the existing targets and provides a few additional targets as follows:
- For the "install" target, use "--skip-subprojects" so that only nvme-cli (and not the subprojects) get installed.
- For the "purge" target, add "meson subprojects purge".
- Added "update-subprojects" target
- Added "test-strict" target. This is to limit testing to nvme-cli and not all the subprojects.

Makefile: Add new targets and update meson command syntax

---

nvme-print-json.c
nvme-print-stdout.c

Print the newly added fields of Asynchronous Event Configuration feature (FID - 0Bh)
NVM Express Base Specification 2.1.

nvme-print: print new fields of Asynchronous Event Configuration

---

plugins/sed/sed.c
plugins/sed/sedopal_cmd.c
plugins/sed/sedopal_cmd.h

Improve quality of error messages but including context and locking state.

sed: improved contextual error messages

---

Documentation/nvme-get-reg.txt
Documentation/nvme-set-reg.txt
nvme.c

Below commands that use mmap_registers failed since a31081a3fa14 (v2.9)
nvme show-regs /dev/nvme0n1
nvme effects-log /dev/nvme0n1

nvme: allow mmap_registers from block device

---

plugins/wdc/wdc-utils.c

FreeBSD 15 and newer finally has the timezone variable (prior it that was a compat function leftover from 4BSD). Older versions are still supported. Both have tm_gmoff, which I've always preferred for better portability.
I also considered dropping the defined(glibc), but wasn't sure how many other targets there are these days and thought this would be better. I really didn't want any FreeBSD ifdefs, but I don't know how to avoid this.

wdc: On FreeBSD, get the timezone the same as with real glibc

---

Documentation/cmd-plugins.txt
Documentation/meson.build
Documentation/nvme-sed-discover.txt
Documentation/nvme-sed-initialize.txt
Documentation/nvme-sed-lock.txt
Documentation/nvme-sed-password.txt
Documentation/nvme-sed-revert.txt
Documentation/nvme-sed-unlock.txt

man pages for SED plugin commands

sed: add SED man pages

---

plugins/netapp/netapp-nvme.c

Display the ONTAP subsystem name too in the verbose output.

netapp-ontapdev: add subsysname to the verbose output

---

plugins/lm/lm-nvme.c

Forward the user-provided 'numd' value from the command-line options to the underlying nvme_lm_migration_recv library function call.
The `lm_migration_recv` function parsed the `--numd` option but failed to pass the value (`cfg.numd`) when calling the library function `nvme_lm_migration_recv`.
The library function `nvme_lm_migration_recv` requires this value to set command parameters (CDW15) and calculate the expected data transfer length. [libnvme/src/nvme/ioctl.c at master · linux-nvme/libnvme](https://github.com/linux-nvme/libnvme/blob/master/src/nvme/ioctl.c#L2406)

plugins/lm: Pass numd option to nvme_lm_migration_recv

---

plugins/ocp/ocp-nvme.c

Reduce duplicated string definitions.

ocp: replace no-uuid option help string to use no_uuid variable

---

plugins/ocp/ocp-nvme.h
plugins/ocp/ocp-telemetry-decode.c
util/utils.c

The function print_formatted_var_size_str (in util/utils.c) which is used to print the telemetry statistics additional data had a string array (used for printing out the data) with a hard coded length of 1024 chars.  The Stats data with 80 DW's of data would exceed the size of that array.  Therefore, the code was changed to allocate a buffer large enough to contain the full string data.

OCP Telemetry Data Statistics Parsing Fix

---

plugins/netapp/netapp-nvme.c

Display the subsysname in the regular output as well.

netapp-ontapdev: add subsysname to regular output

---

plugins/solidigm/solidigm-nvme.h
plugins/solidigm/solidigm-smart.c

Broke down additional SMART PLL Lock Loss field into separate counters.

plugins/solidigm: Updated SMART PLL Lock Loss counters field

---

plugins/lm/lm-nvme.c
subprojects/libnvme.wrap

Changed the command dword reference in the sequence indicator (seqind) help text from CDW11 to CDW10. This aligns with the spec.
In the spec, `mos` field is at bits 31:16 of CDW10, and `seqind` is at bits 01:00 of `mos`, which gives us the final location of `(CDW10[17:16])`.
Also changed the macro used for setting the sequence indicator bits in the `mos` field from LM_MIGRATION_SEND_MOS to LM_SEQIND.

plugins/lm: Refine Sequence Indicator description and macro usage

---

plugins/sed/sed.c
plugins/sed/sedopal_cmd.c

Use context to print better error messages for common revert and password errors.

sed: better error messages for revert and password

---

plugins/ocp/ocp-telemetry-decode.c
plugins/ocp/ocp-telemetry-decode.h

The Statistics Snapshot FIFO Event is in a slightly different format from the other FIFO Events.  These changes are required for the correct parsing of the statistics snapshot event.

ocp: Fix Parsing of Statistics Snapshot FIFO Event

---

meson.build
nvme.spec.in
nvmf-autoconnect/udev-rules/71-nvmf-vastdata.rules.in

Vast Data array supports NVMe-oF block access, and it prefers the host to use round-robin path selection for performance benefits.
In addition, disable the ctrl_loss_tmo in case of prolonged maintenance operations.

udev: Add custom udev rule for the Vast Data Block array

---

plugins/wdc/wdc-nvme.c
plugins/wdc/wdc-nvme.h
plugins/wdc/wdc-utils.c
plugins/wdc/wdc-utils.h

Add checking of the supoorted log pages (log id 0) for currently supported log pages.  The previous code was only checking a vendor specific log page for this info. Also the uuid index value was added so the supported log pages can be checked for a specific uuid.

wdc:  Fixed check for supported log pages

---

plugin.c

As the help short option parsed -h by argconfig so follow plugin also.

plugin: translate -h into commands

---

plugins/feat/feat-nvme.c
plugins/feat/feat-nvme.h

This is for HCTM feature to get and set thermal management temperature.

feat: add hctm command

---

plugins/wdc/wdc-nvme.c
plugins/wdc/wdc-utils.c
plugins/wdc/wdc-utils.h

Some minor code improvements in wdc plugin.

wdc: plugin code cleanups

---

nvme-print.c
nvme.c
nvme.h
util/logging.c
util/logging.h

The option is to show command instead of sending.
@ikegami-t

nvme: add dry-run NVME_ARGS default option

---

nvme.c
plugin.c
plugin.h

This is to find easily the sub-commands name from the help list.

nvme-builtin: sort command list as alphabetical order

---

plugins/feat/feat-nvme.c

Since almost duplicated and fix to handle buffer data also.

feat: combine get functions

---

nvme.c

Since already checked in nvme_get_feature_length() calling. Deleted before by the commit: 18de3a6d but then incorrectly added.
Fixes: b1567901d9b7 ("nvme: split get_feature to get multiple feature ids")

nvme: delete host identifier feature length checking

---

Documentation/nvme-admin-passthru.txt
Documentation/nvme-io-passthru.txt
Documentation/nvme-nvme-mi-recv.txt
Documentation/nvme-nvme-mi-send.txt
nvme.c

The shorthand -o change for --output from --opcode before. Then the default opcode value zero used incorrectly if the -o used.

nvme: make --opcode argument mandatory

---

plugins/feat/feat-nvme.c
plugins/feat/feat-nvme.h

Includes save and sel options for all nvme feat plugin commands.

feat: add FEAT_ARGS to use instead of NVME_ARGS

---

fabrics.c
nvme.c
subprojects/libnvme.wrap
util/logging.c
util/meson.build
util/sighdl.c
util/sighdl.h

The kernel started to return EAGAIN and EINTR. It is quiet likely that this was possible before but it happened not so often. Thus for users of nvme-cli it is a behavior change.
The first attempt was to handle this in libnvme itself. But it turns out we can't just blindly retry. It is necessary to check if the user has pressed Ctrl-C to terminate the program. Adding a signal handler inside the library is a no go. Thus add the retry logic to nvme-cli itself.
Fixes: https://github.com/linux-nvme/nvme-cli/issues/2760 https://github.com/linux-nvme/nvme-cli/issues/2781 https://github.com/linux-nvme/nvme-cli/pull/2775
depends on https://github.com/linux-nvme/libnvme/pull/1010

nvme: retry commands on EAGAIN and EINTR (v2)

---

.github/workflows/run-nightly-tests.yml

We are now running the self-hosted testing infrastructure with the help of GitHub's ARC. This allows us to be more considerate with the available resources as the VMs are now spawned on demand with the requested kernel.
For now, we have to print KERNEL_VERSION in a previous job to pick up the correct kernel. This should be fixed in the future by contributing a labeling mechanism to GitHub's ARC.

CI: move to self-hosted GitHub ARC infrastructure

---

fabrics.c
util/logging.c

The previous 'fix' was not really working because the error status is in errno not in the return value.
fixes: #2801

Handle add ctrl errors

---

Documentation/nvme-dir-send.txt

Since actually the option is not used by the command.

doc: update dir-send command documentation on -H

---

scripts/build.sh

Since currently the error output by the muon build.
error invalid option: 'docs=disabled'

build: delete docs=disabled muon build option

---

util/logging.c

Only supported for the NVMe-MI message type NVMe admin command.

logging: add nvme_mi_submit entry and exit functions

---

util/sighdl.c

The header file required for the muon build on CentOS.

sighdl: include stddef header file

---

plugins/ocp/ocp-print-stdout.c

Fixed OCP Latency Monitor stdout spacing in column header
version 2.11
fix

Fixed OCP Latency Monitor stdout spacing in column header

---

nvme-print-json.c

The parameters VSIL and EL order was incorrect so reverse the order.

nvme-print-json: reverse pel power on reset parameter order error

---

Makefile

Autotools and many handwritten Makefiles only provide a 'clean' target, which typically removes everything. However, the 'clean' target here does not fully do this, leaving some artifacts behind after it is run. This leads to confusion when, after cleaning, the build step still doesn't reflect configuration changes such as newly installed libraries.
Therefore, update the 'clean' target to behave like the 'purge' step.

build: make 'clean' target an alias for 'purge'

---

plugins/wdc/wdc-nvme.c

Change the string length to 41 from 40 for the warning below.
[165/166] linking unit/test-uint128
../plugins/wdc/wdc-nvme.c: In function 'wdc_print_unsupported_reqs_log_json': ../plugins/wdc/wdc-nvme.c:5381:71: warning: 'sprintf' may write a terminating nul past the end of the destination [-Wformat-overflow=]
sprintf((char *)unsup_req_list_str, "Unsupported Requirement List %d", j);
^
../plugins/wdc/wdc-nvme.c:5381:3: note: 'sprintf' output between 31 and 41 bytes into a destination of size 40
sprintf((char *)unsup_req_list_str, "Unsupported Requirement List %d", j);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

wdc: fix muon build warning

---

meson.build
plugins/wdc/wdc-utils.c

Set the variable if the struct tm have a tm_gmtoff field.

wdc: use HAVE_TM_GMTOFF meson configuration variable

---

plugins/wdc/wdc-nvme.c
plugins/wdc/wdc-nvme.h

Add support for the clear-assert-dump wdc plugin command to SNTMP drives

wdc: Add support for clear-assert-dump to SNTMP drives

---

plugins/feat/feat-nvme.c
plugins/feat/feat-nvme.h

Also fixed temp-thresh command string and added get-feature print.

feat: add arbitration command

---

nvme.c

Binary format is not implemented for list-ctrl, so limit output to normal and json formats only.

list-ctrl: limit to JSON and normal output

---

logging.c
nvme.h

Allow the user to disable the retry logic. There are use cases in testing where the simple retry logic should not be applied, e.g. sending out admin passthru commands while a reset is issued. The admin passthru commands should just fail in this case.
Fixes #2846

nvme: add command line argument to disable retries

---

Documentation/nvme-fw-download.txt

Add a comment why fw-download is depending on huge TBL and what do to when the allocation fails.
fixes:  #2848

doc: add note about huge TLB when using fw-download

---

nvme-print-json.c
nvme-print-stdout.c
nvme.c

Depends on: https://github.com/linux-nvme/libnvme/pull/1022
Fixes: https://github.com/linux-nvme/nvme-cli/issues/2830

Fix list-subsys filtering

---

plugins/wdc/wdc-nvme.c
plugins/wdc/wdc-nvme.h

The return value of this function represents what commands are supported by the target, so returning a -1 here incorrectly enables all capability checks. Instead, this updates the behavior to just log the error and continue to report the actual device capabilities.
Reviewed-by: Jeffrey Lien <jeff.lien@sandisk.com>

wdc: invalid customer ID fix

---

.github/workflows/run-nightly-tests.yml

Previously we used two independent ARC deployments where one compiled/announced the kernel and the second spun up a VM that executed our tests.
This setup caused concurrency related issues in other projects that use the same infrastructure. An ARC can assign work to any available resource (in our case the VM) and thus we could not guaranty which kernel was used for testing.
We are now using a single ARC that can build and spawn a VM. To spawn and run commands in the VM we are now using the kubevirt-action defined in linux-blktests/blktests-ci.

CI: adopt kubevirt-action for self-hosted ARC

---

Documentation/nvme-get-feature.txt
Documentation/nvme-set-feature.txt
nvme.c

The feature-id parameter can be set the symbolic names also.

nvme: add get and set feature commands symbolic names

---

nvme-print-stdout.c
nvme-print.c
nvme-print.h
nvme.c

Still only supported partial log pages to output.

nvme-print-stdout: add get log command verbose outputs

---

nvme-print-stdout.c

Added as get log command verbose outputs.

nvme-print-stdout: add ANA, PEL and LBA status log verbose outputs

---

nvme-print-json.c
nvme-print-stdout.c
plugins/micron/micron-nvme.c
plugins/micron/micron-nvme.h

-Fixed segmentation fault issue in JSON output format for VS Eye data
-Added support to hex dump VS Eye data in both normal and JSON formats
-This enables customers to decode the raw eye chart data if needed
-Ensured compatibility with existing d() and obj_d() hex dump utilities
-Addressed all the review comments that are given as part of pull request #2828

nvme: plot eye chart data and hex dumping VS eye data

---

nvme-print-stdout.c

-Printable Eye message key missing for eye plotting
-Removed malloc for vsdata as memory cleanup taken care by caller

nvme: Added message key for printable eye in normal format

---

plugins/sandisk/sandisk-nvme.c
plugins/sandisk/sandisk-nvme.h

This change will check if data area 4 is supported and set the etdas bit in feature id 0x16 if supported.

Add support for retrieving data area 4

---

plugins/sandisk/sandisk-nvme.h
plugins/wdc/wdc-nvme.c
plugins/wdc/wdc-nvme.h

This change will check for the Sandisk UUID first and fallback to the WDC UUID if the Sandisk UUID is not found.

sndk: Add support for the Sandisk UUID

---

nvme.c

The `parse_and_open()` function uses `OPT_BYTE` to parse the feature_id and sel options. This means it writes a single byte to the memory locations for `feature_id` and `sel` in the `feat_cfg` struct.
However, these fields were declared as `enum`, which typically has the size of an `int`. On big-endian architectures, writing a single byte to the address of an `int` modifies the most significant byte, resulting in an incorrect value being read. This caused the `get-feature` command to fail. The command only worked on little-endian systems.
Fix the issue by changing the type for `feature_id` and `sel` to `__u8`. This ensures the fields are treated as single bytes, guaranteeing correct behavior on all architectures.

nvme: Fix get-feature on big-endian systems

---

Documentation/nvme-solidigm-vs-internal-log.txt
completions/_nvme
plugins/solidigm/solidigm-internal-logs.c
plugins/solidigm/solidigm-nvme.h

EXTENDED option to extract logs that slows things down during vs-internal-log.

plugin/solidigm: Added EXTENDED vs-internal-log option.

---

nvme.c
subprojects/libnvme.wrap

When retrieving telemetry log data area 4, the etdas bit in the host behavior changed feature must be set. This commit will change the code to use new functions added to libnvme to set and clear that bit before and after retrieving data area 4.

nvme: Enable retrieving telemetry log data area 4

---

plugins/ocp/ocp-nvme.h
plugins/ocp/ocp-print-json.c

The parsing of the ocp 2.5 telemetry string log fails with buffer overflow errors.  The overflows are caused by arrays that aren't long enough to contain the data once converted to strings.  This change will fix the overflow failures.

ocp: Fix telemetry string log json format parsing

---

Documentation/nvme-ocp-internal-log.txt
plugins/ocp/ocp-nvme.c
plugins/ocp/ocp-nvme.h
plugins/ocp/ocp-telemetry-decode.c
plugins/ocp/ocp-telemetry-decode.h

The current ocp internal-log command will only retrieve up to data area 3.  This change will enable retrieving of all 4 telemetry log data areas.
It will also refactor the code used to save off the 2 files collected:  telemetry log and string log along with the 1 generated file:  the parsed da 1 and 2 data.
Swap -o and -f on output-format and output-file parameters.

Enable data area 4 internal-log ocp plugin command

---

fabrics.c

Currently a user can use the `nvme discover` to connect to a discovery controller. This then allows the user to use a --persistent argument to maintain a persistent or not. This correctly sets a KATO and works as expected.
A user can also perform `nvme connect` to connect to a discovery controller. In this case a KATO is not specified to the kernel (KATO of 0) yet we are actually creating a persistent connection. This results in the nvme target constantly generating keep-alive timeouts as a Linux target sets a KATO of 120 seconds (as allowed by the spec) yet we have no keep-alive timer running for the persistent connection.
This patch checks if we are connecting to a discovery controller and if we are sets the persistent option to true. We know it's a persistent connection because we are …

fabrics: set persistent when connecting to a discovery controller

---

Documentation/nvme-check-tls-key.txt
Documentation/nvme-gen-tls-key.txt
nvme.c
subprojects/libnvme.wrap

Add a '--compat' flag for 'gen-tls-key' and 'check-tls-key' to allow interoperability with older implementations.

nvme: add --compat flag for 'gen-tls-key' and 'check-tls-key'

---

nvme-print-binary.c
nvme-print-json.c
nvme-print-stdout.c
nvme-print.c
nvme-print.h
nvme.c
nvme.h
util/meson.build
util/table.c
util/table.h

https://lore.kernel.org/all/20250904175654.1183750-1-nilay@linux.ibm.com

nvme-cli: enhance the visibility of multipath using show-topology command

---

.github/workflows/run-nightly-tests.yml

Improving nightly blktests by:
1. Remove any preinstalled nvme-cli and libnvme packages
2. Output nvme-cli version information to artifacts
3. Run only tests that utilized nvme-cli

CI: improve nightly blktests

---

plugins/ibm/ibm-nvme.c
plugins/ibm/ibm-nvme.h
plugins/meson.build

The patch implements two functions in ibm vendor specific extensions:
- Display IBM additional smart log information
- Display IBM VPD information

Add IBM specific plugins code
