nvme.c

nvme_firmware_log_page.frs has 7 entries, not 8.

Fix over-long loop in show_fw_log().

---

Makefile

struct nvme_command contains an anonymous union (a GNU extension).

Compile with -std=gnu99.

---

Documentation/nvme-id-ctrl.1
Documentation/nvme-id-ctrl.txt
Documentation/nvme-id-ns.1
Documentation/nvme-id-ns.txt
nvme.c

This patch adds a human readable decode for the various bitfields in id-ctrl and id-ns, and also formats the LBA Format decode in id-ns. It is enabled with the -H switch.

Human-readable decode for id-ctrl and id-ns

---

nvme.c

The index used to determine lba value takes into account the entire FLBAS field.  Bit 4 determines whether an extended or separate buffer is used to send metadata and if set to 1'b, throws off the index value.  Masked out the top 4 bits to only take into account Bits 3:0 which indicate the LBA format type used.
Without this change any device with bit 4 set will not show usage/capacity correctly in the list output.

Fix to determine initial value for lba in print_list_item

---

Makefile

The changes enable the packaging mechanism to tune the compiler and linker flags, install files to requested folders and install documentation separately.
I can provide the rest of the deb package files if there is interest in them.

prepare Makefile for easier packaging

---

nvme.c

Some NVMe drives take longer than 60 seconds to perform a format on a
namespace. Increase the timeout for the format to 120 seconds.

Allow longer timeout for format

---

completions/README
completions/_nvme
completions/bash-nvme-completion.sh

Adds completions/_nvme and completions/bash-nvme-completion.sh, which (when located appropriately on your system) enable tabbing autocompletions for NVMe commands and sub-commands. Options to sub-commands are also printed, after a sub-command is specified.

[v2] add bash + zsh autocompletions

---

nvme.c

On a firmware activate, some drives require a reset before the new
firmware can be used. Such drives return a status 0x10b to the activate
request.
Rather than treat this as an error, tell this user the activation was
successful, but a reset is required.

Allow for firmware activation that needs a reset

---

linux/nvme.h
nvme.c

- Using --human-readable (or -H) option with the get-feature command will decode
the fields of the specified FID.

Added a decode option for all mandatory and optional Feature Identifiers fields

---

nvme.c

- Changed default NSID to 1 in get-feature function.   Some features require a valid NSID (i.e. lba range type)
- Corrected IEEE byte order in id-ctrl output
- Fixed format of LBA range output
- Added description (Decode) to the attributes field in LBA range output
- Changed default NSID to 0xffffffff in get_log (Matches help documentation now)

 Change default NSID in get-feature function. Fixed format of LBA range output

---

src/argconfig.c
src/argconfig.h
src/suffix.c
src/suffix.h

As noted in discussed in issue #30 and PR #32, there have been legal concerns of linking Apache licensed code with GPLv2 code. This change modifies the license of the code originating from libargconfig.
All of the copyright holders (including myself and PMC Sierra represented by Stephen Bates <Stephen.Bates@pmcs.com>) have signed off on this change.

Modified the license of the code pulled from libargconfig to be GPLv2

---

Makefile
common.c
common.h
nvme.c

The printing output should be identical. The id structure
printing functions can be more or less used by lsnvme.
Signed-off-by: Patrick McCormick <patrick.m.mccormick@intel.com>

Factor out ID printing code into common.c

---

Makefile

Don't link with unused libs: -lm, -lpthread
Don't hardcode in 64 bit compile, this will break cross compilation
Put preprocessor flags in CPPFLAGS
Add to existing variables instead of var = $var pattern
Signed-off-by: Patrick McCormick <patrick.m.mccormick@intel.com>

Makefile cleanup.

---

Makefile
debian/control
debian/rules

* The changes from 3686759 make the debian/rules a lot simpler.
* Fix so ld doesn't leave a.out turds.
* Add dist-orig make target that creates a reproducible orig.tar.gz.
A reproducible source archive is a first step towards reproducible
builds.
* Fix typo in debian package description.
* Add dist and pkg to the PHONY targets.

Improve debian package build process.

---

common.c
nvme.c

- Display temperature sensors data using smart-log command
- Removed code that truncated the last byte of fr, mn, sn in id-ctrl.
Matched string format with list command

Added decoding of temp sensors to the SMART log page (02h)

---

nvme.c

In submit_io  buffers "buffer and mbuffer" allocated are not getting freed at the fail cases and hence might lead to memory leak 
This patch free the buffer before the return of the function .

Fixing Memory Leak

---

common.c

This improve the output of id-ctrl on my Samsung 950 to:
ps    0 : mp:6.50W operational enlat:5 exlat:5 rrt:0 rrl:0
rwt:0 rwl:0 idle_power:- active_power:-
ps    1 : mp:5.80W operational enlat:30 exlat:30 rrt:1 rrl:1
rwt:1 rwl:1 idle_power:- active_power:-
ps    2 : mp:3.60W operational enlat:100 exlat:100 rrt:2 rrl:2
rwt:2 rwl:2 idle_power:- active_power:-
ps    3 : mp:0.0700W non-operational enlat:500 exlat:5000 rrt:3 rrl:3
rwt:3 rwl:3 idle_power:- active_power:-
ps    4 : mp:0.0050W non-operational enlat:2000 exlat:22000 rrt:4 rrl:4
rwt:4 rwl:4 idle_power:- active_power:-
This will increase my inspiration level to teach Linux about power saving.

Decode power states more readably

---

nvme.c

I used to see:
Node             Model                Version  Namepace Usage                      Format           FW Rev  
---------------- -------------------- -------- -------- -------------------------- ---------------- --------
/dev/nvme0n1     Samsung SSD 950 PRO  1.1      1         73.12  GB / 512.11  GB    512   B +  0 B   1B0QBXX7
/dev/nvme0n1p1   Samsung SSD 950 PRO  1.1      1         73.12  GB / 512.11  GB    512   B +  0 B   1B0QBXX7
/dev/nvme0n1p2   Samsung SSD 950 PRO  1.1      1         73.12  GB / 512.11  GB    512   B +  0 B   1B0QBXX7
/dev/nvme0n1p3   Samsung SSD 950 PRO  1.1      1         73.12  GB / 512.11  GB    512   B +  0 B   1B0QBXX7
Now I see:
Node             Model                Version  Namepace Usage                      Format           FW Rev …

Restrict 'nvme list' to disks, i.e. exclude partitions

---

src/argconfig.c

This patch helps to avoid memory leak in the function argconfig_parse_subopt_string of argconfig.c
file

Memory leak fix at argconfig_parse_subopt_string of argconfig

---

README.md

I've included two command examples, i hope that's not too much bloat. normally people will try to avoid using udev, but it's not really necessary either assuming everyone can ls /dev/nvme* ;)

Add starter doc for AlpineLinux

---

nvme.c

I noticed the format command help text text was a little off from the spec and the range checking was also not respecting the spec defined values.  Updated the help text and option range checking.  Please let me know if these changes are out of line.

Fixed option checking for format to match NVMe spec limits.

---

nvme.c

Fix to release the allocated "buffer" memory on the failure of "mbuffer" allocation before returning

Fix Memory leak on fail case of mbuffer

---

nvme-print.c

Commit 82c4d1fff8db ("Use endian host conversions for endian type data")
introduced a typo. This is a fix for that.
Signed-off-by: Stanislav Kholmanskikh <stanislav.kholmanskikh@oracle.com>

nvme-print: fix a typo

---

nvme-print.c
nvme.c

According to the NVMe Specification, there is an error when display Model Number.
In addition, currently it does not display the info of Serial Number, so add it.

Fix the bug of Model Number and display the info of Serial Number

---

nvme.c

The data_size and metadata_size fields in the config struct are declared as
__u32, but should actually be __u64. The current types cause issues in the
argument parsing functions depending on machine architecture and endianness. In
ppc64, using __u32 causes "data size not provided" errors due to the way writes
are being done by argconfig_parse() at src/argconfig.c. Changing the types to
__u64 should fix this behaviour and is in accordance to the CFG_LONG_SUFFIX
flag.
Signed-off-by: Heitor Ricardo Alves de Siqueira <halves@linux.vnet.ibm.com>

fix data_size and metadata_size types

---

nvme-ioctl.c
nvme-ioctl.h
nvme.c

This kills off the old nvme_get_log() and rename
nvme_log() to nvme_get_log().
Signed-off-by: Ming Lin <ming.l@ssi.samsung.com>

Rename nvme_log() to nvme_get_log()

---

completions/bash-nvme-completion.sh

Remove shebang line from bash completion file as rpmlint on openSUSE/SLE
complains about a script ment to be sourced not executed containing a shebang
line.
[   38s] nvme-cli.x86_64: W: sourced-script-with-shebang /etc/bash_completion.d/nvme /usr/bin/env
[   38s] This text file contains a shebang, but is meant to be sourced, not executed.
Signed-off-by: Johannes Thumshirn <jthumshirn@suse.de>

bash completion: Remove shebang line

---

nvme.c

Add check_arg_dev() to check if a device name has been provided
and use this in show_registers to avoid the following segfault:
Segmentation fault (core dumped)
Signed-off-by: Colin Ian King <colin.king@canonical.com>

Fix segmentation fault using nvme show-regs with no device name

---

Documentation/nvme-lnvm-create.txt
Documentation/nvme-lnvm-diag-bbtbl.txt
Documentation/nvme-lnvm-diag-set-bbtbl.txt
Documentation/nvme-lnvm-factory.txt
Documentation/nvme-lnvm-id-ns.txt
Documentation/nvme-lnvm-info.txt
Documentation/nvme-lnvm-init.txt
Documentation/nvme-lnvm-list.txt
Documentation/nvme-lnvm-remove.txt
Makefile
linux/lightnvm.h
nvme-lightnvm.c
nvme-lightnvm.h
nvme.c

Add support for identify geometry, get bad block interface and
administration interface for LightNVM. This patch adds the following
commands:
- (lnvm-id-ns) Identify geometry of a LightNVM device.
- (lnvm-diag-bbtbl) Retrieve bad block table from LightNVM device.
- (lnvm-info) Get information about modules loaded, and available
devices.
- (lnvm-init) Initialize LightNVM device with a media manager.
- (lnvm-create) Create targets on top of registered devices.
- (lnvm-remove) Remove a registered target.
- (lnvm-factory) Factory initialize a LightNVM device.
Signed-off-by: Matias Bjørling <m@bjorling.me>

Add LightNVM adminstration and diagnose support

---

nvme.c

building with clang scan-build picked up a memory leak:
nvme.c:2176:3: warning: Potential leak of memory pointed to by 'mbuffer'
fprintf(stderr, "failed to read data buffer from input file\n");
^~~~~~~
instead of returning, jump to free_and_return which performs the
correct cleanup.  Also fix the indentation of the return at the end of
the function.
Signed-off-by: Colin Ian King <colin.king@canonical.com>

 Fix leak of mbuffer on error exit path

---

nvme.c

- Enhanced both the reset and subsystem-reset functions to return an error message on older kernels with no ioctl support.  Current behavior is to return general_help() message with no indication that the ioctl call failed.
- Added "zeroes based" to the block count documentation for write-uncorr and write-zeroes

Enhanced both reset and subsystem-reset to return an error message

---

nvme-print.c
nvme.c

- In nvme_feature_show_fields:  Correct printed output of Arbitration Burst.  Per spec, if value is 7, print "No limit"
- In set_feature print actual value used for set-feature command instead of result

Minor fixes to printed output of set/get feature

---

lnvm-nvme.c

Hi Keith,
I found a couple parsing-bugs in the LightNVM plugin, here are a couple of patches fixing them.
Thank you
Signed-off-by: Simon A. F. Lund <slund@cnexlabs.com>
Reviewed-by: Matias Bjørling <matias@cnexlabs.com>

plugin-lnvm: Fixes to argument parsing.

---

nvme.c

Display NVMe command status in both string and hex format for write_uncorr and write_zeroes commands

Display NVMe command status in both string and hex format (write_zeroes & write_uncor)

---

Makefile
fabrics.c
intel-nvme.c

There are current 2 issues on version 0.8 that blocks it to be integrated in Debian.
1) The package is not compiling in all architectures anymore
2) The package is using the legacy directory for bash completion
Both of them are fixed in this pull request.

Fixes to make version 0.8 available in Debian

---

Documentation/nvme-list.1
Documentation/nvme-list.html
Documentation/nvme-list.txt
README.md
nvme.c

The previous list command required libudev. We can accomplish the same
thing with standard functions, and in the future remove the libudev
dependency

nvme-cli: Implement list command that doesn't rely on libudev

---

fabrics.c
nvme.h

There are a couple fields defined in the tool not-in-sync with the NVMe-over-Fabrics standard, so getting that up to par.
I also style-cleaned up the entire fabrics.c file based on checkpatch.pl tool.

getting discovery fields up-to-par with standard

---

nvme.c

Hi, I believe this fixes a couple of typos in nvme dsm

fix dsm short-form switches for ctx-attrs and cdw11

---

json.c

No one who uses the JSON API is checking for return values.
Instead of littering the json code with if-else chains,
we will error on any memory allocation failure. Even though
incredibly unlikely malloc will return NULL it's easier to
check for it and print an error instead of faulting.

json: Print to stderr and abort() instead of returning NULL and faulting

---

nvme-print.c

Fixes:
==15224==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7fffffffcf55 at pc 0x7ffff6ecb9f5 bp 0x7fffffffcd80 sp 0x7fffffffc510
WRITE of size 22 at 0x7fffffffcf55 thread T0
#0 0x7ffff6ecb9f4 in __interceptor_vsprintf (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x619f4)
#1 0x7ffff6ecbcc9 in __interceptor_sprintf (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x61cc9)
#2 0x420357 in json_nvme_id_ctrl /home/sbauer/nvme_code/nvme-cli/nvme-print.c:1266
#3 0x4072f1 in __id_ctrl /home/sbauer/nvme_code/nvme-cli/nvme.c:935
#4 0x40742f in id_ctrl /home/sbauer/nvme_code/nvme-cli/nvme.c:950
#5 0x42fa63 in handle_plugin /home/sbauer/nvme_code/nvme-cli/plugin.c:140
#6 0x410c46 in main /home/sbauer/nvme_code/nvme-cli/nvme.c:2729
#7 0x7ffff6ac182f in __libc_start_main …

Fix stack-based overflow in id-ctrl json output.

---

fabrics.c

To make things a tad easier for human usage understanding,
refine the single letter short option of 'r' to 'c' for the
'connect' command as 'r' is already used by 'discover'.
Signed-off-by: Jay Freyensee <james_p_freyensee@linux.intel.com>
Signed-off-by: Christoph Hellwig <hch@lst.de>
Signed-off-by: Sagi Grimberg <sagi@grimberg.me>

nvme-cli: change 'r' to 'c' for connect flag

---

scripts/latency

This patch adds functionality to
*) Calculate and display the average latency
*) Make sure count is not 0
Fixes
*) in case of write, grep latency in case of dd command would
always fail. Fixed it.

latency script fixup

---

argconfig.c
fabrics.c
suffix.c

While compiling nvme-cli for ChromeOS, the compiler founds minor issues
in the code:
- unsigned and sizet_t can never be negative.
- use fabs instead of llabs when argument is a double.
Signed-off-by: Gwendal Grignou <gwendal@chromium.org>

Fix compilation errors

---

nvme-print.c

Some fixes for issues prevented the list output's JSON format being parseable in some cases:
* Fix the 'Firmware' field in the JSON output mode possibly reading past the end of the `.fr` field in the `nvme_id_ctrl` struct.
* Print the list as a JSON array of objects (as the "Devices" key of a root JSON object) rather than an object with the product name as the key, to avoid the issue of duplicate keys when two cards have the same product name
* Fix some issues right-trimming field whitespace

JSON format fixes

---

Makefile

The way compiler settings are appended to CFLAGS breaks custom flags
that people are using to build.  So if someone does:
$ export CFLAGS='-O0 -ggdb'
$ make
The build will force -O2 instead.
Shift these defaults into a default setting rather than always appending.
Signed-off-by: Mike Frysinger <vapier@gentoo.org>

change default CFLAGS settings into the default

---

Documentation/Makefile

The current Documentation/Makefile always sets PREFIX to /usr/local.
If the parent Makefile sets it to something else, then it still gets
clobbered.  Change the Makefile to look like the parent and allow the
cascading logic to work.
Signed-off-by: Mike Frysinger <vapier@gentoo.org>

Documentation: allow parent PREFIX to override

---

nvme.h

Fix the following error when building with musl libc:
nvme.h:136:2: error: implicit declaration of function 'le16toh'
[-Werror=implicit-function-declaration]
le16toh((__force __u16)(x))
^
Signed-off-by: Natanael Copa <ncopa@alpinelinux.org>

Include endian.h for byte/host order functions

---

nvme.c

When sel == 3, the controller returns capabilities in the completion
entry and does not produce a feature value blob.  Stop allocating
space for the blob and displaying it -- the result is garbage.
Signed-off-by: Andy Lutomirski <luto@kernel.org>

get-features: Don't try to read the data buffer for sel == 3

---

Makefile

Currently it is not recommend to put the bash completion files inside
/etc, but on the new /usr/share/bash-completion, as stated in :
https://lintian.debian.org/tags/package-installs-into-obsolete-dir.html
https://bugs.debian.org/776954
Signed-off-by: Breno Leitao <breno.leitao@gmail.com>

Moving the bash completion files to the standard

---

lnvm-nvme.c

The default behavior when initializing a target without lun end and
begin is to use only the first lun of the OCSSD. Going forward, the
user shall either explicit specific the begin and end, or if not defined
for kernel 4.11 and newer, the full SSD is initialized.
Signed-off-by: Matias Bjørling <matias@cnexlabs.com>

lightnvm: default to -1 on lun begin and end

---

linux/nvme.h

The enum values for QPTYPE, PRTYPE and CMS are off by 1 from the
values defined in figure 42 of the NVM Express over Fabrics 1.0:
http://www.nvmexpress.org/wp-content/uploads/NVMe_over_Fabrics_1_0_Gold_20160605-1.pdf
Fix our enums to match the final spec.
The matching fix to the kernel include has been submitted as well:
http://lists.infradead.org/pipermail/linux-nvme/2017-March/008612.html
Signed-off-by: Roland Dreier <roland@purestorage.com>

<linux/nvme.h>: Correct NVMF enum values to match NVMe-oF rev 1.0

---

fabrics.c

The TRSVCID and TRADDR fields in the discovery log page are defined
as ASCII strings, which according to the NVMe standard means they
should be space-padded rather than NUL-terminated.
The current nvme-cli code will print all the spaces and possibly some
garbage from the next field.  For example this causes "connect-all"
to write strings that get rejected with "malformed IP address passed."
Fix this by only writing the contents of these fields until the first
space character.
Signed-off-by: Roland Dreier <roland@purestorage.com>

fabrics: Handle space-padded TRSVCID and TRADDR fields

---

nvme.c

We forgot to actually read the data from the disk into the buffer.
Reported-by: Thomas Bowen <thomas.t.bowen@intel.com>

Fixup Security send/recv to read data from disk

---

nvme.spec.in

The build would otherwise fail with:
```
Processing files: nvme-1.2-1.el7.centos.x86_64
error: File not found: /root/rpmbuild/BUILDROOT/nvme-1.2-1.el7.centos.x86_64/etc/bash_completion.d/nvme
```

Unbreak RPM build after bash completion files were moved in 7e4c7596

---

fabrics.c

I was a bit surprised that running:
nvme disconnect -d /dev/nvme1
actually disconnected nvme0 and I could never disconnect nvme1. Turns
out the code was not expecting a full path and silently used instance
zero if it failed to parse any arguments.
This patch fixes it so that it ignores any path component and fails if
sscanf doesn't match any items.

fabrics: Fix disconnect_by_device from disconnecting instance 0 on error

---

nvme.c

Security Receive sent the wrong pointer, specifically a pointer to a
stack location. When using the Dump raw command we would dump stack
contents, not the buffer received from the controller.
Signed-off-by: Thomas Bowen <thomas.r.bowen@intel.com>
Signed-off-by: Scott Bauer <Scott.Bauer@intel.com>

Fixed problem with security-recv binary output not working correctly

---

linux/lightnvm.h
lnvm-nvme.c
nvme-lightnvm.c
nvme-lightnvm.h

Allow to drop the target recovery mechanism when creating a target in
order to start in factory mode. This facilitates development and makes
it possible to evaluate an OCSSD in different states.
Signed-off-by: Javier González <javier@cnexlabs.com>

lightnvm: allow to init target on factory mode

---

huawei-nvme.c
nvme.c

While compiling using gcc 7.1.1 I ran into compile errors, eg.
``` C
nvme.c: In function ‘scan_dev_filter.part.5’:
nvme.c:797:35: error: ‘%s’ directive output may be truncated writing " \
"up to 255 bytes into a region of size 251 [-Werror=format-truncation=]
snprintf(path, sizeof(path), "%s%s", dev, d->d_name);
``` 
This is caused because the buffer on the stack is only 256 bytes and the
dirent.d_name is 256 and the constant string is "/dev/", so  256 + 5,
but I've rounded up to nearest 4/8 byte alignment of 264.
Signed-off-by: Tony Asleson <tasleson@redhat.com>

Fix potential device string truncation

---

nvme-models.c

If a device that is _not_ in pci.ids has its name looked up after a device
that _was_ present in pci.ids, these pointers are still set even though
they've been free'd, and then get passed to snprintf resulting in a
use-after-free.

fix use-after-free in pci.ids parsing

---

Documentation/nvme-discover.1
Documentation/nvme-gen-hostnqn.1
Documentation/nvme-id-ns.1
wdc-nvme.c

Spelling errors were corrected in some documentation files. They were
showing up when trying to run the Lintian tool.
Signed-off-by: Rodrigo R. Galvão <rodrigorosattig@gmail.com>

Fix spelling errors

---

nvme.c

Print error message for "nvme list" command when NVMe device(s)
is not present.

nvme-cli: add error message for nvme list.

---

tests/nvme_create_max_ns_test.py

Fix typo of flbas in nvme_create_max_ns_test

Fix typo of flbas in nvme_create_max_ns_test

---

nvme.c

The current parameter types will cause the sanitize action value to
be set to 0 and "Invalid Sanitize Action" errors.  Setting them to
the correct types resolves the issues.

NVMe-CLI Fix Sanitize Command Parameter Types

---

Makefile

The test to determine whether libuuid is installed uses the host 'ld' utility.
This breaks when cross compiling, since target libraries are often different
than host libraries.
Use $(LD) instead. This allows to easily use the cross compiler linker.
Signed-off-by: Baruch Siach <baruch@tkos.co.il>

Makefile: allow linker override for cross uuid test

---

nvme.c

In case it is a negative value when user has no permisson to open file.
Signed-off-by: Xiao Liang <xiliang@redhat.com>

nvme-cli/list: change fd returned by open operation from unsigned to signed.

---

intel-nvme.c

Fixed get_internal_log to parse the entire nlog and allow selection of specific regions to be parsed.

Fixed get_internal_log

---

nvme.c

C operator precedence puts ternary operator below many arithmetic operators
http://en.cppreference.com/w/c/language/operator_precedence
Without these changes following expression will return 2 instead of expected answer 5
printf("Sum = %d", min(2,3)+max(2,3));

Fixing macro definitions to avoid issues when these are used in expression

---

nvme-print.c

Added the new bit fields for OACS from NVMe rev 1.3
Bit 6: NVMe-MI Send and Receive
Bit 7: Virtualization Management
Bit 8: Doorbell Buffer Config
Size of reserved bits are also reduced to Bits 15:9

new bit fields (6, 7, and 8) for OACS from NVMe rev 1.3

---

nvme-print.c

Added the new bit field for ONCS from NVMe rev 1.3
Bit 6: Timestamp feature
Size of reserved bits are also reduced to Bits 15:7

new bit field (6) to ONCS from NVMe rev 1.3

---

nvme-print.c
nvme.c

Added handling for temperature threshold values below 0C(273K) in human readable option and removed buffer check for human readable output as Temperature threshold feature does not use Memory Buffer for Attributes
Changes to be committed:
modified:   nvme-print.c
modified:   nvme.c

Added handling for temperature threshold values below 0C(273K)

---

README.md

Just updated the Nix package to 1.4 and noticed this list. This'll add install instructions for Nix(OS) if you want. I also noticed that the Alpine Linux install instructions [weren't rendered correctly](https://github.com/linux-nvme/nvme-cli/tree/9c1c0c7f7900642ca64985f1e0609da05c3709a9#alpinelinux) ([new version](https://github.com/primeos/nvme-cli/blob/300104d3be129af7cac1a6f3384c40dd727ee0c0/README.md#alpine-linux)). Feel free to squash the two commits if you prefer only one commit.

README: Add Nix(OS) install instructions and fix some minor Markdown mistakes

---

nvme.c

namespace id's default value is 0 and changed to 15 by get_nsid()
when device is not a block device.
With this change:
`# ./nvme id-ns /dev/nvme0 -n 0`
Error: requesting namespace-id from non-block device
NVMe Status:INVALID_NS(b) **NSID:0**
Without this change:
Missleading output when user passed 0 or 15 as namespace id.
`# nvme id-ns /dev/nvme0`
Error: requesting namespace-id from non-block device
NVMe Status:INVALID_NS(b) **NSID:15**
`# nvme id-ns /dev/nvme0 -n 0`
Error: requesting namespace-id from non-block device
NVMe Status:INVALID_NS(b) **NSID:15**
`# nvme id-ns /dev/nvme0 -n 15`
NVMe Status:INVALID_NS(b) **NSID:15**
Signed-off-by: Xiao Liang <xiliang@redhat.com>

nvme/id-ns: do not try to get namespace id from non-block device.

---

nvme-print.c

`Sec.` is never used anywhere else, bit confusing for end users. (Initially I didn't notice that my Intel 800p module was missing OPAL support.)

Avoid unnecessary abbreviation

---

intel-nvme.c

There is no free 'intel' variable memory even if is is allocated with malloc().

Fix memory leak

---

nvme-print.c

As stated in the title, the request updates the human readable printing to be NVMe 1.3 compliant for the SGLs field in the identify controller command.  There is also a nitpick change included where the alignment of the vendor specific dump was off due to a missing newline character before the dump.

Update human readable for SGLS field in identify controller to NVMe 1.3

---

nvme.c

Internally some people are building with asan which complains
that we're leaking that memory. So we'll fix it for them.

nvme-cli: Fix small mem leak.

---

nvme-print.c
nvme.h

Add print line for Command Specific Information[39:32] in Error
Information Log Entry.

nvme-cli: add print for command specific info field of error log page

---

Documentation/nvme-error-log.1
Documentation/nvme-error-log.html
Documentation/nvme-error-log.txt
nvme-ioctl.c
nvme-ioctl.h
nvme.c

nvme-cli: Remove nsid param in error-log
Namespace Identifier is not needed for error information in get log page command.
Update nvme-error-log.txt documentation also.

nvme-cli: Remove nsid param in error-log

---

nvme-print.c
nvme-print.h
nvme.c

Add support for json output format of sanitize-log command.

nvme-cli: add support for json output format of sanitize-log command

---

nvme-print.c
nvme.h

NVMe 1.3 spec introduced BPS(Boot Partition Support) bit field in CAP of
controller register.
Add this bit field to "struct nvme_bar_cap" by changing
"css_nssrs_dstrd" field to "bps_css_nssrs_dstrd".
Also add a print for BPS bit field to print CAP properly when show-regs
command with human-readable.

nvme-cli: add BPS bit field to CAP controller register

---

Documentation/nvme-intel-smart-log-add.1
Documentation/nvme-intel-smart-log-add.html
Documentation/nvme-intel-smart-log-add.txt

Update smart-log-add command documentation in intel plugin with
output-format parameter description.
In github issue #175, tim-oleksii reported that descriptions of
output-format whose implementation was added in Pull request #178 was
not added in documentation.

nvme-cli: intel: update smart-log-add command documentation

---

linux/lightnvm.h
lnvm-nvme.c
nvme-lightnvm.c
nvme-lightnvm.h

On target creation, allow to define the over-provision (OP). Since OP
area has a direct impact on write amplification, users can optimize the
OCSSD behavior for their workloads.
Support in the kernel has been upstreamed in 4.16
Signed-off-by: Javier González <javier@cnexlabs.com>

lightnvm: enable to set OP on target creation

---

tests/nvme_error_log_test.py
tests/nvme_test.py

Remove nsid parameter in a testcase of error-log subcommand.
This parameter has been removed by a commit 98ffd4b on the master branch
of linux-nvme/nvme-cli.

nvme-cli: tests: remove nsid parameter in a testcase of error-log

---

intel-nvme.c

Add const to descriptions of subcommand option.

nvme-cli: intel: add const to descriptions of subcommand option

---

intel-nvme.c

Make it return negative error value when file open is failed to intel
commands.

nvme-cli: intel: add check for fd after open to intel commands

---

Documentation/nvme-intel-smart-log-add.1
Documentation/nvme-intel-smart-log-add.html
Documentation/nvme-intel-smart-log-add.txt

tim-oleksii has reported that intel smart-log-add help differs from man
page in #260 .
Update man, html, and txt documentation to follow output of below
command.
./nvme intel smart-log-add

nvme-cli: intel: fix smart-log-add documentation

---

tests/nvme_get_features_test.py

Comment and function name typo will directly reflect document which
will be generated by Makefile.
Fix typos like below.
1. Typo in feature lists in the global comment.
2. Mandetory -> Mandatory

nvme-cli: tests: fix typo in get_feature_test

---

lnvm-nvme.c

The return value of argconfig_parse() should be returned if it fails.
Make lnvm commands return when it fails.

nvme-cli: lnvm: Make it return error status when argconfig_parse fails

---

nvme.c

Make it return ENOMEM when malloc of metadat is failed with some error
message.

nvme-cli: add error handling for a failure of malloc

---

nvme.c

Fix memory leak from posix_memalign() without any free.
Minwoo Im (9):
nvme-cli: fix memory leak in list_ctrl()
nvme-cli: fix memory leak in ns_descs()
nvme-cli: fix memory leak in fw_download()
nvme-cli: fix memory leak in set_feature()
nvme-cli: fix memory leak in sec_send()
nvme-cli: fix memory leak in dir_send()
nvme-cli: fix memory leak in sec_recv()
nvme-cli: fix memory leak in dir_receive()
nvme-cli: fix memory leak in passthru()
nvme.c | 63 +++++++++++++++++++++++++++++++++++++++++++++------------------
1 file changed, 45 insertions(+), 18 deletions(-)

nvme-cli: fix memory leak in nvme.c

---

Documentation/nvme-wdc-smart-add-log.1
Documentation/nvme-wdc-smart-add-log.html
Documentation/nvme-wdc-smart-add-log.txt
wdc-nvme.c

Clean up wdc-nvme.c by making few descriptions (const char *).
Also, update document of wdc-smart-add-log.
Minwoo Im (2):
nvme-cli: wdc: add const to descriptions
nvme-cli: wdc: fix mismatch in document for smart-add-log
Documentation/nvme-wdc-smart-add-log.1    |  8 ++++----
Documentation/nvme-wdc-smart-add-log.html | 15 +++++++++------
Documentation/nvme-wdc-smart-add-log.txt  |  4 ++--
wdc-nvme.c                                | 20 ++++++++++----------
4 files changed, 25 insertions(+), 22 deletions(-)

nvme-cli: wdc: update wdc plugin

---

memblaze-nvme.c

Update memblaze plugin with error returning and fix for memory leak
Minwoo Im (2):
nvme-cli: memblaze: fix memory leak in memblaze-nvme.c
nvme-cli: memblaze: add error return after parse_and_open()
memblaze-nvme.c | 6 ++++++
1 file changed, 6 insertions(+)

nvme-cli: memblaze: update memblaze plugin

---

plugin.c
wdc-nvme.c

Signed-off-by: Oleksii Timofieiev <tim.oleksii@gmail.com>

nvme-cli: wdc: Removed superfluous output in WDC plugin

---

nvme-print.c

Add command specific field to json output of error-log command.
This field was added in commit 662c1618 without considering json output
format.
Fixes: 662c1618("nvme-cli: add print for command specific info field of
error log page")

nvme-cli: add command specific field to json output of error-log

---

nvme-ioctl.c

_bpid_ was added as a parameter in commit d52c9988 without any being
used.
Make it have inside of cdw10 before submitting a command.
Fixes: d52c9988 ("nvme-cli: update Firmware Commit with boot partition
feature")

nvme-cli: make it have bpid in cdw10 for fw-commit

---

nvme.c

Fix leaks(a single memory leak, file descriptors leaks) in subcommands
by adding explicit close for opened things.

nvme-cli: fix leaks in subcommands

---

nvme-print.c
nvme-print.h
nvme.c

Code clean-up by moving print-functions for list and list-subsys
commands to nvme-print.c with no functional changes.

nvme-cli: move print-function to nvme-print

---

nvme-ioctl.c
nvme.c

If caller invokes get_nsid() with character device without checking
whether a given device is block device or not, ENOTBLK is returned from
nvme_get_nsid() which is a positive value, so that caller may treat this
value as a valid nsid.
Make it return a negative vaelue with -ENOTBLK and add error checking to
callers.

nvme-cli: make return negative value in nvme_get_nsid() when not blkdev

---

nvme-print.c

Adjust JSON print format according to uint format which has recently been
added with no functional change.

nvme-cli: adjust json print according to uint format

---

nvme-ioctl.c

Update 0x1000 hard coding magic value to NVME_IDENTIFY_DATA_SIZE which
was added in linux-nvme driver commit 0add5e8e588c.

nvme-cli: make it use NVME_IDENTIFY_DATA_SIZE

---

nvme-ioctl.c
nvme-ioctl.h
nvme.c

Add helper function for sanitize command just like other commands with few
error returning from wrong options.

nvme-cli: add helper for sanitize command

---

nvme.c

Sending these changes for review:
1) Fix double free in list_subsys
get_nvme_subsystem_info() deallocates subsys_list_item in case of error.
This hits double free when list_subsys() as well attempts to free it.
Removed deallocation of subsys_list_item from get_nvme_subsystem_info().
2) Log error incase of failure in get_nvme_subsystem_info()
Currently get_nvme_subsystem_info() silently fails in case
of error. This patch logs relevant error message incase of
failure in get_nvme_subsystem_info().
Signed-off-by: Vijay Kumar <vijay.ac.kumar@oracle.com>

Few fix related to 'nvme list-subsys'

---

Makefile

Hello again nvme-cli team,
I'm sending you another pull request, following on from #326. This change causes the toshiba plugin to be included in the makefile rules. Many apologies - it was accidentally missed from the previous pull request.
Thanks and regards,
Andrew Meir

Add toshiba plugin to makefile rules.

---

nvme.c

From f9fa2b9001f1abfb0d2fcb96d3aa8c3de83a7313 Mon Sep 17 00:00:00 2001
From: Minwoo Im <minwoo.im.dev@gmail.com>
Date: Tue, 10 Apr 2018 02:29:47 +0900
Subject: [PATCH 0/2] nvme-cli: fix endurance_log subcommand
This patch set is to fix segmentation fault and the leak of file descriptor in endurance_log subcommand.
Minwoo Im (2):
nvme-cli: fix seg_fault by cmd options in endurance_log
nvme-cli: fix leak in endurance_log command
nvme.c | 8 ++++++--
1 file changed, 6 insertions(+), 2 deletions(-)
-- 
2.7.4

nvme-cli: fix endurance_log subcommand

---

nvme.c

Currently, non-fabrics show-regs subcommand is *not* returning 0 even if it has
successfully read from the bar.  Make it return 0 when successfully done.
Link: #338
Signed-off-by: Minwoo Im \<minwoo.im.dev@gmail.com>

nvme-cli: make it return 0 in case of non-fabric for show-regs

---

nvme.c

fix show command before sending typo to slba (Starting LBA)

nvme-cli: fix show command typo

---

nvme-ioctl.c

nvme-cli currently is printing out the error code via perror when nsid
from the nvme_get_nsid(fd) <= 0.  Once user gives a chrdev node instead of
blkdev node, following "Success" message is being printed-out even it's
a failure case.
Error: requesting namespace-id from non-block device
nvme0: Success
errno will *not* be set in case that blkdev is not given.  So set the
proper errno for this case.  The following message will be nicer than
previous one.
Error: requesting namespace-id from non-block device
nvme0: Block device required
This patch will also fix the return value of this subcommand.  0 will
*not* be given when the subcommand fails.
Signed-off-by: Minwoo Im \<minwoo.im.dev@gmail.com>

nvme-cli: fix perror when blkdev not given when get-ns-id

---

Documentation/nvme-id-nvmset.1
Documentation/nvme-id-nvmset.html
Documentation/nvme-id-nvmset.txt
linux/nvme.h
nvme-builtin.h
nvme-ioctl.c
nvme-ioctl.h
nvme-print.c
nvme-print.h
nvme.c

From 4e48e94751bf85469faff5f45e26f91e438c11a2 Mon Sep 17 00:00:00 2001
From: Minwoo Im \<minwoo.im.dev@gmail.com>
Date: Mon, 16 Apr 2018 03:01:50 +0900
Subject: [PATCH 0/3] nvme-cli: add support for id-nvmset subcmmand
This patchset adds Identify NVM Set List command.
It also updates new fields to Identify Namespace data structure.
Minwoo Im (3):
nvme-cli: add support for id-nvmset subcommand
nvme-cli: update new fields in id-ns subcommand
nvme-cli: update the document for id-nvmset subcommand
Documentation/nvme-id-nvmset.1    | 147 +++++++
Documentation/nvme-id-nvmset.html | 869 ++++++++++++++++++++++++++++++++++++++
Documentation/nvme-id-nvmset.txt  |  78 ++++
linux/nvme.h                      |  24 +-
nvme-builtin.h                    |   1 +
nvme-ioctl.c                      |  13 +- …

nvme-cli: add support for id-nvmset subcmmand

---

linux/nvme.h
nvme-print.c

This adds support for the NVMe revision 1.3 Deallocate Logical Block
Features (DLFEAT) field in the Identify Namespace data structure.
Signed-off-by: Klaus Birkelund Abildgaard Jensen <klaus.jensen@cnexlabs.com>

nvme-cli: add support for DLFEAT

---

nvme-ioctl.c

In the case of 64 bit property, the offset loop variable is advanced correctly only on error. When the call to nvme_property is successful (and thus err == 0) the offset variable is advanced by 4 bytes only.

nvme-ioctl.c : nvme_get_properties(): fix 64bit offset advance

---

Documentation/nvme-get-log.1
Documentation/nvme-get-log.html
Documentation/nvme-get-log.txt
nvme-ioctl.c
nvme-ioctl.h
nvme.c

Currently telemetry-log cannot retain content of corresponding log page as RAE is not set.
This patch adds RAE bit support into routines to retrieve log pages.
Signed-off-by: Alexey Timofeyev <alexey.timofeyev@sk.com>

nvme-cli: add support of RAE

---

nvme-builtin.h
nvme-ioctl.c
nvme-ioctl.h
nvme-print.c
nvme-print.h
nvme.c

We can get all properties with show regs but getting a single property (instead of block of registers) looks more suitable for NVMeOF. When using nvme-cli for QA tests for devices, show regs might not be appropriate in some cases.
Missing doc (txt, man, html) for this command.

Add a single get-property command for NVMeOF.

---

nvme.c

Previously, issuing a command with --dry-run but without
--show-command would actually execute the command
Signed-off-by: Tal Shorer <tal.shorer@gmail.com>

don't execute a command if --dry-run is supplied

---

tests/nvme_create_max_ns_test.py
tests/nvme_test.py

Creating max ns by getting the total nvm capacity, and format.
Thus, the whole capacity is used in nvme_create_max_ns_test

Use tnvmcap register for creating namespace

---

nvme-print.c

Fix the typo like below:
MaximiumLBA -> MaximumLBA
Issue: #396: Typo in nvme list command

nvme-cli: fix typo in json_print_list_items

---

nvme-ioctl.c
nvme.c

changed files:
nvme.c        function list()
nvme-ioctl.c  function nvme_get_nsid() : return -errno if fstat fails
**Before fix:**
Note that "Success" print is because strerror (errno) is called after successful close (errno == 0)
```
/dev/nvme0n2: failed to obtain nvme info: Success    <<<< ERROR
/dev/nvme0n3: failed to obtain nvme info: Success
/dev/nvme0n4: failed to obtain nvme info: Success
/dev/nvme4n1: failed to obtain nvme info: Success
/dev/nvme4n2: failed to obtain nvme info: Success
/dev/nvme4n3: failed to obtain nvme info: Success
/dev/nvme4n4: failed to obtain nvme info: Success
Node             SN                   Model                                    Namespace Usage                      Format           FW Rev  
---------------- -------------------- …
```

nvme list : fix nvme list output if identify failed on device

---

nvme.c

The path is in a char[310], contributing at most 309 chars for the ‘%s’.
‘/subsysnqn’ is a further 10.  Plus one for the NUL.
309 + 10 + 1 = 320 so sspath[319] is too short.

Enlarge local char[] so snprintf(3) can't truncate path.

---

nvme.c

Original
```
Segmentation fault (core dumped)
```
After fix:
```
attach-ns: controller id list is required
```

attach-ns : fix segfault for ctrl list wrong input

---

nvme.spec.in

Build with "make rpm" failed since  bash completion file in "make install"  and in "nvme.spec.in" were not the same.
Fixed the spec.
Also, since uuidgen is provided by "util-linux" package (on RHEL, SUSE and Fedora), I changed the Requires too. Otherwise installation would fail since there is no "uuidgen" package.
Tested build on RHEL 7.4 and Fedora 28.
Tested installation on RHEL 7.4 and Fedora 28.
Note that resuling rpm has file conflicts with vendor "nvme-cli" which must be removed first.

nvme-cli make rpm:  fix bash completion and require in nvme.spec.in

---

fabrics.c
intel-nvme.c
linux/nvme_ioctl.h
memblaze-nvme.c
nvme-ioctl.c
nvme-ioctl.h
nvme-models.c
nvme-print.c
nvme.c
nvme.h
seagate-nvme.c
toshiba-nvme.c
wdc-utils.c
wdc-utils.h

There's a series of commits that fix many Linux-specific idioms where more portable constructs work just as well. It's part of a larger series that ports things to FreeBSD, but the rest of the series aren't ready yet as to complete that port some structural changes will be needed and I've not settled on the proper way to do them. These are needed regardless of any future work, however, and should be generally uncontroversial. It only makes three real code changes: uses the proper unsigned long for the command argument to ioctl where it's passed from function to function, removes a needless const on a char * argument, and gets timezone offsets from standard interfaces rather than glibc specific exported globals. Other than that, I'm just removing needless includes and preferring POSIX …

Portability fixes

---

json.c

I think zero length string is no error. nvmecli have to just display data from ssd.

In json output, if there is zero length string in command return data, it occur allocation failure & abort (cannot display empty value)

---

plugins/micron/micron-nvme.c

Where possible it is best to use the redirections, so that any future usb bridges etc (where the nvme command will have to do translation) will work.

micron-nvme: Replace direct use of ioctl

---

README.md

Fix typo 'akp' to 'apk'.
Signed-off-by: Minwoo Im \<minwoo.im.dev@gmail.com>

nvme-cli: readme: fix typo in Alpine distro support

---

nvme-builtin.h
nvme-ioctl.c
nvme-ioctl.h
nvme.c

Previous feedback, **(http://lists.infradead.org/pipermail/linux-nvme/2018-June/018724.html)**, on the implementation of NVMe 1.3's virtualization feature for nvme-cli requested that the change be tested against a device actually supporting the feature.  This has now been completed internally at Intel, and this pull request merges the previous patch into the latest nvme-cli sources.

nvme-cli: Added support for virtualization-management command

---

README.md

Really small change, but as `yaourt` is now [discontinued](https://wiki.archlinux.org/index.php/AUR_helpers), I think we should encourage installation through the new recommended AUR helper: `yay`.
P.S Great tool :)

README: update Arch Linux install instructions

---

Documentation/nvme-create-ns.txt
Documentation/nvme-format.txt
nvme.c

Similar to #445 however adds the helper to create-ns command instead of format. Allows user to select target block size in a create-ns command instead of requiring FLBAS to be specified directly.

Adding a Format Helper to create-ns

---

nvme-print.c

We accidantly evaluated SHIFT operation before AND
operation which caused wrong values to be printed
using Human Readable output (-H).
Signed-off-by: Roy Shterman <roys@lightbitslabs.com>

nvme-print: Fix evaluation of ctratt on pretty print

---

fabrics.c

Hi,
I'd like to add a very few features to check failure in the middle of the
discovery process.
```
Minwoo Im (2):
fabrics: Return negative errno when asprintf() fails
fabrics: Return negative errno to check remove_ctrl() is failed
fabrics.c | 14 ++++++++------
1 file changed, 8 insertions(+), 6 deletions(-)
```

fabrics: Return negative errno to check failure in discovery

---

common.h
nvme.c
plugins/intel/intel-nvme.c
plugins/micron/micron-nvme.c
plugins/wdc/wdc-nvme.c

Hi,
This patchset cleans-up code quality by removing duplicated macros.
```
Minwoo Im (2):
nvme: Use ARRAY_SIZE() macro in common.h
nvme: Unify min(), max() macro as a common one
common.h                     |  3 +++
nvme.c                       | 11 ++++-------
plugins/intel/intel-nvme.c   |  4 +---
plugins/micron/micron-nvme.c |  3 +--
plugins/wdc/wdc-nvme.c       |  3 +--
5 files changed, 10 insertions(+), 14 deletions(-)
```

nvme: Clean-up duplicated macros

---

Documentation/nvme-show-regs.1
Documentation/nvme-show-regs.html
Documentation/nvme-show-regs.txt
nvme-print.c
nvme-print.h
nvme.c

This patchset introduces --output-format support for show-regs subcommand.
Document will also be upated if merged.
```
Minwoo Im (2):
nvme: Support raw_binary and json format for show-regs
doc: Update show-regs document with output-format
Documentation/nvme-show-regs.1    | 42 ++++++++++++++++++++++++++-----
Documentation/nvme-show-regs.html | 41 ++++++++++++++++++++++++------
Documentation/nvme-show-regs.txt  | 15 +++++++++--
nvme-print.c                      | 42 +++++++++++++++++++++++++++++++
nvme-print.h                      |  1 +
nvme.c                            | 31 ++++++++++++++++++++---
6 files changed, 154 insertions(+), 18 deletions(-)
```

nvme: Support raw_binary and json format for show-regs

---

nvme.c

Hi,
I'd like to propse changes about virt-mgmt subcommand options here.
All the other options for subcommands are lowercase, but virt-mgmt command
has options started with uppercase with long name of it.
I'd like to have a discussion to change it to lowercase because there might
be somebody's already using these options.
Thanks,
```
Minwoo Im (2):
nvme: Simplify description for virt-mgmt
nvme: Simplify virt-mgmt options to lowercase
nvme.c | 37 ++++++++++++++++++-------------------
1 file changed, 18 insertions(+), 19 deletions(-)
```

[RFC] Simplify virt-mgmt subcommand options to lowercase

---

nvme-ioctl.c

```
The given *pbar is allocated inside this function without freeing it
will be freed from the caller in case of show-regs subcommand for NVMe-oF
controller.
If Get Property is failed because it has PCIe transport, then it needs
to be freed here instead of caller.
```

ioctl: Free memory if get_property for fabrics failed

---

tests/nvme_create_max_ns_test.py
tests/nvme_flush_test.py
tests/nvme_format_test.py
tests/nvme_fw_log_test.py
tests/nvme_get_features_test.py
tests/nvme_id_ns_test.py
tests/nvme_test.py
tests/nvme_test_io.py

```
The following issue has been reported that README in "tests" seems not
correct because it will not be able to be invoked in case python3
because print() has to be taken instead of print which had been used for
python2.
Issue !429:
https://github.com/linux-nvme/nvme-cli/issues/429
```

tests: Update print to print() for python3

---

nvme.c
plugin.c

```
When a given string for a subcommand is not valid, we can return EINVAL which
means invalid arguments.  ENOTTY is used to indicate that an invalid IOCTL
number was specified.
```

plugin: Return EINVAL instead of ENOTTY

---

nvme-print.c

Sometimes human-readable id-ctrl output could be confusing, e.g.
```
$ nvme id-ctrl /dev/nvme0
NVME Identify Controller:
vid       : 0x144d
ssvid     : 0x144d
sn        : S3HDNX0K601842
mn        : SAMSUNG MZWLL1T6HEHP-00003
fr        : GPNA5B3Q
rab       : 8
ieee      : 002538
cmic      : 0x3
mdts      : 5
cntlid    : 21
...
```
Here cntlid value is hexdecimal and equals 33, but nothing shows that.
In the same time some other values have 0x prefix. Let's use the prefix
for all hexdecimal values of the output.
Signed-off-by: Alexander Larin <znahar@yandex-team.ru>

Always use 0x prefix for hexdecimal values of id-ctrl output

---

Makefile

Commit 254bcd6b2343 ("Fix CFLAGS parameter") only fixed the problem
if the variable came from the environment, not if it came from the
command line.  Fix it using 'override'.  See the GNU Make manual,
section 6.7 ("Overriding variables") for details.
Signed-off-by: Andy Lutomirski <luto@kernel.org>

Fix passing CFLAGS on the make command line.

---

nvme-ioctl.c

Hi Keith,
The first one needs to be merged to fix what Ken has reported. Also,
the second one will fix the return value of this function in case
get_property_helper() fails after the first time.
Reported from https://github.com/linux-nvme/nvme-cli/pull/471
```
Minwoo Im (2):
ioctl: Fix double-free in a loop of get_property
ioctl: Fix wrong return case of get_property
nvme-ioctl.c | 10 +++++-----
1 file changed, 5 insertions(+), 5 deletions(-)
```
Thanks,

For 1.9/fix double free in a loop

---

nvme-print.c
nvme-print.h
nvme.c

Minor patches are here without any functional changes.  The first one
introduces a common API to print out nvme status in case of error.  The second
makes function which returns string type to have const with it. The third and
fourth make printing nvme status to be in case of return value is positive.
```
Minwoo Im (4):
print: Introduce show_nvme_status to print nvme status
print: Add const to return type of string
get-telemtry-log: Print nvme status in case err > 0
sanitize: Print nvme status in case ret > 0
nvme-print.c |  30 ++++++----
nvme-print.h |   9 +--
nvme.c       | 152 +++++++++++++++++++++------------------------------
3 files changed, 85 insertions(+), 106 deletions(-)
```

nvme-print: Few code clean-ups here

---

Documentation/Makefile

DocBook 5 has been released about a decade ago. Newer versions of
asciidoctor (since version 2.x) no longer support the previously
used DocBook 4.x format, so it is about time for us to switch too.
Fixes #495

DOC: Move to DocBook 5 when using asciidoctor

---

nvme-print.c

TP 4022 states that when a sanitize operation is started, self-test
operations in progress shall be aborted. The device-self test log page
includes a new result code that indicates if a self-test was aborted due
to a sanitize operation.

nvme-print: update self-test log to include 'aborted due to sanitize'

---

nvme-ioctl.c
nvme-print.c
nvme.h

Hi,
If you follow the commands below, you can see an over-printed
result of the get-property command in fabrics env.
```bash
property: 0x14 (Controller Configuration), value: 7f7800460001
```
But, If you have an option with `-H`, then the value would be printed
out in 32bit size which is intended.  So this patchset fixes the case
whose human option is not given to print out proper size of it.
```
Minwoo Im (3):
property: Introduce inline function to check 64bit reg
property: Remove unnecessary wrapper function
property: Fit print size for a property
nvme-ioctl.c | 30 ++++++++----------------------
nvme-print.c | 10 ++++++++--
nvme.h       | 24 ++++++++++++++++++++++++
3 files changed, 40 insertions(+), 24 deletions(-)
```

For 1.9/fit print property size

---

nvme-print.c

Revert commit 096fd4d which mistakenly reported Virtual Management
support in the ONCS field of the Identify Controller data structure.
Virtual Management support is part of OACS instead of ONCS and was
already correctly being displayed.

nvme-print: remove Virtual Management support from ONCS

---

nvme.c

This patchsets fix fd-leak in caes of error.  This branch might be
conflicted if prefious PR is merged first.  Then I'll rebase it after
all.
```
Minwoo Im (3):
format: Do not return directly without freeing fd
create-ns: Do not return directly without freeing fd
list-ctrl: Do not return directly without freeing fd
nvme.c | 28 +++++++++++++++++++---------
1 file changed, 19 insertions(+), 9 deletions(-)
```

nvme: Do not return directly without freeing fd

---

nvme-print.c

The bug was the instead of adding paths to to the subsystem object it
was added as a new subsystem

fix json print for list-subsys command

---

Makefile
plugins/shannon/shannon-nvme.c
plugins/shannon/shannon-nvme.h

Hello,current NVMe-Cli tools hasn't supprot for shannon systems, we want to add it.
May we add some specific commands?
We add four NVMe commands for shannon temporarily,smart-log-add, get-feature-add, set-feature-add,
and id-ctrl.
Any problems, please contact me with:
Email:yongxing.sun@shannon-sys.com

NVMe-Cli Shannon Plugin-add support for shannon systems.

---

fabrics.c
linux/nvme.h
nvme-ioctl.c
nvme-ioctl.h
nvme-lightnvm.c
nvme-models.c
nvme-print.c
plugins/huawei/huawei-nvme.c
plugins/intel/intel-nvme.c
plugins/seagate/seagate-nvme.c
plugins/virtium/virtium-nvme.c
plugins/wdc/wdc-nvme.c

This patch series fixes multiple sparse warnings and also adds supports for the NVMe 1.4 Identify Namespace fields.

Multiple nvme-cli patches

---

Makefile
fabrics.c
linux/nvme.h
nvme-status.c
nvme-status.h
nvme.c

```
Hi Keith,
Now it's v7 patchset for the nvme-status mapping with errno.  Chaitanya
has reviewed for the first five patches, and Sagi has suggested to
return an error for a case that numrec is different.  The 6th and 7th
patch will make what Sagi's said.
This patchset introduces nvme-status module to manage mapping
relationships between nvme error status and errno.  It cannot be
directly mapped in 1:1, but we can figure out what kind of errors
happended by the return value of nvme-cli.
NVMe status fields are 16bits to indicate, but UNIX return value from
main() will be parsed in 8bits so that we need to do something about
return value to indicate nvme error status.
This patch series has been tested with:
- nvme pcie device controller/namespaces
- nvme loop target with nvme-fabrics
The …
```

Introduce errno mapping with NVMe stauts

---

nvme-print.c

The Transport SGL Data Block Descriptor is a new SGL Descriptor Type added in
NVMe 1.4. Support for this descriptor type is added to the SGL Support (SGLS)
field of the Identify Controller data structure.

nvme-print: Show value for Transport SGL Data Block Descriptor support

---

nvme.c

ioctl might be failed in case that user gave a nvmeX controller device
node which is a character device.
Issue: #521

format: check BLKRRPART failure

---

nvme-lightnvm.c
plugins/lnvm/lnvm-nvme.c

This PR has been reviewed by the Javier and Matias from the
linux-nvme mailing list:
http://lists.infradead.org/pipermail/linux-nvme/2019-July/025712.html
Please consider this series to be merged.
Thanks,
```
Minwoo Im (3):
lnvm: remove redundant whitespace in lnvm_init()
lnvm: do not print 0 when the arg is not given
lnvm: cast identity structure to (void *) directly
nvme-lightnvm.c          | 5 ++---
plugins/lnvm/lnvm-nvme.c | 8 ++++----
2 files changed, 6 insertions(+), 7 deletions(-)
```

For lnvm/clean up

---

Documentation/nvme.1
Documentation/nvme.html
Documentation/nvme.txt

This series is just a update for the nvme main page of the doc.
It updates the main description to indicates not only just for PCIe,
but also fabrics.  Also the extensions plugin format has been updated.
```
Minwoo Im (2):
doc: make description not only for PCIe
doc: add extension plugins' command format
Documentation/nvme.1    | 16 ++++++++++++----
Documentation/nvme.html | 13 ++++++++++---
Documentation/nvme.txt  | 12 +++++++++---
3 files changed, 31 insertions(+), 10 deletions(-)
```

Update for the main nvme documentation

---

nvme.c

Now we can have it without any pre-whitespace before the goto labels.

nvme: clean up goto labels without whitespace

---

plugins/memblaze/memblaze-nvme.c

1. add six fields
CORRECT_PCIE_PORT0
CORRECT_PCIE_PORT1
REBUILD_FAIL
ERASE_FAIL
PROGRAM_FAIL
READ_FAIL
2. add more printf log
Signed-off-by: 丁剑 <jian.ding@memblaze.com>

[Log] Memblaze add more log infomation for S.M.A.R.T.

---

plugins/micron/micron-nvme.c
plugins/toshiba/toshiba-nvme.c
plugins/wdc/wdc-nvme.c

We can't use c99 declarations with older compilers.
Signed-off-by: Simon Schricker <sschricker@suse.de>

nvme-vendor: fix c99 declarations in vendor plugins

---

linux/nvme.h
nvme-print.c
nvme.c

* Show CRDT fields of Identify Controller data structure
* Show Host Behavior Supported state for Get Feature 16h
* Add support for error status NVME_SC_CMD_INTERRUPTED
Reviewed-by: Edmund Nadolski <edmund.nadolski@intel.com>

nvme: Enhanced Command Retry

---

nvme-lightnvm.c
nvme-lightnvm.h
plugins/lnvm/lnvm-nvme.c
plugins/lnvm/lnvm-nvme.h

This series has been reviewed by Matias and Javier.  The main patch
which is 2nd in this series has been updated by Matias's review.
Please consider this series to be merged.
Thanks,
```
Minwoo Im (3):
lnvm: make data_len to sizeof() instead of magic number
lnvm: introduce chunk-log command for chunk info
lnvm: introduce alias geometry for id-ns for lnvm
nvme-lightnvm.c          | 81 +++++++++++++++++++++++++++++++++++++++-
nvme-lightnvm.h          | 17 +++++++++
plugins/lnvm/lnvm-nvme.c | 81 ++++++++++++++++++++++++++++++++++++++++
plugins/lnvm/lnvm-nvme.h |  3 +-
4 files changed, 179 insertions(+), 3 deletions(-)
```

lnvm: add chunk-log page

---

Documentation/nvme-connect-all.txt
Documentation/nvme-discover.txt
fabrics.c

These are old patches by Hannes we forgot to send upstream. I had to fiddle a bit to make them apply again so I will ask Hannes to review them too.
A few things:
* I am not sure how to properly indent in the `build_options` function, because of the inconsistent use of whitespace.
* There are some new options, which weren't there when Hannes made the patches initially, which may need to be masked out as well.
* I think I also found the original discussion regarding these patches, as a bit of background:
http://lists.infradead.org/pipermail/linux-nvme/2019-February/022249.html

Mask out invalid options during discovery.

---

linux/nvme.h
nvme-print.c

Added display of new SANICAP fields of the Identify Controller data structure
* No-Deallocate Inhibited
* No-Deallocate Modifies Media After Sanitize
Updated Sanitize Status Log Page to include new fields
* Sanitize Status (SSTAT) field value (100b - completed successfully with deallocation)
* Estimated Time For Overwrite With No-Deallocate Media Modification (bytes 23:20)
* Estimated Time For Block Erase With No-Deallocate Media Modification (bytes 27:24)
* Estimated Time For Crypto Erase With No-Deallocate Media Modification (bytes 31:28)
Added Get/Set Feature - Sanitize Configuration
Reviewed-by: Edmund Nadolski <edmund.nadolski@intel.com>

nvme: sanitize enhancements

---

linux/nvme.h
nvme-builtin.h
nvme-ioctl.c
nvme-ioctl.h
nvme-print.c
nvme-print.h
nvme.c

* Add 'id-ns-granularity' (Identify command CNS 16h)
* Show Namespace Granularity Support (ctratt) for Identify Controller

nvme: add support for Namespace Granularity

---

nvme-print.c

* Bit 8 - CMB Queue Dword Alignment (CQDA)
* Bit 7 - CMB Data Metadata Mixed Memory Support (CDMMMS)
* Bit 6 - CMB Data Pointer and Command Independent Locations Support (CDPCILS)
* Bit 5 - CMB Data Pointer Mixed Locations Support (CDPMLS)
* Bit 4 - CMB Queue Physically Discontiguous Support (CQPDS)
* Bit 3 - CMB Queue Mixed Memory Support (CQMMS)
Reviewed-by: Edmund Nadolski <edmund.nadolski@intel.com>

nvme-print: show new CMBLOC bit fields added in NVMe 1.4

---

README.md

The nvme-cli package is already available in the official repository.

Update packaging state in Arch Linux

---

README.md

nvme-cli is available in the official repo of openSUSE Leap 42.2 or later.
See: [openSUSE Software](https://software.opensuse.org/package/nvme-cli)

Added openSUSE Leap to README.md

---

Documentation/nvme-sanitize-log.1
linux/nvme.h
nvme-print.c
nvme-status.c
nvme.h

*update 'show-regs' to display the new PMR registers (PMRCAP, PMRCTL, PMRSTS)
*update 'show-regs' to display the PMRS bit of the Controller Capabilities Register
*add support for error status NVME_SC_SANITIZE_PROHIBITED_PMR
Change-Id: Iec44c4c6cb6518dd6aacd870bd339668892d2525

nvme: add Persistent Memory Region (PMR) registers

---

linux/nvme.h
nvme-builtin.h
nvme-ioctl.c
nvme-ioctl.h
nvme-print.c
nvme-print.h
nvme.c

1. Add 'id-uuid' command to show the available UUID list
2. Update the get-log, get-feature, and set-feature commands
to include a uuid-index parameter
a. If set, the index will be passed as part of DW14 to
the controller
3. Update show_nvme_id_ctrl_ctratt() to show bit 9 of the CTRATT
(UUID List Supported)
4. Update show_effects_log_human() to show the UUID selection bit
of the effects log

nvme: UUIDs for Vendor-Specific Information

---

nvme.c

Make sure that the metadata buffer is initialized just like the data buffer.
For read/write, prefill the metadata buffer with zeroes. For passthru, reuse the prefill argument for the metadata buffer too.

nvme-cli: prefill metadata buffers

---

completions/bash-nvme-completion.sh

(Copied from issue) Autocompleting `nvme get` should result in: `get-feature    get-log    get-ns-id`, matching the rest of `nvme-cli`'s documentation and help dialogs.
Resolves #552

Fix bash-nvme-completion.sh typo

---

nvme-print.c
nvme-topology.c

Fixes a3b3e93286a3 ("nvme-cli: Code reorg")
$ gcc -v
minwoo@minwoo-desktop:~/work/nvme-cli.git$ (fix-build-error-for-asprintf) gcc -v
...
gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
nvme-print.c: In function ‘show_relatives’:
nvme-print.c:3964:3: error: ignoring return value of ‘asprintf’, declared with attribute warn_unused_result [-Werror=unused-result]
asprintf(&path, "/sys/class/nvme/%s", name);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
nvme-print.c:3968:3: error: ignoring return value of ‘asprintf’, declared with attribute warn_unused_result [-Werror=unused-result]
asprintf(&path, "/sys/block/%s/device", name);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

fix build error due to asprintf()

---

nvme.h

We have this structure in linux/nvme.h already.
cc -D_GNU_SOURCE -D__CHECK_ENDIAN__ -O2 -g -Wall -Werror -std=gnu99 -I. -DNVME_VERSION='"1.9.22.g6936.dirty"' -Iutil -o nvme-print.o -c nvme-print.c
In file included from nvme.h:35:0,
from nvme-print.h:4,
from nvme-print.c:7:
linux/nvme.h:24:3: error: conflicting types for ‘uuid_t’
} uuid_t;
^~~~~~
In file included from nvme-print.h:4:0,
from nvme-print.c:7:
nvme.h:32:3: note: previous declaration of ‘uuid_t’ was here
} uuid_t;
^~~~~~
Makefile:70: recipe for target 'nvme-print.o' failed

remove LIBUUID things from nvme.h

---

nvme-print.c
plugins/wdc/wdc-nvme.c

Since some pointer handlings are depended on 64 bit system.
So fix them as generic.

MAINT: compile warning error on 32 bit system

---

Makefile

It's possible for the install target to fail if the install-hostparams
target executes before the install-etc target:
```
/bin/sh: line 1: $(DESTDIR)$(SYSCONFDIR)/nvme/hostnqn: No such file or directory
make: *** [Makefile:113: install-hostparams] Error 1
```
Signed-off-by: Zac Medico <zmedico@gentoo.org>

make: install-hostparams depends on install-etc

---

nvme-print.c

```
The controller type should be printed out when the human-readable
option is given.
```

nvme-print: fix to print ctrltype when human-readable

---

nvme.spec.in

error caused by 70-nvmf-autoconnect.rules location different with Makefile.

nvme.spec.in: fix rpm build error

---

nvme.c

Changes determination of Device Self-Test in progress to be based on the
Current Device Self-Test Operation field as opposed to the Current
Device Self-Test Completion field.
Current implementation assumes that the Current Device Self-Test
Completion field will be 100% when no Device Self-Test operation is in
progress. This is an unsafe assumption as the NVMe Specification
explicitly specifies that the Current Device Self-Test Completion field
is invalid when no Device Self-Test operation in progress as indicated
by a value of 0 in the Current Device Self-Test Operation field.
A safe assumption is to use the Current Device Self-Test Operation field
which will be 0 when no Device Self-Test operation is in progress.
Current output when no Device Self-Test in progress:
```
$ nvme …
```

Correct self-test-log output

---

nvme-ioctl.c
nvme-ioctl.h
nvme.c

Instead of scanning all the namespaces for logs, the user can specify
the namespace from which he wants to retrieve the self-test log from.

nvme-cli: Add namespace-id option to self-test-log

---

Documentation/nvme-show-hostnqn.txt
Makefile
fabrics.c
fabrics.h
nvme-builtin.h
nvme.c

If /etc/nvme/hostnqn is not present, the fabric commands will ask
systemd for an app-specific machine ID as a fallback.  This should
improve functionality if /etc/nvme/hostnqn is not present and should
allow packagers to avoid creating /etc/nvme/hostnqn.
Heavily based on an earlier patch from Tomasz Torcz.
See also #415.
If you like this, similar treatment may be needed for hostid.

Use a systemd app-specific machine ID for hostnqn

---

plugins/intel/intel-nvme.c

Updating fields in 'nvme intel id-ctrl' to parse/print data already provided by the drive.

Intel plugin: Adding fields to id-ctrl VU region

---

Documentation/nvme-attach-ns.txt
updated.patch1

Add an example to man page of attach-ns command showing syntax and information to use hexadecimal value for Namespace identifier and controller identifier.

Add an example for attach-ns

---

nvme-print.c

1. Adding Controller Memory Space Supported(CMSS) in PMRCAP
2. Adding Persistent Memory Region Status(CBAI) in PMRSTS

nvme-cli: Update PMR Capability and PMR Status

---

nvme.c

Err value should be updated to 0 on success of nvme_get_nsid,
else the File Descriptor is passed on to nvme_status_to_errno
which returns an irrelevant errno.

nvme-cli: Update err value to 0 in get_ns_id func.

---

nvme.c

Err needs to be updated to 0 else err contains bs(no. of bytes written).
This gets passd onto nvme_status_to_errno, thus returning irrelevant errno.

nvme-cli: Update err to 0 in get_telemetry_log

---

nvmf-autoconnect/systemd/nvmefc-boot-connections.service

This prevents an unnecessary error message in the case that the nvme-fc
kernel module is not loaded and the
`/sys/class/fc/fc_udev_device/nvme_discovery`
handle is not available.
Apparently somebody sent my unit-files upstream, but didn't choose the up-to-date version :)

nvme-cli: Check for sysfs interface before NVMe discovery

---

nvme-print.c

Since the following %lx format warning error was caused on 64 bit system.
error: format ‘%lx’ expects argument of type ‘long unsigned int’,
but argument 2 has type ‘long long unsigned int’ [-Werror=format=]
So fix this by using %" PRIx64 " format instead as generic.

MAINT: Fix format compile warning error on 32 bit system

---

nvme.c

Opcode bits 1:0 indicate the direction of data transfer. These
bits should agree with the read or write flags provided.
Signed-off-by: Kelly Ursenbach <kelly.ursenbach@eideticom.com>

Warn on admin-passthru opcode not matching read/write flag

---

plugins/intel/intel-nvme.c

Adds the lat-stats function to intel plugin.
If lat-stats-tracking is enabled, lat-stats will print out latency
statistics according to the user's desired format.
Auto detects intel drives to print the correct format.
Can output as raw binary, a formatted histogram, or as formatted json.

intel: Add function lat-stats to cli

---

Documentation/nvme-wdc-clear-fw-activate-history.txt
Documentation/nvme-wdc-vs-error-reason-identifier.txt
Documentation/nvme-wdc-vs-fw-activate-history.txt
plugins/wdc/wdc-nvme.c
plugins/wdc/wdc-nvme.h

This commit contains the following changes:
Add support for WDC plugin command - vs-error-reason-identifier
Reverse enable/disable bit on the vs-telemetry-controller-option WDC plugin command
Add documentation file for vs-error-reason-identifier WDC plugin command
Minor corrections to the documentation files for vs-fw-activate-history and clear-fw-activate-history WDC plugin commands

Add  vs-error-reason-identifier WDC plugin command

---

Makefile
nvmf-autoconnect/dracut-conf/70-nvmf-autoconnect.conf
nvmf-autoconnect/dracut-conf/70-nvmf-autoconnect.conf.in

Currently, UDEVDIR defaults to `/etc/udev` while the dracut config file hardcodes `/usr/lib/udev`. This makes dracut complain that it cannot find the specified file.

Makefile: generate Dracut config according to UDEVDIR

---

Makefile
nvmf-autoconnect/dracut-conf/70-nvmf-autoconnect.conf.in

The SUSE rpm macros only have UDEVRULESDIR, not UDEVDIR.
So introduce a UDEVRULESDIR variable which is preset to
UDEVDIR/rules.d

Makefile: use UDEVRULESDIR instead of UDEVDIR

---

nvmf-autoconnect/systemd/nvmf-autoconnect.service

Add a systemd service to automatically start 'nvme connect-all'
upon booting if an /etc/nvme/discovery.conf file exists.
The 'nvme-tcp' or 'nvme-rdma' modules need to be loaded earlier
by eg the modules-load service.
Signed-off-by: Hannes Reinecke <hare@suse.com>

nvmf-autoconnect.service

---

scripts/gen-hostnqn.sh

Add a script to create a deterministic hostnqn which remains stable across reinstalls.
* Based on the system-UUID via dmidecode
* verifies UUID format
* tries to catch fake/lazy UUIDs

nvme-cli: Add script to determine host NQN

---

plugins/micron/micron-nvme.c

nvme-cli fails to build on musl with errors:
`error: 'PATH_MAX' undeclared` and `error: 'NAME_MAX' undeclared`
https://travis-ci.org/void-linux/void-packages/builds/650527256
Including the limits header fixes this: https://travis-ci.org/void-linux/void-packages/builds/650567795

Include limits.h for PATH_MAX and NAME_MAX on musl

---

linux/nvme_ioctl.h

Kernel has already updated 0x47 and 0x48 ioctl commands for 64bits
support.  This patch synced up the header file between kernel and
nvme-cli.

uapi: Sync up nvme_ioctl.h with kernel

---

nvme-ioctl.c

Remove duplicated included header files in a file (nvme-ioctl.c)

ioctl: Remove duplicated header files

---

tests/nvme_get_features_test.py

For One of the mandatory feature "Interrupt Vector Configuration",
the parameter cdw11 value should be equal to or less than the
number of interrupt vectors. Current implementaion uses the
IRQ number instead. This commit fixes it.

NVMe get features test fix

---

plugins/intel/intel-nvme.c

Fixing alignment in nvme_additional_smart_log_item introduced by switch
from '#pragma pack' semantics to '__attribute__((pack))'.
Per https://gcc.gnu.org/onlinedocs/gcc/Common-Type-Attributes.html each
union or struct requires it's own '__attribute__((pack))'.

Fixing Alignment Error In intel smart-log-add

---

plugins/intel/intel-nvme.c
plugins/intel/intel-nvme.h

This adds the cli function for lat-stats-tracking. Enabling it allows
the drive to start tracking latency statistics during i/o.

intel: Add lat-stats function

---

plugins/intel/intel-nvme.c

Fixing incompatibility between #580 and
e5786ad7ffa4734249c99bede2323a4d4cbb51ab.
Resolves #676  

Fixing compile error introduced by #580

---

plugins/intel/intel-nvme.c

Fixing empty fields in Intel VU id-ctrl introduced in
44755ae6869ab2a9dc6ac976fb43f4f2d746336c.

Fixing Empty Fields of Intel VU id-ctrl

---

nvme.spec.in

nvme.spec: rpmbuild error fix (missing file)

---

nvme-print.c

The offset for the next entry in the list is based on the length (len)
of the previous entry, but len is erroneously accumulated instead of
being set. This works fine for the first and second entry in the list
but will fail to reach the correct offset for the 3rd entry and beyond.
Signed-off-by: Saar Gross <saarg@amazon.com>

nvme-print: fix offset calculation in NS ID Descriptor list

---

nvme-print.c

9b2ce6ca3ba7 fixed the len accumulation, but only for the JSON printing.
Fix it for human output as well.
Reported-by: Narae Park <narae7.park@samsung.com>

nvme-print: fix namespace descriptor human printing

---

Makefile

The install path has been changed recently.  This change removes the old install folder if it exists.

Update Makefile to remove old destination folder

---

fabrics.c
nvme-topology.c
util/json.c

See issue https://github.com/linux-nvme/nvme-cli/issues/388

list-subsys: show PCIe device addresses of local devices, even when running on legacy kernels

---

nvme-lightnvm.c

If the execution of ioctl fails, the fd is not closed before returning,
and there is a resource leak.
Signed-off-by: Wu Bo <wubo40@huawei.com>

nvme-cli:lightnvm:fix fd leak when execute ioctl failed

---

Documentation/nvme-connect-all.1
Documentation/nvme-connect-all.html
Documentation/nvme-connect-all.txt
fabrics.c
nvmf-autoconnect/systemd/nvmf-connect@.service

Optionally have `connect-all` connect only to such controllers that have a matching `traddr` field. 
This avoids confusing error messages and failed connect attempts for NVMeoFC autoconnect. See https://github.com/linux-nvme/nvme-cli/commit/f989634e0595b1f184a0acb125c4460b1b31960a commit message for a detailed rationale.

nvme-connect-all: add -m /  -matching option

---

nvme-ioctl.c
nvme.c
plugins/netapp/netapp-nvme.c

In SPDK project (see spdk.io) we have implemented the ability
to set up devices via CUSE device exposing controller and
namespaces as character devices.
Namespace devices are also exposed as character devices, so
nvme-cli tools will not recognize them as valid devices.
To allow to use nvme-cli tool with SPDK NVMe CUSE devices
we can't assume that namespaces are block devices.
Change-Id: I52aa79d24002b8dec10e6fdd0cb9a71bb6750358
Signed-off-by: Tomasz Kulasek <tomaszx.kulasek@intel.com>

remove block device checking for namespace

---

nvme.c

fix fd leak when an error occurs in open_dev()
Signed-off-by: Wu Bo <wubo40@huawei.com>

nvme-cli:nvme:fix fd leak when an error occurs in open_dev()

---

nvme.c

Empty controller-id list in the ioctl call for attach/detach of namespace results effectively in no operation, yet the nvme cli reports falsely success. The controller id list must be specified with at least 1 controller in the list.

nvme-cli: controller list argument is required in attach-ns/detach-ns commands

---

nvme.c

If there is given nsid by user, no need to set using nvme_get_nsid.
(e770466615096a6d41f038a28819b00bc3078e1d)
Format for All namespace not using prev_lbaf.
(62ae3bea42cb3a81cc77492568747a330f783100)

nvme.c: remove side effects from older commit

---

nvme.c
plugins/intel/intel-nvme.c

Some error mesages are output without LF code so add it.

MAINT: nvme-cli: Add LF code into error messages

---

Makefile

A change to fabrics.c - commit 48c10dbf requires systemd version 242 or later.
Signed-off-by: Randy Bates <randall.bates@wdc.com>

Update systemd required version.

---

plugins/wdc/wdc-nvme.c

Changed the text displayed in the FW activation history commands under the WDC plugin to make the firmware history clearer.

Corrected text output in FW activation history

---

nvme-ioctl.c

Submit the address, not the value in the zone append ioctl.

ioctl: fix missing addrof

---

nvme-print.c

The Changed Zone List only support reporting of a maximum of 511 entries. If controller reports 0xFFFF is reported the data may be invalid and report zones should be issued instead.
Signed-off-by: Hans Holmberg <hans.holmberg@wdc.com>

Add warning if not all zone changed list entries are retrieved.

---

fabrics.c

Allows setting 0 value of ctrl_loss_tmo on connect.
Refer to this bug https://github.com/linux-nvme/nvme-cli/issues/740

Allow 0 value of ctrl_loss_tmo.

---

plugins/zns/zns.c
plugins/zns/zns.h

Changed verbose option to be the human readable option, such that it
aligns with the behavior of NVM id-ns and NVM id-ctrl.
Fix typos.

Various cleanups in the ZNS plugin

---

nvme-print.c

Fix mixed tabs/spaces use in show-regs pretty print and align tabulated
output.

nvme-print: streamline show-regs output

---

plugins/zns/zns.c

1. To do exception handling, the function needs nsid.
so nsid exception moved before using nsid
2. The data_len should be in bytes while setting zone descriptor.
And the logic already exist as a function, so use the function for it.

Zns refactoring

---

nvme-print.c
plugins/zns/zns.c

=======================================
osboxes@osboxes:~/$ sudo ./nvme zns zone-mgmt-send /dev/nvme0n1 -n 1 -s 0 -z 2
Segmentation fault
osboxes@osboxes:~/$
With fix.
osboxes@osboxes:~/$ sudo ./nvme zns zone-mgmt-send /dev/nvme0n1 -n 1 -s 0 -z 2
zone-mgmt-send: Success, action:2 zone:0 nsid:1
osboxes@osboxes:~/$
=====================================
And fixed if/else spacing in a couple of places.
Added close(fd) in the id_ctrl() function in second patch.

Zns plugin

---

plugins/wdc/wdc-nvme.c

Added opcode support for device 0x5006 on the clear-pcie-correctable-error command.

Clear pcie error

---

nvme-print.c

Fix the conversion from 16 to 32 bits.

nvme-print: zns mar/mor fields are 32 bits

---

nvme.spec.in

For /usr/bin/udevadm and /usr/bin/systemctl
This commit fixes an issue I found on CentOS 8.2 when installing an OS tree into an empty directory. It can be easily reproduced by
1. `mkdir /tmp/t`
2. `sudo dnf --installroot=/tmp/t --releasever=8 --setopt=module_platform_id=platform:el8 install nvme-cli`
The missing dependencies cause this error to appear:
```
/var/tmp/rpm-tmp.GvJTAy: line 6: uuidgen: command not found
/var/tmp/rpm-tmp.GvJTAy: line 10: systemctl: command not found
/var/tmp/rpm-tmp.GvJTAy: line 11: systemctl: command not found
/var/tmp/rpm-tmp.GvJTAy: line 12: udevadm: command not found
warning: %post(nvme-cli-1.9-7.el8_2.x86_64) scriptlet failed, exit status 127
```
util-linux has already been added to fix the uuidgen dependency. This simply fixes the dependencies for the …

Add missing dependencies on systemd & systemd-udev

---

nvme-print.c

- Add pretty print for mar, mor, rrl, and frl fields.
- Clarity Zone Size that value is reported in hex.
- Add header text for the zoc and ozcs fields.

Improve pretty print of the ZNS Command Set Identify Namespace command

---

Documentation/nvme-copy.1
Documentation/nvme-copy.html
Documentation/nvme-copy.txt
completions/_nvme
completions/bash-nvme-completion.sh
linux/nvme.h
nvme-builtin.h
nvme-ioctl.c
nvme-ioctl.h
nvme-print.c
nvme-status.c
nvme.c

Add support for NVMe TP 4065a ("Simple Copy Command"), v2020.05.04
("Ratified").
Co-authored-by: Steven Seungcheol Lee <sc108.lee@samsung.com>
**Note** For testing, there is an implementation of TP 4065a [available](https://irrelevant.dk/g/pci-nvme.git/commit/?h=scc) for the QEMU emulated NVMe device.

add support for issuing simple copy commands

---

Makefile
plugins/amzn/amzn-nvme.c
plugins/amzn/amzn-nvme.h

This allows the user to extract useful information from the vendor-specific field when querying Elastic Block Storage devices attached by Amazon Web Services. In particular, this field is populated with the block device that was requested by the user in the API call, which is of the form `/dev/sdc` or `/dev/xvdc` rather than `/dev/nvme2`. This plugin reduces the need for operating system maintainers to include vendor-specific packages in their distribution.
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/nvme-ebs-volumes.html
https://github.com/aws/amazon-ec2-utils/blob/master/ebsnvme-id

id-ctrl vs for Amazon Elastic Block Store

---

nvme.c

Physical block size could be different with logical block size from kernel
because of npwg(Namespace Preferred Write Granularity) & nows(Namespace Optimal Write Size)
physical block size would be multiple of logical block size.
Reviewed-by: Beomsoo Kim <beomsooo.kim@samsung.com>

nvme.c: read, write data size should be block_count * logical block size

---

nvme-print.c

- Expose MAR/MOR in a human readable format.
- Update spaces between values to align appropriately.
- Expose the MAR/MOR/FRL/RRL fields as unsigned decimal instead of hex.

Improve output readability of the zns id-ns command

---

Documentation/nvme-connect-all.1
Documentation/nvme-connect-all.html
Documentation/nvme-connect-all.txt
Documentation/nvme-connect.1
Documentation/nvme-connect.html
Documentation/nvme-connect.txt
Documentation/nvme-discover.1
Documentation/nvme-discover.html
Documentation/nvme-discover.txt

Commit d48164ad3a5 ("nvme: Add TCP transport ") added 'tcp' as a
transport type option, but didn't document it.
Add it for:
nvme-connect-all
nvme-connect
nvme-discover

doc: add 'tcp' as transport type option

---

Makefile

rpmbuild cause error on the system which is using difference RPM macros

rpmbuild: install directories using Makefile's variables

---

nvmf-autoconnect/dracut-conf/70-nvmf-autoconnect.conf.in

```
/usr/lib/dracut/dracut.conf.d/70-nvmf-autoconnect.conf:install_items+="/usr/lib/udev/rules.d/70-nvmf-autoconnect.rules"
dracut: WARNING: <key>+=" <values> ": <values> should have surrounding white spaces!
dracut: WARNING: This will lead to unwanted side effects! Please fix the configuration file.
```

add surrounding white spaces in 70-nvmf-autoconnect.conf.in

---

nvme-print.c

MAR is currently printed as unsigned.
MOR is currently printed as signed.
They should use the same print format.
Printing MOR as unsigned on a controller that has no limit,
shows as -1, which doesn't make sense.
Since no limit is represented as 0xffffffff in the ZNS spec,
printing MAR/MOR as hex makes the most sense.
Signed-off-by: Niklas Cassel <niklas.cassel@wdc.com>

nvme-print: fix ZNS MAR/MOR print format

---

plugins/seagate/seagate-nvme.c

This is the fix for "Seagate Uncorrectable Read Error Count reported twice #686"

Fix: Seagate Uncorrectable Read Error Count reported twice #686

---

nvme-ioctl.c
nvme-ioctl.h
nvme-lightnvm.c
nvme.c
plugins/dera/dera-nvme.c
plugins/intel/intel-nvme.c
plugins/memblaze/memblaze-nvme.c
plugins/micron/micron-nvme.c
plugins/scaleflux/sfx-nvme.c
plugins/seagate/seagate-nvme.c
plugins/shannon/shannon-nvme.c
plugins/toshiba/toshiba-nvme.c
plugins/wdc/wdc-nvme.c
plugins/zns/zns.c

Added passing Command Set Identifier to Get Log Page as described in TP
4056.
Spec : NVMe - TP 4056 Namespace Types 2020.06.15 - Ratified
Signed-off-by: Andrzej Jakowski <andrzej.jakowski@linux.intel.com>

nvme: implement passing csi to Get Log Page as described in TP 4056

---

nvme.spec.in

${_sbindir} could be placed in out of default bin directories
so just 'nvme gen-hostnqn' would not work with 'nvme command not found'

nvme.spec.in: using specific directory for nvme command on %post

---

Documentation/cmds-main.txt
Documentation/nvme.1
Documentation/nvme.html

```
This patch adds missing subcommands to the main man page.
Issue: https://github.com/linux-nvme/nvme-cli/issues/793
```

Add missing sub-command links from main man page

---

Documentation/nvme-rpmb.1
Documentation/nvme-rpmb.html
Documentation/nvme-rpmb.txt
Makefile
nvme-builtin.h
nvme-print.c
nvme-rpmb.c
nvme.c

RPMB commands with HMAC-SHA256 computed using Linux kernel crypto services and using MD5 (computed using Linux kernel crypto services) of a random number as nonce. Currently supports
- read-counter  - read current value of write counter
- read-data       - read data from specified RPMB target onto given file
- read-config    - reads configuration block data from specified RPMB target onto given file
- program-key  - configures given authentication key for an RPMB target
- write-data      - writes given block of data onto specified RPMB target
-  write-config   - writes device configuration block data to specified RPMB target
- info                  - prints current RPMBs support info of given NVMe device
TODO:
Need to check on what should be abstraction at nvme cli  to support boot …

Add support for Replay Protection Memory Block (RPMB) commands

---

Documentation/nvme-persistent-event-log.1
Documentation/nvme-persistent-event-log.html
Documentation/nvme-persistent-event-log.txt
completions/_nvme
completions/bash-nvme-completion.sh
linux/nvme.h
nvme-builtin.h
nvme-ioctl.c
nvme-ioctl.h
nvme-print.c
nvme-print.h
nvme.c
plugins/dera/dera-nvme.c
plugins/intel/intel-nvme.c
plugins/memblaze/memblaze-nvme.c
plugins/micron/micron-nvme.c
plugins/scaleflux/sfx-nvme.c
plugins/seagate/seagate-nvme.c
plugins/shannon/shannon-nvme.c
plugins/toshiba/toshiba-nvme.c
plugins/wdc/wdc-nvme.c
plugins/zns/zns.c

This is to add support for LID = 0x0D, Persistent Event log page,
this log page contains information about significant events not
specific to a particular command. The information in this log page
shall be retained across power cycles and resets. For More details
see NVM Express 1.4 Spec. Section 5.14.1.13 Persistent Event Log
(Log Identifier 0Dh)
Change nvme get log to read the whole log page interms of 4096 bytes.
Adding LSP argument in nvme get log fuction and change this across
the nvme get log function wherever has been used with NVME_NO_LOG_LSP.
This Adds support for the persistent event types:
01h SMART / Health Log Snapshot
02h Firmware Commit
03h Timestamp Change
04h Power-on or Reset
05h NVM Subsystem Hardware Error
06h Change Namespace
07h Format NVM Start
08h Format NVM …

nvme: add support for persistent event log page

---

plugins/zns/zns.c

If nvme_zns_report_zones() returns system error(negative) value, it
should not be passed to nvme_show_status() which parses NVMe completion
status code in case of positive value from the ioctl.
---
`NVMe status: Unknown(0xffff)` -> `zns report-zones: Inappropriate ioctl for device`

zns: fix showing system error in report_zones

---

Documentation/nvme-pred-lat-event-agg-log.1
Documentation/nvme-pred-lat-event-agg-log.html
Documentation/nvme-pred-lat-event-agg-log.txt
completions/_nvme
completions/bash-nvme-completion.sh
linux/nvme.h
nvme-builtin.h
nvme-ioctl.c
nvme-ioctl.h
nvme-print.c
nvme-print.h
nvme.c

This is to add support for LID = 0x0B, Predictable Latency Event
Aggregate Log Page, this is used if a Predictable Latency Event has
occurred for a particular NVM Set. For More details see NVM Express
1.4 Spec. Section 5.14.1.11 ("Predictable Latency Event Aggregate Log
Page (Log Identifier 0Bh)")
Max entries supported by this log page are 2044 which is:
(min xfer size (4096B) - size of num of entries(8B))/entry size (2B)
= 2044 entries

nvme: add support for predictable latency event aggregate log page

---

nvme.c

This patch refactors S_ISCHR/S_ISBLK macros to helper functions for
readability.  The global variable nvme_stat does no longer need to be in
subcommand handlers.

nvme: refactor S_ISCHR/S_ISBLK with helpers

---

Makefile

"verify-no-dep" makefile rule verifies that the main "nvme" program has no dependency
on code from the plugin modules. It can be used by developers as a regression check
in the development process.

verify-no-dep : Fix makefile entry.

---

nvme-ioctl.c
nvme-ioctl.h
nvme.c

The argconfig array helpers parse into int and unsigned long long
arrays. In the copy function we are casting an int* to __u16* and we end
up with wrong values. Instead, just use the types in the setup functions
directly and convert the individual values as part of calling the
cpu_to_le* helpers.
While copy is the one that is immediately broken on most systems, do
this for DSM as well since it breaks on systems where int is not 32
bits.
Fixes: 5dc44e6c21a1 ("add support for issuing simple copy commands")

fix dsm and copy range setup

---

nvme-print.c

```
As kernel sysfs shows nsid as a decimal format, nvme-cli should print
Namespace ID as decimal format.  Additionally, of course, the following
two commands results should be consistant:
- nvme list
- nvme list --verbose
The following examples is for case of nsid=32.
root@vm:~/work/nvme-cli.git# ./nvme list
Node             SN                   Model                                    Namespace Usage                      Format           FW Rev
---------------- -------------------- ---------------------------------------- --------- -------------------------- ---------------- --------
/dev/nvme0n1     deadbeef             QEMU NVMe Ctrl                           32          1.05  MB /   1.05  MB    512   B +  0 B   1.0
root@vm:~/work/nvme-cli.git# ./nvme list --verbose …
```

nvme-print: fix Namespace ID to decimal format

---

Documentation/nvme-predictable-lat-log.1
Documentation/nvme-predictable-lat-log.html
Documentation/nvme-predictable-lat-log.txt
completions/_nvme
completions/bash-nvme-completion.sh
linux/nvme.h
nvme-builtin.h
nvme-ioctl.c
nvme-ioctl.h
nvme-print.c
nvme-print.h
nvme.c

This is to add support for LID = 0x0A, Predictable Latency per
NVM Set, used to determine the current window for the specified
NVM Set when Predictable Latency Mode is enabled and any events
that have occurred for the specified NVM Set. For More details
see NVM Express 1.4 Spec. Section 5.14.1.10 ("Predictable Latency
Per NVM Set (Log Identifier 0Ah)")

nvme: add support for predictable latency per NVM set log page

---

nvme-ioctl.c
nvme-ioctl.h
nvme.c

In get lba status admin command, host shall specify valid and
desired namespace, adding NSID field to receive from user and
also assign data len fields as per the given MNDW value.

nvme: fix get lba status command nsid and data len fields

---

fabrics.c
nvme-print.c
nvme-topology.c
nvme.c
nvme.h

In SPDK project (spdk.io) it is possible to represent
devices using CUSE as character devices in "/dev/spdk/" directory.
No sysfs entries are generated for those devices.
nvme-cli default behavior is to scan the sysfs for entries on
newer kernels. Previously legacy_list() was used to determine
the topology, but that worked only on "/dev/" path.
To enable listing SPDK devices following changes were made:
- pass path parameter to list command
- before checking sysfs, check the path using legacy_list()
- expand arguments of scan_subsystems and related functions to accept the path
Example:
nvme list -d /dev/spdk/
Signed-off-by: Tomasz Zawadzki <tomasz.zawadzki@intel.com>

add path to nvme list

---

nvme-topology.c

Let's say we have multiple three subsystems in the system.  If we run
a simple 'nvme list' command, then scan_subsystems() will never set the
'ret' value which is a local variable.  This should be initialized to a
initial value to avoid invalid value returning.
This patch fixes returning invalid value from the scan_subsystems() in
case of multi-subsystems found.

nvme-topology: fix returning invalid value in scan_subsystems()

---

Documentation/nvme-self-test-log.1
Documentation/nvme-self-test-log.html
Documentation/nvme-self-test-log.txt
linux/nvme.h
nvme-ioctl.c
nvme-ioctl.h
nvme-print.c
nvme-print.h
nvme.c

Namespace ID no need to mention for the device self test log,
removing nsid and adding DST log entries field

nvme: fix device self test log

---

plugins/zns/zns.c

```
If Select All field in CDW13 is set to 1, SLBA(Starting LBA) will be
ignored.  This patch added a select all field to print out when
successfully done.  More informative success log with this field.
Example:
zns-reset-zone: Success, action:4 zone:0 all:1 nsid:1
```

zns: print select_all field for Zone Management Send

---

nvme-status.c

'errno' is set to errno value when system calls are returning with an
error (e.g., ioctl).  But, If a command fails without any system call,
then it needs to return the raw negative error value.
For example, if we don't provide any options for connect command:
root@vm:~# nvme connect
need a transport (-t) argument
root@vm:~# echo $?
0

nvme-status: return negative status if !errno

---

linux/nvme.h
nvme.c

Added fix for OWPASS value in sanitize command's CDW10, a value
of 0h specifies 16 overwrite passes.
Added the complete log data structure memebers, currently reseved
fields are ignored currently.

nvme: add fix for sanitize OWPASS value and log page structure

---

nvme.c

nvme: fix log-id data type and remove unnecessary log-id validtion

---

nvme-ioctl.c
nvme-ioctl.h

Functions nvme_write, nvme_read, nvme_compare are
not being called in place. Removing these unused
functions.

nvme: remove unused functions nvme_{read, write, compare}

---

fabrics.c
nvme-topology.c

But don't segfault if user gets this incorrect, instead provide helpful
info.

Input expects device name without /dev

---

nvme-topology.c

Sometimes opens are intentionally attempted and allowed fail, such as
the "nvme list" command.

Don't print error on failed to open in nvme-topology.c

---

Documentation/nvme-discover.txt

Document --device option so people know just to use the device name,
rather than device name with /dev prepended.

Man page update nvme discover

---

fabrics.c

The 'ctrl_loss_tmo' setting is invalid for 'loop' devices, so move
the default to '-1' (for 'unset'), and only set the default timeout
if discovery is not done on a loop device and the user has not
specified another value.
Fixes: 68bc869 ("fabrics: fix passing ctrl_loss_tmo=0 by default")

fabrics: ctrl_loss_tmo setting is invalid for 'loop'

---

linux/nvme.h
nvme-builtin.h
nvme-ioctl.c
nvme-ioctl.h
nvme-print.c
nvme-print.h
nvme.c

This will add the support for the identify controller nvm
command set. This is to impose size limit on non-mdts IO
commands as per TP 4040.

nvme: add identify controller nvm command set support

---

nvme.c

Remove spurious showing attribute 'rsvd'.  This even is not from the
user input.

nvme: remove spurious command show 'rsvd'

---

nvme.c

nvme: remove unassigned variable "lbads" from format function

---

nvme-print.c

nvme-print: add status_to_string for IO command specific status codes

---

nvme-print.c

Showing Sanitize Config (FID = 0x17) and Read Recovery Level
Config (RRL) (FID = 0x12) feature fields. Refactor the FID = 0x0
and non-defined/reserved FIDs response.

nvme-print: show feat fields for FID = {0x17,0x12} and refactoring

---

fabrics.c

When creating a persistent device with the `--persistent` option, print the device that was created so that one can reference it later without having to guess it.

Print device name when creating a persistent device

---

Documentation/nvme-endurance-event-agg-log.1
Documentation/nvme-endurance-event-agg-log.html
Documentation/nvme-endurance-event-agg-log.txt
completions/_nvme
completions/bash-nvme-completion.sh
linux/nvme.h
nvme-builtin.h
nvme-ioctl.c
nvme-ioctl.h
nvme-print.c
nvme-print.h
nvme.c

This log page indicates if an Endurance Group Event has
occurred for a particular Endurance Group, the details of
the particular event are included in the Endurance Group
Information log page for that Group. For details see
NVM Express 1.4 Spec. Section 5.14.1.15 ("Endurance Group
Event Aggregate (Log Identifier 0Fh)")
Co-Authored-By: Karthik Balan <karthik.b82@samsung.com>

nvme: add support for endurance group event aggregate log

---

Documentation/nvme-lba-status-log.1
Documentation/nvme-lba-status-log.html
Documentation/nvme-lba-status-log.txt
completions/_nvme
completions/bash-nvme-completion.sh
linux/nvme.h
nvme-builtin.h
nvme-ioctl.c
nvme-ioctl.h
nvme-print.c
nvme-print.h
nvme.c

This log page is used to provide information about
subsequent actions the host may take to discover which
logical blocks, in namespaces that are attached to
the controller, may no longer be recoverable when read.
For more details see NVM Express 1.4 Spec. Section
5.14.1.14("LBA Status Information (Log Identifier 0Eh)")
Co-Authored-By: Karthik Balan <karthik.b82@samsung.com>

nvme: add support for lba status log page

---

Documentation/nvme-discover.txt
fabrics.c

Add the '-o'/'--output-format' option to generate JSON output
for nvme discovery.

nvme-discover: add json output

---

scripts/gen-hostnqn.sh

IBM POWER systems expose a platform created UUID in the device
tree. Use that as the UUID in the host NQN.
Signed-off-by: Brian King <brking@linux.vnet.ibm.com>

nvme: Make gen-hostnqn use partition UUID on IBM POWER systems

---

fabrics.c

Remove the extra "conf" in the error message when the open on
/etc/nvme/discovery.conf fails.

fabrics: update discovery.conf error message

---

linux/nvme.h
nvme-print.c

The changes as per the Base NVMe 1.4b and NVMeOF 1.1 specification.
Optional Fabrics Command Support(OFCS) field added at wrong offset
of the structure, and other naming conventions fixed as per the Spec.

nvme: fix identify controller structure fabrics identify fields

---

fabrics.c
nvme.c

As per the latest comment on PR #933, changing all the memory
failure errors notify using "perror" instead of "fprintf"

nvme: change system error notification from fprintf to perror

---

linux/nvme.h
nvme-print.c

Split the PMR Memory Space Control register 64 bits into
PMR Memory Space Control Lower and Upper 32 bits each as
per NVM Express Spec. 1.4b changes.

nvme-print: split pmrmsc into pmrmscl and pmrmscu

---

nvme-ioctl.c
nvme-ioctl.h
nvme-rpmb.c
nvme.c

Security Send and Receive commands doesn't fill the CQE CDW0,
remove uncessary passing of result field in both the commands.
The changes are made in RPMB related files since it is dependent
on these commands. RPMB operations only result field as part of
the dataframe and this result is completely different from the
CQE CDW0.

nvme: fix securuty send and receive commands result field

---

nvme-print.c

For Host Memory Buffer(HMB) fearure as part of get feature Memory
Return(MR) bit is not part of the CQE CDW0 and add endianess conversion
for the get feature HMB attribute data structure.

nvme-print: fix HMB get feature response in human readable format

---

nvme.c

Show the command return status code along with details with the
help of nvme_show_status instead of printing the err.

nvme: use nvme_show_status when command status code is non-zero

---

nvme.c

Fix DSP description, which is Data Protections Settings and other fields
description improved especially 'flbas' and 'block-size' relationship.

nvme: fix DPS description and improve the other fields descriptions

---

nvme-print.c
nvme-print.h
nvme.c

Refactor and improve the passthru, io-passthru and admin-passthru
result printing based on the command opcode and type by using the
cmd_to_string.

nvme: refactor and improve the passthru function

---

nvme.c

In DSM and Copy Commands buffers which dyamically allocated
not freed, fixing that.

nvme: fix dsm and copy commands free up buffers

---

linux/nvme.h
nvme-print.c

In NVMe 1.4 spec. Change Namespace Event Type (06h) of persistent
event log Data Format - NCAP field was assigned with 16 bytes. Now
in 1.4b spec. its modified to 8 bytes.

nvme: address 1.4 to 1.4b changes for Change NS event type

---

fabrics.c

When parsing the discovery entries results in invalid parameters
for a given connection we'll enter an infinite loop as the -EINVAL
error code is always assumed to indicate a wrong 'disable_sqflow'
setting.

fabrics: fix infinite loop on invalid parameters

---

Makefile
fabrics.c
nvme-print.c
nvme-print.h
nvme.h
plugins/amzn/amzn-nvme.c
plugins/huawei/huawei-nvme.c
plugins/intel/intel-nvme.c
plugins/micron/micron-nvme.c
plugins/netapp/netapp-nvme.c
plugins/scaleflux/sfx-nvme.c
plugins/seagate/seagate-nvme.c
plugins/shannon/shannon-nvme.c
plugins/wdc/wdc-nvme.c
util/json.c
util/json.h

For future improvements like parsing json configurations we should be building against a 'real' json library; that'll save us having to implement the necessary functions ourselves. And as json-c has a quite similar structure we can use is as a drop-in replacement for our internal json functions.

Build against json-c library

---

fabrics.c
nvme-topology.c
nvme.c
nvme.h

Both fabrics.c and the 'gen-hostnqn' command contain functions
to generate a default host NQN. Needless to say, both are different.
_And_ we have the script 'nvme-gen-hostnqn' to read the host nqn
from the system UUID, implement yet another way.
This patch merges all of these functions, and implements a hierarchy
in generating host NQNs:
- Try reading system UUID from /sys/firmware/dmi/entries
- Try reading systemd-generated UUID
- Generate a random UUID

Read system UUID from DMI and merge hostnqn generation functions

---

nvme.c

In Timestamp feature structure size is 8 bytes, since the 6th
and 7th bytes are reserved no need to change the data len
parameter to 6 bytes. Another fix required for the data len of
time stamp i.e. mentioned as 13, it fixed and sent it as PR #983

nvme: fix timestamp feature in set feature

---

Documentation/nvme-connect-all.1
Documentation/nvme-connect-all.html
Documentation/nvme-connect-all.txt
Makefile
fabrics.c
fabrics.h
nvme-topology.c
nvme.c
nvme.h
util/cleanup.c
util/cleanup.h
util/log.c
util/log.h

This corresponds to the patch series by the same name that I've posted to linux-nvme on Mar 30th. It's part of my larger PR #877. I'm posting it here knowing that #877 is harder to review and more controversial, in the hope to get these small fixes merged.
This series collects patches from my former submission "RFC: add "nvme
monitor" subcommand" which aren't directly related to the monitor
functionality, but required to make the monitor in its current form
compile. A v3 of the monitor code is about to follow.
The main part is the "generic logging functionality".
Changes wrt the RFC: add "nvme monitor" subcommand series: many.
- rebased to current upstream code base e9d43dd ("[nvme-cli] Fix Max/Min 
User data erase counts displayed in 0xC2 Log Page"))
- renamed log() to msg() in order to …

Some minor fixes/additions for nvme-cli

---

linux/nvme.h
nvme-builtin.h
nvme-ioctl.c
nvme-ioctl.h
nvme-print.c
nvme-print.h
nvme.c

Adds support for Identify Primary Controller Capabilities command (CNS 14h)
For reference, the data structure is defined in 5.15.2.10 Primary Controller Capabilities data structure (CNS 14h) in the 1.4a specification. 
Signed-off-by: Nate Roiger <nate.roiger@hpe.com>

Identify Primary Controller Capabilities support

---

linux/nvme.h

In recent PR that merged has redundant/duplicate structure
with name "nvme_pri_ctrl_caps" that has already defined with
name "nvme_primary_ctrl_caps" and its been used.

nvme: remove redundant structure of primary controller capabilities

---

nvme-topology.c

It looks like in PR #979 `systemd/sd-id128.h` include was omitted from `nvme-topology.c`.
Without this build fails with:
```
nvme-topology.c: In function ‘uuid_from_systemd’:
nvme-topology.c:760:2: error: unknown type name ‘sd_id128_t’
760 |  sd_id128_t id;
|  ^~~~~~~~~~
nvme-topology.c:763:6: warning: implicit declaration of function ‘sd_id128_get_machine_app_specific’ [-Wimplicit-function-declaration]
763 |  if (sd_id128_get_machine_app_specific(NVME_HOSTNQN_ID, &id) < 0)
|      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
nvme-topology.c:763:40: error: ‘NVME_HOSTNQN_ID’ undeclared (first use in this function); did you mean ‘NVME_IOCTL_ID’?
763 |  if (sd_id128_get_machine_app_specific(NVME_HOSTNQN_ID, &id) < 0)
|                                        ^~~~~~~~~~~~~~~
| …
```

Fix missing sd-id128 include

---

Documentation/nvme-sanitize-log.1
Documentation/nvme-sanitize-log.html
Documentation/nvme-sanitize-log.txt
nvme-ioctl.c
nvme-ioctl.h
nvme.c

Added Retain Asynchronous Event (RAE) field for sanitize
log.

nvme: add rae field in sanitize-log

---

nvme-print.c

normal print result
Node             SN                   Model                                    Namespace Usage                      Format           FW Rev
---------------- -------------------- ---------------------------------------- --------- -------------------------- ---------------- --------
/dev/nvme0n1     S39XNX0J6C3BBA       91721190020910SAM0PM1725A0004T00035000   1           0.00   B /   4.19  TB      4 KiB +  0 B   MVP41G7A
/dev/nvme0n2     S39XNX0J6C3BBA       91721190020910SAM0PM1725A0004T00035000   2           4.19  MB /   4.19  MB      4 KiB +  0 B   MVP41G7A
json print result (nvme0c0n* are invaild devices name, so will be removed from list)
[root@localhost nvme-cli]# nvme list -o json
{
"Devices" : [
{
"NameSpace" : 1,
"DevicePath" : "/dev/nvme0c0n1",
... …

nvme: Remove invalid device node from nvme list

---

plugins/intel/intel-nvme.c
plugins/intel/intel-nvme.h
util/argconfig.c
util/argconfig.h

Optane lat-stat thresholds are 8 bytes per bucket. Also
the amout of buckets is smaller when compared to nand ssds.
This change allows to query both types of ssds transparently.
Also added the command line option to print lat-stats in json
Signed-off-by: Francisco Munoz <francisco.munoz.ruiz@intel.com>

Modify lat-stats cmd to cope with optane bucket format

---

nvme-print.c

Status Field in error-log 16 bits, 15 bits from q to 15 are represents
status field and 0th bit is phase tag, print phase tag seperately, in
1.4b spec its been clearly called out.

nvme-print: print phase tag field separately in error-log fields

---

nvme-topology.c

Fix the following build error.
nvme-topology.c: In function ‘uuid_from_systemd’:
nvme-topology.c:766:8: error: unused variable ‘ret’ [-Werror=unused-variable]
766 |  char *ret;
|        ^~~

nvme-topology: fix build error for unused variable

---

plugins/zns/zns.c

Currently ZNS plugin nvme device status code 15 bits
being returned to shell which will take only 8 bits.
Convert the nvme status code to linux standard errno
with the help of status_to_errno function and return.

zns: return response with status to errno conversion

---

nvme-print.c

IO Command Set Profile feature with FID 0x19 in TP 4056d
CQE CDW0 value printing is incorrect, fix that.

nvme-print: fix io-command set profile feature

---

nvme-rpmb.c
nvme.c

Cleaning up all the nvme-cli source filses where buffer allocation
check is ther before free up, NULL free is acceptable perfectly as
Chaitanya mentioned in another patch.

nvme: remove buf allocation check since NULL free is acceptable

---

nvme-print.c

nvme: add one space around the operand and operator in d_raw

---

Documentation/nvme-resv-register.1
Documentation/nvme-resv-register.html
Documentation/nvme-resv-register.txt
completions/_nvme
nvme.c

Fix typos in short option for reservation register action and the full
name of reservation acquire action.

nvme-cli: fix typos in reservation actions

---

nvme-print.c

Print the Namespace write protect states for the get feature
with FID 0x84, Namespace write protect config.

nvme-print: print namespace write protect states in get feature

---

nvme-print.c

Add FNA 3rd bit to indicate whether FormatNVM command
supports Broadcast NSID (FFFFFFFFh) or not as per TP
4056d.

nvme-print: add fna 3rd bit in identify ctrl

---

nvme.c

Command Set Identifier (CSI) data type is 8 bits, fix that.

nvme: fix csi data type in list_ns

---

nvme-ioctl.c
nvme-ioctl.h

nvme-ioctl: remove unused function nvme_identify_ns_list

---

Documentation/nvme-get-log.1
Documentation/nvme-get-log.html
Documentation/nvme-get-log.txt
nvme.c

Previously lsi is set as 0 as hard coded value by the get-log command.
To set this parameter by the command add lsi option for the command.

nvme-cli: Add lsi option for get-log command

---

nvme.c

Fix the parameter sizes as per the data type in complete
nvme.c file.

nvme: fix parameter sizes

---

nvme-print.c

Made changes to nvme_show_sanitize_log to make sure when choosing binary or json that it doesn't also print out human readable directly after.

corrected-returns-in-sanitize-log

---

nvme-topology.c

scan_ctrl() tries to open the controller device but this operation is
expected to fail for fabric setups when a path is down. This can lead
to the situation where the subsystem is in a healthy state, e.g. at
least one path is in live state. In this scenario a failure is printed
although everything is fine.
This is especially a problem for NVMe/TCP configs where the controller
remains in 'connecting' state for 10 minutes following a path
down. All that time 'nvme list' ends up in errors and that's a major
irritant for end users. This also makes CI automation more complex
than needed.
Just drop the error message as we have other error paths in this
function where we just bail out if they fail without printing an
error message.

nvme-topology: no error message when openeing of controller fails

---

nvme.c

Add the invalid LSP and UUID Index value checks as per the field
lengths. Refactor the get_log function.

nvme: add lsp and uuid index invalid value checks in get log

---

linux/nvme.h
nvme-print.c

Add the OCFS field in Identify Controller Structure, as per the
Ratified TP 4065b (Simple Copy Command).

nvme: add optional copy format support id ctrl field

---

nvme-print.c

Add the Zone Descriptor Changed Notices in get feature
human readble output for the Async Event config feature
(FID = 0x0B) as per the TP4053 Zoned Namespaces

nvme: add zone desc changed notice async event

---

fabrics.c

Discovery log page data may include records belonging to different
transport types. If during a nvme connect-all, a connect is attempted
on a record that doesn't match the transport type passed here, it
would end up in a connect failure for that record. For e.g. one would
see the below error if a connect is attempted on a tcp record but the
transport type passed here is 'fc' and its associated parameters:
nvme_tcp: malformed src address passed: nn-0xXXXX:pn-0xYYYY
Fix this by proceeding with the connect only if the appropriate
transport type matches a given record during the connect-all.

fabrics: skip connect if transport type doesn't match

---

nvme-ioctl.c
nvme.c

Add the LBAFU in FormatNVM command as per the NVMe 2.0
Base Specification.

nvme: add the LBA format upper in Format NVM Command

---

nvme.c

Fix the shell return error numbers(errno) in overall
nvme.c file.

nvme: fix errno for non nvme device return errors

---

Documentation/nvme-connect.txt
fabrics.c

When creating a connection (i.e. `nvme connect`) we need to know which device was create so that when we later disconnect, we'll know which device to pass to `nvme disconnect`.
This adds the `--output-format` option to the `nvme connect` command. By default, the device name is not printed. One needs to specify `--output-format normal` or `--output-format json` to print the device name in "normal" or "json" format.

Add option to print device name on connect

---

nvme-ioctl.c
nvme-topology.c

Calling 'nvme list' on a system where some controllers are undergoing a reset will lead to failures in the output as the current code only tries the first controller to fetch information about the namespace.
With this the next available controller is checked if the current one returns an error.

Fix failures during 'nvme list'

---

Documentation/nvme-get-log.1
Documentation/nvme-get-log.html
Documentation/nvme-get-log.txt
nvme-ioctl.c
nvme-ioctl.h
nvme.c
plugins/wdc/wdc-nvme.c

Add the Offset Type (OT) and Command Set Identifier (CSI) in
get_log and to nvme_get_log14 function as per the Spec 2.0.
Based on the requirement this can be added for the nvme_get_log13
and nvme_get_log when implementing specific log pages that use
these two parameters.

nvme: add get log page 2.0 spec fields

---

Documentation/nvme-zns-close-zone.1
Documentation/nvme-zns-finish-zone.1
Documentation/nvme-zns-offline-zone.1
Documentation/nvme-zns-open-zone.1
Documentation/nvme-zns-reset-zone.1
Documentation/nvme-zns-set-zone-desc.1
Documentation/nvme-zns-zone-mgmt-send.1
nvme-ioctl.c
nvme-ioctl.h
plugins/zns/zns.c

- Enabled the option to set the timeout value used for each of the zone management commands, specifically to allow for longer timeouts with the zone-reset command. 
- The default timeout for zone reset is also increased to 90 seconds.

Add Timeout Parameter for Zone Management Commands

---

Documentation/nvme-verify.1
Documentation/nvme-verify.html
Documentation/nvme-verify.txt
Documentation/nvme-write-zeroes.1
Documentation/nvme-write-zeroes.html
Documentation/nvme-write-zeroes.txt
nvme-ioctl.c
nvme-ioctl.h
nvme.c

Added support for the Variable Sized Expected Logical Block Storage Tag(ELBST)
and Expected Logical Block Reference Tag (ELBRT), CDW2 and CDW3 (00:47) bits
for NVM commands Write Zeroes and Verify commands.

nvme: add CDW2 and CDW3 support for Write Zeroes and Verify Command

---

plugins/intel/intel-nvme.c

There is a typo in intel-nvme.c, it should probably read something like "Retrieve Intel Temperature Statistics log, show it". 
Instead it reads "Get Intel Marketing Name log and show it".

intel_nvme: fixed typo

---

plugins/micron/micron-nvme.c
plugins/wdc/wdc-nvme.c

Use PRIx64 format specifier instead of lX for more portability.
Signed-off-by: Sushrut Shirole <sushrutshirole@gmail.com>

Use PRIx64 macro for more portability.

---

linux/nvme_ioctl.h
nvme-ioctl.c
nvme-ioctl.h
nvme.c

Change the IOCTL and depricate SQE structure for NVM commands
Read, Write and Compare Commands to add support for the Storage
Tag field (CDW2 and CDW3).
Remove the unsed nvme_user_io structure and NVME_IOCTL_SUBMIT_IO.

Change IOCTL for read, write and compare commands

---

nvme-print.c

If BPINFO or BPRSEL or BPMBL are zero means it doesn't indicates
that boot parttitions feature is not supported. CAP registers BPS
bit indicatates this feature support, fix that.

fix boot partitions register show in human readable format

---

nvme-ioctl.c
nvme-ioctl.h
nvme.c

Add Multiple Update Detected (MUD) field in FW Commit command
CQE CDW0 as per NVMe 2.0 Spec.

nvme: add multiple update detected result value in fw commit

---

scripts/gen-hostnqn.sh

The validation heuristic is getting triggered for valid system UUID
such as 37383638-3330-4d32-3237-33353032394e. The only UUID validation
is already implemented. Remove the heuristic as it blocks valid use
UUIDs and doesn't protect from misuse anyway.
Signed-off: Daniel Wagner <dwagner@suse.de>

gen-hostnqn: Remove UUID validation heuristic

---

nvme.c

current logic ignore given data by user
so make priority to use user argument first

nvme: Bug fix default data_len used if no argument given

---

nvme-topology.c
nvme.c
nvme.h

Retrieve `logical_block_size` sysfs attribute when I/O subcommand(e.g.,
read, write, ...) is given instead requesting BLKSSZGET ioctl to the
generic device which is not supported.

nvme: support ns generic device to submit_io

---

nvme.h

unsigned int should use json_object_new_uint64(json-c >= 0.14-20200419)
Error examples
nsze    : 0xe8e088b0
{
"nsze":-387938128
}
After fix this
{
"nsze":3907029168
}
json_object_add_value_int also should use json_object_new_int64
since util/json.h support long long type, and other codes are using it for 64bit values

Bug fix unsigned int and int should use 64bit api for json-c

---

nvme-print.c

Check if the controller is available before dereferencing the
controller attributes.

nvme-print: fix 'nvme list' segfault if controller is unavailable

---

nvmf-autoconnect/systemd/nvmf-autoconnect.service

One of my test machines failed to discover the nvme-tcp target during boot
despite the fact that I added the necessary configuration under
/etc/nvme/discovery.conf and I enabled the systemd service script
"nvmf-autoconnect".
I found out that the problem is in the systemd nvmf-autoconnect service:
The script depends on a systemd service called "network.target"
but, according to the following post [1], network.target is not intended
to be used during boot.
To be sure that the network card is really configured before trying to connect to the target,
we should use "network-online.target" instead.
[1] https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/
"network.target has very little meaning during start-up. It only indicates that the network management stack is up after it has …

autoconnect: replace network.target with network-online.target

---

nvme-ioctl.c
nvme-ioctl.h
nvme-rpmb.c
nvme.c

by allowing data from stdin, and assuming transfer length to match input size if not specified.
resolve #951

Making security-send command more flexible

---

.gitmodules
fabrics.c
util/argconfig.c

Heya,
this is the corresponding patchset to the libnvme pull request 'discovery-fixes'.
It fixes the handling of persistent (and non-persistent :-) discovery controllers, and also some crashes which I've encountered on the way.
Once both patchsets are merged one should reset the submodule branch to pointing to the upstream libnvme repository; I'll see if the CI will accept a patch for that even without the merge.

Discovery fixes

---

nvme-models.c

Previously the ProductName field would be set to "Unknown device" if nvme-cli was unable to decode the subdevice/subvendor values found for the device. 
Now set the field using whatever information was able to be decoded.

Print ProductName found even if subvendor/subdevice is unknown

---

fabrics.c

fabrics: Fix memory leak for nvme discover command
Signed-off-by: Wu Bo <wubo.linux@gmail.com>

fabrics: Fix memory leak for nvme discover command

---

plugins/zns/zns.c

I think correct buffer size is `header + N x (descriptor + extension)`. N is multiplied twice here.

Fix report zones buffer allocation

---

nvme.c

Remove the `--directory` argument for `nvme list`. The option has been without
effect since nvme-cli moved to libnvme.
Signed-off-by: Andreas Hindborg <andreas.hindborg@wdc.com>

Remove unused command line argument for `nvme list`

---

nvme-print.c
nvme.c

Simple addition to handling the BINARY flag option.
Example
```
0000000 0001 0001 0000 0000 0000 0000 0000 0000
0000010 0000 0000 0000 0000 0000 0000 0000 0000
*
0001000
```
Signed-off-by: Nate Roiger <nate.roiger@hpe.com>

Binary output support for list-ctrl command

---

nvme-print.c

Generic device (e.g., /dev/ng0n1) is mapped to a block device (e.g.,
/dev/nvme0n1).  This chardev can be taken in case that block device is
failed to initialize from the kernel due to some reasons (e.g.,
metadata initialization failed).  This generic node information can be
shown in the verbose list mode with HIDDEN block device (nvme0n1 in the
below example).
root@localhost:~# nvme list -v
NVM Express Subsystems
Subsystem        Subsystem-NQN                                                                                    Controllers
---------------- ------------------------------------------------------------------------------------------------ ----------------
nvme-subsys0     nqn.2019-08.org.qemu:subsys0                                                                     nvme0
NVM …

nvme-print: print generic ns chardev in verbose mode

---

nvme.c

This patch fixes a bug in `list-ctrl` where an error code was misinterpreted.
Signed-off-by: Andreas Hindborg <andreas.hindborg@wdc.com>

Fix error handling in `list-ctrl`

---

plugins/zns/zns.c

This patch fixes a bug in the error handling in `zns_mgmt_send`, where error
cause was not reported correctly.
Signed-off-by: Andreas Hindborg <andreas.hindborg@wdc.com>

Fix dead assignment

---

plugins/dera/dera-nvme.c
plugins/intel/intel-nvme.c
plugins/wdc/wdc-nvme.c
plugins/zns/zns.c

Compiling with additional compiler options generates some warnings;
fix them.

Fixup compiler warnings

---

Makefile

Support building nvme-cli using a shared version of libvnme. The Makefile checks first if libnvme has been checked out as git submodule in under libvnme and uses this as first preference. If this fails pkg-config is used to determine if a shared libnvme exists.

Support to shared libnvme builds

---

subprojects/json-c.wrap

Commit cad1ef9710f3 ("build: Set minimum version for json-c and add
fallback support") is missing the json-c wrap file.

build:  Add missing json-c.wrap

---

fabrics.c

Avoid dereferencing connect_args strings if the corresponding nvme
sysfs paths are not available.

fabrics: fix 'nvme discover' segfault if sysfs path is not available

---

Makefile
nvme.h

The config flag for json-c hasn't been updated to the consistent
naming scheme everywhere. Let's use prefix it with CONFIG and use the
correct library name which is json-c.

build: Use CONFIG_JSONC consistently

---

fabrics.c

When passing the parameter --ctrl-loss-tmo=-1
nvme-cli silently drops it and replaces its value with the
default one (600) despite the fact that -1 is valid
and accepted by the kernel.
ctrl_loss_tmo < 0 means that it will try to reconnect forever
This is due to the fact that -1 is treated like "variable unset"
by nvme-cli and the add_int_argument() function ignores
all arguments with such a value if allow_zero is true (the latter seems
to be completely unintended).
This patch fixes the bug by:
1) removing the "arg == -1" condition from add_int_argument() and letting
the caller take care of checking if -1 is an acceptable value
for a particular argument.
2) initializing ctrl_loss_tmo to its default value instead of -1.
Signed-off-by: Maurizio Lombardi <mlombard@redhat.com>

nvme-cli: ctrl-loss-tmo should accept -1 as value

---

plugins/zns/zns.h

Refactor the commands available in the zns plugin, such that the most used
comes first, and improve the description a bit.

nvme: refactor the list of ZNS command

---

Makefile
fabrics.c
nvme-print.c
nvme.h
plugins/wdc/wdc-nvme.c

commit 0b63a8b7cfb7 ("Check json-c libversion, recover commit d127537")
broke building on older releases when using 'make'.
Add a compability code to enable building on older json-c releases.

Compability for older json-c releases

---

Documentation/nvme-connect-all.txt
Documentation/nvme-connect.txt
Documentation/nvme-discover.txt
fabrics.c
nvme.spec.in

This patchset adds a new option 'dump-config' to print out the resulting JSON configuration to stdout, and also documents the 'config-file' commandline parameter.

Update and document configuration file access

---

Documentation/nvme-connect-all.txt
Documentation/nvme-discover.txt
fabrics.c

Hi all,
here's now the companion patch to support TP8013 & TP8014 for nvme-cli.
The biggest difference here is that we now have the '--nqn' argument for 'discover' and 'connect-all', allowing to connect to a unique discovery controller NQN. And of course we now decode the new fields and values in the discovery log page entry.

TP8013 & 8014 support

---

fabrics.c

Check if the transport type is available before dereferencing
it in discovery_trsvcid().
Fixes: 362c90f ("fabrics: add default port number for NVMe/TCP I/O
controllers")

fabrics: fix 'nvme connect' segfault if transport type is omitted

---

nvme-rpmb.c
nvme.c
plugins/intel/intel-nvme.c
plugins/memblaze/memblaze-nvme.c
plugins/micron/micron-nvme.c
plugins/seagate/seagate-nvme.c
plugins/shannon/shannon-nvme.c
plugins/toshiba/toshiba-nvme.c
plugins/wdc/wdc-nvme.c
plugins/zns/zns.c

With the latest libnvme update the ioctl wrapper functions have
been sanitized to always include a 'timeout' and 'result' argument.

Update to add 'result' and 'timeout' arguments

---

plugins/zns/zns.c

Pull in the latest libnvme changes to update the zns calling convention
and update the zns plugin accordingly.

plugins/zns: update to match new calling convention

---

Makefile

Makefile: Add missing define (LIBJSONC_14)

---

fabrics.c

fabrics implementations like 'loop' do not have a transport address,
and consequently the address family value doesn't make any sense here.
So do not try to translate the address family to a printable string
if the address itself is empty.

fabrics: do not print 'unrecognized' address family for loop

---

plugins/wdc/wdc-nvme.c

Previously nvme_log_id_to_string returned "WDC Vendor Unique Log ID" if
it was any vendor unique log ID. This causes problems when requesting
JSON, as only the final vendor unique log ID would be output.
Instead, append the log id to the string making each unique.
Also, wdc_log_page_directory previously returned whatever the
output_format was. Instead return 0 if the format was valid.

Use unique names for VULs, also return 0 on success

---

fabrics.c

the uuid buffer size must be at least 37 bytes to avoid
corrupting the memory
Signed-off-by: Maurizio Lombardi <mlombard@redhat.com>

monolithic: fabrics: fix a buffer overrun

---

subprojects/libnvme.wrap

Stop tracking the HEAD version of libnvme with meson's wrap.  Instead
sync it with the git submodule revision. This avoids all sort of
inconsistenies.

build: Sync libnvme wrap revision to the git submodule one

---

nvme.c

We performed a "sec_fd=open(cfg.file)" earlier, so we should not
overwrite the handle.
Signed-off-by: Maurizio Lombardi <mlombard@redhat.com>

nvme: do not leak an open file handle

---

nvme-topology.c

Fix memory leaks in nvme_logical_block_size_from_ns_char()
Free the allocated strings before returning from the function.
Signed-off-by: Maurizio Lombardi <mlombard@redhat.com>

nvme-topology: fix memory leaks

---

nvme-print.c
nvme-print.h
plugins/zns/zns.c

Previously multiple JSON objects would be in the output of
zns-report-zones if there were more than 1024 zones requested because of
the chunked requests sent by nvme-cli.
Fix this to output a single JSON object with one zone_list. This is done
by passing around and appending to the zone_list, then outputting all of
it once after receiving all the reports.

Fix JSON Report Zones Output

---

Documentation/nvme-get-log.1
Documentation/nvme-get-log.html
Documentation/nvme-get-log.txt
nvme.c
plugins/seagate/seagate-nvme.c
plugins/wdc/wdc-nvme.c
subprojects/libnvme.wrap

Add Command Set Identifier (CSI) and Offset Type (OT) support to
get_log as per the Spec 2.0.

nvme: Add Command Set Idendifier and Offset Type to get_log

---

.gitignore
meson.build
meson_options.txt
subprojects/openssl.wrap
subprojects/zlib.wrap

meson wrapdb has support for OpenSSL and zlib. Let's make use of it. This allows building/deploying nvme-cli on systems which have either outdated or no support for those libraries.

build: wrapdb for OpenSSL and zlib, detect libhugetblfs

---

meson.build
meson_options.txt

Simplify the OpenSSL logic by using meson's Feature option.
Suggested-by: Eli Schwartz <eschwartz93@gmail.com>

build: Use Feature option for OpenSSL

---

Documentation/nvme-compare.1
Documentation/nvme-compare.html
Documentation/nvme-compare.txt
Documentation/nvme-format.1
Documentation/nvme-format.html
Documentation/nvme-format.txt
Documentation/nvme-id-ns.1
Documentation/nvme-id-ns.html
Documentation/nvme-id-ns.txt
Documentation/nvme-lnvm-id-ns.1
Documentation/nvme-lnvm-id-ns.html
Documentation/nvme-lnvm-id-ns.txt
Documentation/nvme-read.1
Documentation/nvme-read.html
Documentation/nvme-read.txt
Documentation/nvme-sanitize.1
Documentation/nvme-sanitize.html
Documentation/nvme-sanitize.txt
Documentation/nvme-write-uncor.1
Documentation/nvme-write-uncor.html
Documentation/nvme-write-uncor.txt
Documentation/nvme-write-zeroes.1
Documentation/nvme-write-zeroes.html
Documentation/nvme-write-zeroes.txt
Documentation/nvme-write.1
Documentation/nvme-write.html
Documentation/nvme-write.txt
nvme-print.c
nvme-print.h
nvme.c

All data modifying functions open the namespace exclusive. With the --force or -f
option this can be bypassed.
Signed-off-by: Olaf Schmerse <olaf.schmerse@ionos.com>

nvme: open namespace exclusive by default

---

nvme-private.h
nvme.c
nvme.h

Rewrite of the daa6f93 ("nvme: support ns generic device to submit_io") patch from the monolithic branch.
This PR depends on https://github.com/linux-nvme/libnvme/pull/151

 nvme: support ns generic device to submit_io

---

.github/workflows/meson.yml
nvme.c

A pretty old gcc version (SLE15/gcc 7.5.0) is complaining with
```
[60/65] Compiling C object 'nvme@exe/nvme.c.o'                            
../nvme.c: In function ‘passthru.constprop’:                              
../nvme.c:125:5: warning: ‘huge’ may be used uninitialized in this function
if (huge) {                                                             
^                                                                    
../nvme.c:6431:7: note: ‘huge’ was declared here                          
bool huge;                                                              
^~~~        
```                                                       
On my local machine, I don't see this warning (gcc 11.2.1). I think the warning
is legit as we could end up calling nvme_free() without ever …

Fix unitialized variable

---

nvme-rpmb.c
nvme.c
plugins/intel/intel-nvme.c
plugins/memblaze/memblaze-nvme.c
plugins/micron/micron-nvme.c
plugins/scaleflux/sfx-nvme.c
plugins/seagate/seagate-nvme.c
plugins/shannon/shannon-nvme.c
plugins/toshiba/toshiba-nvme.c
plugins/wdc/wdc-nvme.c
plugins/ymtc/ymtc-nvme.c
plugins/zns/zns.c
subprojects/libnvme.wrap

libnvme changed the calling API, which uses an an argument structure
instead of passing all arguments one by one. Update all call sites
accordingly.

nvme: Adapt to API rework

---

plugins/wdc/wdc-nvme.c
plugins/wdc/wdc-nvme.h

Also, update the WDC plugin version to 1.16.0

Add support for new PCI device ID for SN655 Drive

---

nvme-print.c
nvme.c
plugins/huawei/huawei-nvme.c
plugins/netapp/netapp-nvme.c
plugins/virtium/virtium-nvme.c
plugins/zns/zns.c
subprojects/libnvme.wrap

flbas Bits 6:5 indicate the most significant 2 bits of
the Format Index of the supported LBA Format indicated
in this data structure that was used to format the namespace
using libnvme util function nvme_id_ns_flbas_to_lbaf_inuse
to extract currently used lba index
linux-nvme/libnvme#164

nvme: modify flbas rsvd bits to be used

---

nvme-print.c

We should check if the namespace is available when scanning all
paths in nvme_ctrl_for_each_path(); a controller might be resetting
and might not be able to access the namespaces here.

nvme-print: check namespace in nvme_ctrl_for_each_path()

---

nvme.c

list-ctrl should support CNS values of 12h and 13h.  The support for CNS=13h was dropped from 2.0 version

list-ctrl should support CNS values of 12h and 13h

---

nvme-print.c
nvme.c

fix #1324 using explicit casting, using libnvme macro for cap

---

Documentation/nvme-check-tls-key.txt
Documentation/nvme-gen-tls-key.txt
nvme-builtin.h
nvme.c

Add options to generate and check an NVMe TLS PSK.

nvme: add 'gen-tls-key' and 'check-tls-key' options

---

fabrics.c
nvme.h

nvme_msg() is logging function from libnvme. The cli should not use
the logging infrastructure from the library instead it should use it's
own infrastructure. At this point nvme-cli doesn't have one, so just
use the default stderr for all error messages.
This is a preperation step to unexport the nvme_msg() from libnvme.

fabrics: Stop using nvme_msg from libnvme

---

nvme.c

The offsets into the key are wrong, causing the check to fail on
valid keys.

nvme: fixup 'check-tls-key'

---

nvme.c

Commit 81bb8289f642 ("nvme: update list-ns nsid option") changed the
start index for the namespace argument. But the merge back from the
monolithic branch was incomplete and missed to update the index offset
when calling nvme_identify_allocated_ns_list and
nvme_identify_active_ns_list.

nvme: Call nvme_identify_*list with correct nsid offset

---

fabrics.c
nvme.c
nvme.h
subprojects/libnvme.wrap

libnvme allows to define which file descriptor should be used for
logging. This is only for the fabric related interface relevant hence
this is attached to the nvme_root_r object.
Use common code for this into a helper which maps the verbose command
line levels to the correct log levels and setup nvme_root_r
accordingly.
See
- https://github.com/linux-nvme/libnvme/pull/202
- https://github.com/linux-nvme/libnvme/pull/207

nvme: Adapt to logging changes in libnvme

---

README.md

nvme-cli is now supported in the Ubuntu universe for the [latest releases](https://packages.ubuntu.com/bionic/nvme-cli). We should recommend installing from there rather than the sbates ppa.

README: Update the ubuntu install instructions and fix a formatting issue

---

Documentation/nvme-id-ns-lba-format.1
Documentation/nvme-id-ns-lba-format.html
Documentation/nvme-id-ns-lba-format.txt
Documentation/nvme-nvm-id-ns-lba-format.1
Documentation/nvme-nvm-id-ns-lba-format.html
Documentation/nvme-nvm-id-ns-lba-format.txt
Documentation/nvme-nvm-id-ns.1
Documentation/nvme-nvm-id-ns.html
Documentation/nvme-nvm-id-ns.txt
completions/_nvme
completions/bash-nvme-completion.sh
nvme-builtin.h
nvme-print.c
nvme-print.h
nvme.c
subprojects/libnvme.wrap

Based on libnvme PR https://github.com/linux-nvme/libnvme/pull/166
I was add these command into original id-ns, zns id-ns ...
But this command does not need NSID.
So I split this command as a new command.
if have any opinion for this, please let me know :)

For upstream/tp4095

---

.github/workflows/meson.yml
nvme.c

Currently, warnings are hidden in the logs and the build is marked as
succeeded. Mark all warnings as error so that we see them show up in
the review process.

build: Make CI build fail on warnings.

---

nvme.h

We missed to rename LIBJSONC_14 to CONFIG_JSONC_14 in the nvme.h
header file in 4c3a8c058eb3 ("build: Prefix configuration options").
Fixes: #1354

nvme: Rename LIBJSONC_14 to CONFIG_JSONC_14

---

nvme.c
plugins/wdc/wdc-nvme.c
subprojects/libnvme.wrap

Added size pointer and data area parms to the libnvme functions:  nvme_get_ctrl_telemetry, nvme_get_host_telemetry, and nvme_get_new_host_telemetry.   The size will be calculated by those functions based on the passed data area parm and they returned to the calling function via the size pointer.
Since additional parameters were added, this pull request is dependent on the libnvme pull request (https://github.com/linux-nvme/libnvme/pull/213) that contains the changes to the  nvme_get_ctrl_telemetry, nvme_get_host_telemetry, and nvme_get_new_host_telemetry functions.

[nvme-cli] Add support for data area 4 to get-telemetry-log

---

Documentation/meson.build
meson_options.txt

Build the documentation only if explicitly asked to build it. If not
fallback to install the precompiled versions.

docs: Introduce documentation build option

---

nvme-print.c
plugins/netapp/netapp-nvme.c

We have added a hard dependency to libuuid. Remove the ifdefs and the
dead code.

nvme-print: Remove dead !LIBUUID code

---

nvme-print.c

The root needs to be an array an not an object.
This fixes:
```
nvme: /home/abuild/rpmbuild/BUILD/json-c-json-c-0.15-20200726/json_object.c:1490: json_object_array_add: Assertion `json_object_get_type(jso) == json_type_array' failed.
Program received signal SIGABRT, Aborted.
```

nvme-print: Fix json output for list-subsys

---

plugins/netapp/netapp-nvme.c

After the upgrade to libnvme, the NetApp plugin for ontapdevices
now segfaults due to the wrong json object type as shown below:
nvme: json_object.c:1194: json_object_array_add:
Assertion `json_object_get_type(jso) == json_type_array' failed.
Aborted (core dumped)
Fix this by passing the appropriate json array type for
ontapdevices. Include a couple of minor changes here as well -
add a newline to the end of the json output, and then free the
json root device.

netapp-nvme: fix ontapdevices segfault in json output

---

nvme-print.c

Existing 2.0 branch prints all 7 fw slots including the ones with null.   The check for a valid FW revision number is no longer working due to the change of the definition of frs in  the nvme_firmware_slot struct in the latest libnvme.   Current definition uses "char    frs[7][8]" instead of old definition of  "__u64      frs[7]".

Update nvme-print.c:  Only print FW slots that contain  a valid FW image revision number

---

nvme.c

In nvme_attach_ns the controller list is parsed from the command line into the list array, but not transferred into the ctrlist array before it is passed to nvme_init_ctrl_list.  This change copies the values from list into ctrlist before calling nvme_init_ctrl_list.

Fix ctrlist for attach-ns and detach-ns

---

nvme-print.c

After the recent upgrade to libnvme, 'nvme list -o json' segfaults
due to incorrect json object type passed here. So fix this by passing
the appropriate json object type and invoking it outside the
nvme_for_each_host loop.

nvme-print: fix 'nvme list -o json' segfault

---

nvme.c

The get-ns-id command currently prints the perror status for a
given nvme device instead of its nsid. Fix this by properly
checking the return status of the nvme_get_nsid() function.

nvme: get_ns_id command fails on nvme device

---

plugins/intel/intel-nvme.c

Older gcc do not like the constant initializer expression in the intel
plugin:
../plugins/intel/intel-nvme.c: In function ‘lat_stats_log_scale’:
../plugins/intel/intel-nvme.c:662:47: error: initializer element is not constant
static const int LATENCY_STATS_V4_BASE_VAL = (
Use defines as workaround.

intel: Workaround initializer element is not constant

---

Documentation/cmds-main.txt

updated main commands list with media unit status log and supported capacity config list log pages in cmds-main.txt

cmds-main: Add media unit status log and supported capacity config list log pages in main commands list

---

nvme.c

After the upgrade to libnvme, the nvme telemetry-log command
segfaults for error scenarios as shown below:
NVMe status: Invalid Log Page: The log page indicated is invalid(0x4009)
Failed to acquire telemetry log 16393!
Segmentation fault (core dumped)
Freeing the telemetry log page header for error scenarios is already
handled in the libnvme. So avoid freeing this again here, which led to
this segfault.

nvme: fix segfault in nvme telemetry-log error handling

---

meson.build

When the meson build with static library, does not need rpm Requires

meson: remove rpm dependencies when build as static

---

tests/README
tests/meson.build
tests/nvme_attach_detach_ns_test.py
tests/nvme_create_max_ns_test.py
tests/nvme_format_test.py
tests/nvme_fw_log_test.py
tests/nvme_get_features_test.py
tests/nvme_id_ns_test.py
tests/nvme_read_write_test.py
tests/nvme_test.py
tests/nvme_test_io.py
tests/nvme_test_logger.py
tests/nvme_writezeros_test.py
tests/run_py_linters.py

When switching from the Makefiles to meson we forgot to add build targets to for Python code linting and formatting. While at also update the documentation,
Fixes: #1396

tests: Add support for linting and formatting of Python code

---

ccan/ccan/build_assert/LICENSE
ccan/ccan/build_assert/_info
ccan/ccan/build_assert/build_assert.h

../ccan/ccan/str/str.h:169:10: fatal error: ccan/build_assert/build_assert.h: No such file or directory
169 | #include <ccan/build_assert/build_assert.h>
|          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Add build_assert to fix debug build error

---

subprojects/libnvme.wrap

types: fix status code type bug (wrong masking)
https://github.com/linux-nvme/libnvme/pull/274/commits
Bug:
NVMe status: unrecognized(0x13)
Meant to be:
NVMe status: PRP Offset Invalid: The Offset field for a PRP entry is invalid(0x13)

build: Update libnvme wrap

---

nvme.c

occured from 0adb8c2c79df953bbef9e08ce684239a5650638f
write command always print below error
data size not provided

nvme: nvme write bug fix (no parse for option)

---

nvme.c

Initialize all command line arguments to a default value.
Fixes: #1412

nvme: Initialize all arguments for passthru

---

fabrics.c

The libnvme's nvmf_add_ctrl() might return zero (success) while
having errno set to a non-zero value due to lots of calls inside.
And since nvmf_connect() returns errno primarily, make sure
it's zeroed on success.
See related https://github.com/linux-nvme/libnvme/pull/292

connect: Set errno to zero on nvmf_add_ctrl() success

---

nvme-print.c

This should roughly make the JSON output consistent with the nvme-cli-monolithic branch.
Closes #1424

nvme-print: Make JSON keys consistent with nvme-cli 1.x

---

nvme-topology.c

The state variable might not be initialized at all, that is it can be
NULL. strcmp is not able to handle NULL gracefully.
Fixes: bace574bbe55 ("nvme-topology: fix controller check in scan_subsystem()")
Reported-by: mgerdts (github)
Fixes: #1426

nvme-topology: Check if state variable is a valid string

---

meson.build
nvme.spec.in

revert as 1.16
1. bash-completion
AS IS : DATADIR/bash-completion/completions/nvme/bash-nvme-completion.sh
TO BE : DATADIR/bash-completion/completions/nvme
2. sbindir include prefix
3. sysconfdir do not use prefix
fix rpm macro wrong use

installation path modification

---

nvme-print.c

Generic namespace device is one of I/O paths that needs to be listed up
in the `nvme list` command along with the blkdev.  Print it out in the
simple list command.

nvme-print: print generic device in list command

---

nvme.h

nvme-cli 1.x didn't do any (optional) slash escaping in JSON
output. Don't break backwards compatibility unnecessary.
Fixes: #1411

nvme: Do not slash escape strings in JSON output

---

meson.build
nvme.spec.in

meson:
remove duplicate line (SYSCONFIGDIR)
remove unused variables (libdir, includedir, bindir)
add configuration data of installation directory

rpm: use meson configuration instead of default macros

---

plugins/netapp/netapp-nvme.c

After the upgrade to libnvme, the NetApp plugin for smdevices
segfaults due to the wrong json object type as shown below:
nvme: json_object.c:1194: json_object_array_add:
Assertion `json_object_get_type(jso) == json_type_array' failed.
Aborted (core dumped)
Fix this by passing the appropriate json array type for smdevices.
Also include a couple of minor changes as well - add a newline to
the end of the json output, and then free the json root device.
Tested-by: Clayton Skaggs <claytons@netapp.com>

netapp-nvme: fix smdevices segfault in json output

---

tests/nvme_smart_log_test.py
tests/nvme_test.py

bug fix - added check condition in nvme_smart_log_test.py to check smart log support per namespace
and call accordingly.
added supp_check_id_ctrl wrapper in nvme_test.py to check support
based on passed key value to make it generic.

nvme_smart_log_test: call smart log for all ns based on LPA 

---

Documentation/nvme-create-ns.1
Documentation/nvme-create-ns.html
Documentation/nvme-create-ns.txt
nvme.c
subprojects/libnvme.wrap

Depends on changes in libnvme commit f054255, including removing nvme_init_id_ns and instead just setting fields directly in create_ns.

Add lbstm option to create-ns

---

nvme.c
subprojects/libnvme.wrap

When a device name is specified for 'nvme list-subsys' we should
be printing out only those parts of the tree which relate to the
specified device name, not the entire tree.

nvme: use filter for 'list-subsys <devname>'

---

nvme.c
plugins/intel/intel-nvme.c
plugins/memblaze/memblaze-nvme.c
plugins/scaleflux/sfx-nvme.c
plugins/seagate/seagate-nvme.c
plugins/shannon/shannon-nvme.c
plugins/wdc/wdc-nvme.c
plugins/ymtc/ymtc-nvme.c
plugins/zns/zns.c
util/argconfig.c
util/argconfig.h

getopt_long_only() is able to load the default values directly. Though
the type has to be 'int'. If the target type of argument not 'int'
getopt_long_only will overwrite adjacent memory location.
Reduce the complexity by not using this feature.
Instead use the type bool because libnvme uses bool in 'struct
nvme_fabrics_config'.
Fixes: #1459

argconfig: Do not use default value loading by getopt_long_only

---

fabrics.c
meson.build

Port 'fabrics: Correctly stringify default hostnqn and hostid paths' from libnvme.

fabrics: Correctly stringify discovery.conf and config.json paths

---

nvme.c

strcmp() is tricky, so rather check for something with a given
length.

nvme: Fixup namespace filtering yet again

---

Documentation/nvme-discover.txt
common.h
fabrics.c

The persistence flag will be overwritten by the built in logic. Allow
the user to overwrite this by providing a force command line option.
The code is a bit hard to follow, hence linearize it using forward
jumps. This allows use to centralize the overwrite logic and reduces
my head to hurt.
There is the wish to bring back a feature from 1.x branch which allows
the user always to create new discovery connection. This was done
in 1.x by looking at the KATO value. But this seems a bit fragile.
So I think it's better to introduce a explicit --force flag to overwrite
the logic.
See also:  https://github.com/linux-nvme/nvme-cli/commit/14d0e0f7e0c1b420da65783881c064e49ac7d6d7

fabrics: Introduce force flag to overwrite persistence logic

---

tests/meson.build
tests/nvme_get_lba_status_test.py

test added for get lba status command and updated test list in meson.build with newly added
test nvme_get_lba_status_test.

tests: Add test for get lba status command 

---

Documentation/meson.build
Documentation/nvme-mi-cmd-support-effects-log.txt
nvme-builtin.h
nvme-print.c
nvme-print.h
nvme.c

Added get_mi_cmd_support_effects_log and help text
Print out new persistent_event_log fields - ehai and pelpid
Added function to print the ID NS NSATTR field in human readable text
Dependent on libnvme commit 3dc85542e84c6ffaff86bea4ca754ccbf75bf89c.  I updated subprojects/libnvme.wrap.  Not sure if there on any other requirements for dependent changes.

Nvme 2.0 Changes

---

subprojects/libnvme.wrap

Get "tree: always allocate config file in nvme_read_config()" from upstream.

build: Update libnvme.wrap

---

Documentation/cmds-main.txt
Documentation/meson.build
Documentation/nvme-dim.txt
completions/bash-nvme-completion.sh
fabrics.c
fabrics.h
nvme-builtin.h
nvme.c

TP8010 defines the DIM command (Discovery Information Management)
as a way to Register-with or Deregister-from a Discovery
Controller. This is used for NVMe-over-Fabrics when connecting to
Central Discovery Controllers (CDC).
Signed-off-by: Martin Belanger <martin.belanger@dell.com>

fabrics: Add DIM command

---

fabrics.c

The connect call will fail if there is no /etc/nvme/hostnqn file
available. The 1.x version did have a fallback mechanisme in place
when the config file was missing.
Let's add this feature back by calling nvmf_hostnqn_generate() when
there is no /etc/nvme/hostnqn file.
Fixes: #1473

fabrics: Support connect even when no /etc/nvme/hostnqn file exists

---

fabrics.c

38f5a54a7306 ("fabrics: Support connect even when no /etc/nvme/hostnqn
file exists") introduce a regression. arg_parser() might assign a
static string to hostnqn and/or hostid. Can't free this.

fabrics: Do not free static string

---

plugins/intel/intel-nvme.c

The 'buckets' elements in the statistics output are an array, not
a list of (identically named) objects.

plugins/intel: make 'buckets' a json array

---

Documentation/meson.build
Documentation/nvme-ocp-latency-monitor-log.txt
Documentation/nvme-ocp-smart-add-log.txt
plugins/meson.build
plugins/ocp/ocp-nvme.c
plugins/ocp/ocp-nvme.h

New OCP plugin that consolidates some of the functionality from the other vendor plugins. For now, implements getting of C0 and C3 log pages.
Signed-off-by: Arthur Shau <arthurshau@fb.com>
Signed-off-by: Wei Zhang <wzhang@fb.com>
Signed-off-by: Venkat Ramesh <venkatraghavan@fb.com>

Add new OCP plugin

---

fabrics.c
nvme.c

If nvme_scan_toplopy return failed,  need to free the previously calloc struct nvme_root structure pointer  'r'.
Signed-off-by: Wu Bo <wubo.linux@gmail.com>

Fix memory leak when nvme_scan_toplopy return failed

---

nvme-print.c

Forgotten commit from #1451 that was unrelated to the NULL-values discussed there, still a pretty important fix for the JSON builder. Resubmitting.
This caused memory corruption in case of multiple host records.

nvme-print: Fix json array object instantiation

---

fabrics.c
nvme-print.c
nvme-print.h
nvme.c
subprojects/libnvme.wrap

nvme: update to nvme_scan_filter_t modifications
The scan filter in libnvme has been updated, so update the code
to make use of it.
[dwagner: show also paths for discvoery controller]
Replaces #1482 and #1481

nvme: update to nvme_scan_filter_t modifications

---

fabrics.c

The order of the connect and persistent argument for the recursive
call to __discover is in the wrong order:
__discover(.., bool connect, bool persistent, enum nvme_print_flags flags)

fabrics: Switch connect and persistent argument for __disover

---

fabrics.c

This is the second attempt to address #1476 
The first two patches are only refactoring existing code and there is no change in behavior.
The third patch handles makes the connect-all case behave the same way as the discover regarding the `--persistent` command line argument.

fabrics: Set KATO for discovery controller when connecting

---

fabrics.c

Prefer unique subsystem NQN discovery controllers over well-known subsystem NQN when a persistent controller is created.
This is series is inspired by #1487, but avoiding code duplication.
Note: this is based on #1489

Create persistent controller using unique subsystem NQN

---

util/base64.c

util/base64: fix missing sys/types.h include

---

fabrics.c

If the initial discovery controller creation fails while passing
the -p option to the nvme discover (or connect-all) command, it
could lead to the below segfault:
nvme discover -t rdma -w 192.168.1.114 -a 192.168.1.113 -p
Failed to write to /dev/nvme-fabrics: Connection reset by peer
Segmentation fault (core dumped)
Avoid this segfault by checking if the controller created in
__create_discover_ctrl() is valid before proceeding.

fabrics: avoid segfault when nvme discover fails with the -p option

---

fabrics.c

Currently when nvme discover or connect-all is called without
passing any params, it simply blanks out without any meaningful
error. So add an appropriate error message for such scenarios,
similar to what's done in the erstwhile nvme-cli-monolithic branch.

fabrics: error message for nvme discover/connect-all with no params

---

meson_options.txt

It's unclear to me if we want `system` included in `meson_options.txt` or if it should be implicitly appended in `meson.build`?

meson_options: Include system sub directory

---

completions/bash-nvme-completion.sh

Previously, the associative arrays for the vendor/subcommands and
vendor/functions listings were split into a declaration of type
(using "typeset") and attribute definition (using "readonly"). On
bash 5.1.16 (at least), this lead to the following error (reported
after enabling -xv to expand and print shell inputs)
...
+ . /usr/share/bash-completion/completions/nvme
readonly NO_OPTS=""
++ readonly NO_OPTS=
++ NO_OPTS=
typeset -A _plugin_subcmds
++ typeset -A _plugin_subcmds
readonly _plugin_subcmds=(
[intel]="id-ctrl internal-log lat-stats \
...
++ _plugin_subcmds=(['intel']='id-ctrl internal-log lat-stats...
bash: 'intel': syntax error: operand expected (error token is "'intel'")
...
Using the available flags for "typeset" to declare the variables as
readonly arrays resolved the issue …

completions: Collapse declaration and attribute assignment

---

nvme-print.c

Looks like a copy&past error for the human output.
Reported-by: mgerdts
Fix: 43460fcce21b ("nvme: add identify controller structure 2.0 spec. fields")
Fixes: ##1514

nvme-print: Show mec field in human output instead of vwci

---

fabrics.c

The command line option -J config.json allows to provide a
configuration via a JSON file. We handle this correctly for the
'connect' case but fail to apply the configuration for 'connect-all'
because we missed to add nvme_read_config() in this path.
Fixes: #1521

fabrics: Honor config file for connect-all

---

nvme-print.c

When listing the subsystem, show the path from the first namespace
only. Every namespace has the same paths for a subsystem. This avoids
listening the same controllers for each namespace.
Fixes: #1529 
```bash
nvme-subsys1 - NQN=nqn.1988-11.com.dell:powerstore:00:f03028e73ef7D032D81E
\
+- nvme1 tcp traddr=10.162.198.42,trsvcid=4420 live non-optimized
+- nvme2 tcp traddr=10.162.198.45,trsvcid=4420 live optimized
```

nvme-print: Show paths from the first namespace only

---

Documentation/meson.build

There are alternative binary names for asciidoctor. Search for
'asciidoc' or 'asciidoctor' when building the docs.
See #1543

docs: Search for 'asciidoctor' as alternative

---

Documentation/meson.build

Apparently, asciidoc and asciidoctor are two different
projects. nvme-cli depends on the former. Depend on asciidoc only and
make it a hard dependency when the user ask to build the doc.
Fixes: 6b18babf40d4 ("docs: Search for 'asciidoctor' as alternative")
Fixes #1543

docs: Don't confuse asciidoc with asciidoctor

---

nvme-print.c
nvme-print.h
nvme.c

'nvme list-subsys' shows the state of all controllers belonging to a
subsystem. The ANA state is a per namespace attribute hence it only
makes sense to show it if the user lists the subsystem for a
namespace.
Fixes: 7435ed9ae6a6 ("nvme-print: Show paths from the first namespace only")
Fixes: #1542

nvme-print: Show ANA state only for one namespace

---

fabrics.c
subprojects/libnvme.wrap

fabrics: Already connected uses a different error code
The libnvme library reports connection errors with it's own error
codes, e.g. ENVME_CONNECT_ALREADY stands for already connected. Update
the connect-all call so that it prints 'already connected' again.
Fixes: #1505

Log connect errors

---

fabrics.c
linux/nvme.h

TP8014 added a new discovery log page entry type '3' for the
'current discovery subsystem'; decode it accordingly.

fabrics: decode 'current' discovery subsystem

---

nvme.c

Since "18de3a6d Convert to libnvme", an "nvme compare" was being
converted incorrectly into an "nvme write" in submit_io().
Fixes #1562.
Signed-off-by: John Levon <john.levon@nutanix.com>

submit_io(): fix "nvme compare" to pass correct command

---

README.md

The min kernel version is v4.15 kernel because libnvme depends on the
/sys/class/nvme-subsystem interface.
Fixes #1516

README: add note about min kernel version

---

.github/workflows/meson.yml

v4 of the setup-python helper wants to know the python version number.

ci: add python version to setup-python environment

---

tests/README
tests/meson.build
tests/nvme_attach_detach_ns_test.py
tests/nvme_compare_test.py
tests/nvme_copy_test.py
tests/nvme_create_max_ns_test.py
tests/nvme_dsm_test.py
tests/nvme_error_log_test.py
tests/nvme_flush_test.py
tests/nvme_format_test.py
tests/nvme_fw_log_test.py
tests/nvme_get_features_test.py
tests/nvme_get_lba_status_test.py
tests/nvme_id_ctrl_test.py
tests/nvme_id_ns_test.py
tests/nvme_lba_status_log_test.py
tests/nvme_read_write_test.py
tests/nvme_simple_template_test.py
tests/nvme_smart_log_test.py
tests/nvme_test.py
tests/nvme_test_io.py
tests/nvme_test_logger.py
tests/nvme_verify_test.py
tests/nvme_writeuncor_test.py
tests/nvme_writezeros_test.py

The test are still using nose which has been superseeded by
nose2. Update the tests to use the nose2 and unittest.
To minimize errors in most of the porting is done using sed, e.g
's/TestNVMeIO.__init__(self)/super().setUp()/g'.
While at it also update the build system and move the test files to
the build dir. This avoids in tree exectution of the Python files
which leaves the __pycache__ dir in the source tree.
This also fixes the problem, that the config file is not found when
'meson test -C .build' is used. We have the prober dir structure for
Python and nose2 to find all resources in the build root. Furthermore,
when running the tests the output is captured in the nvmetests
dir. This dir is also created under the build root dir.
Fixes: …

tests: Port to nose2 and unittest

---

completions/bash-nvme-completion.sh

Fixed:
* error when completion file is sourced for the second time
* typo resulted in broken completion for seagate plugin

Bash Completion fixes

---

Documentation/nvme-id-ns.txt

as documented in NVM Command Set Specification Revision 1.0b,
chapter 4.1.5.1 - NVM Command Set Identify Namespace Data Structure (CNS 00h).

docs: Document nvme-id-ns behavior when nsid is 0xFFFFFFFF

---

.github/reviewers.yml
.github/workflows/auto_request_review.yml

Arthur has asked  to be added as reviewer to the OCP plugin changes. 
Let's setup an auto review bot. We might also want to hook up this for the other
plugins in the future.

ci: Add auto review bot

---

plugins/solidigm/solidigm-garbage-collection.c
plugins/solidigm/solidigm-latency-tracking.c
plugins/solidigm/solidigm-nvme.h
plugins/solidigm/solidigm-smart.c

Removed -b flag option from solidigm plug-in, in favor of "-o binary".

Added average latency field to solidigm latency-tracking-log.

---

.github/workflows/auto_request_review.yml

Currently setting the reviewer from the bot fails with:
Error: HttpError: Resource not accessible by integration
The GITHUB_TOKEN needs enough permission to update the PR.
Links: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token

build: Give auto review bot write permission on pull request

---

plugins/wdc/wdc-nvme.c

This series has a couple of small fixes for the wdc plugin, preventing a double close, and outputting unintialised log data on failures.
Found through code inspection only - I don't have target hardware to test.

plugins/wdc: telemetry log fixes

---

nvme-print.c
nvme.c

Currently, nvme get-feature with the -H option fails to print detailed
info for specific feature ids such as number of IO queues (fid=0x07),
async event config (fid=0x0b), KATO value (fid=0x0f), etc. This is
because nvme_feature_show_fields() is invoked only if the corresponding
'buf' pointer is valid, which is not necessary for the above feature
ids. So fix this by removing this restriction while invoking
nvme_feature_show_fields(). At the same time, ensure this 'buf' pointer
is appropriately validated before use in this function.
Fixes: bcab212 ("nvme: coverity fixes")

nvme: fix nvme get-feature with -H option

---

nvme-print.c

The previous code would skip the first entry in the list.  This fix will print all entries.

print: Fix nvme_id_uuid_list

---

nvme.c
plugins/innogrit/innogrit-nvme.c
plugins/micron/micron-nvme.c
plugins/seagate/seagate-nvme.c
plugins/transcend/transcend-nvme.c
plugins/virtium/virtium-nvme.c
plugins/wdc/wdc-nvme.c

libnvme 1.0 hard codes the rae value for all nvme_get_nsid_log to
false. The upcoming 1.1 release will pass the rae value through
to the kernel. This is causing a behavior change. To be on the safe
side set all rae=true to false.
At least for nvme_get_log_error and nvme_get_log_smart this seems also
what the spec recommends.
Reported-by: Jeremy Kerr <jk@codeconstruct.com.au>
See #https://github.com/linux-nvme/libnvme/issues/437

nvme: Set default rae value for nvme_get_nsid_log users

---

nvme-print.c

Trivial fix to sanitize the nvme get-feature async event config
output by ensuring the details printed are properly aligned.

nvme-print: sanitize the get-feature async event config output

---

fabrics.c

The dhchap-ctrl-secret is per controller but discover and connect-all
operate on several controllers. As this get's very fast very
complicated how to express this on the command line, we defer here to
JSON config file in this case.
Fixes: #1618

fabrics: Remove dhchap-ctrl-secret from discover/connect-all

---

nvme.c

We print error and status on the top level, so no need to print it a
helper.
Fixes: #1625

nvme: Do not print error message in collect_effects_log helper

---

release.sh

This syncs the release.sh script with the one in libnvme.
This should be merged after v2.1 release.
See #https://github.com/linux-nvme/libnvme/issues/429 and https://github.com/linux-nvme/libnvme/pull/433

Sync release steps with libnvme
